D7Texte.add({
  id: "sach-feuerwehr-m", titel: "Nachwuchs für den Notfall: die Jugendfeuerwehr", textsorte: "Sachtext", zug: "M7",
  modul: "Sachtexte und Informationen", unterthema: "Zusammenfassung", woerter: 391, schwierigkeit: "mittel",
  lehrplan: "D7 2.1, 2.3, 3.2", thema: "Jugendfeuerwehr", quelle: "Eigenständig für GRUMI erstellt.", lizenz: "eigener Text",
  erstellung: "eigener Text für GRUMI", zeilennummern: true, probe: false,
  absaetze: [
    "Wer die 112 wählt, verlässt sich darauf, dass wenige Minuten später Hilfe eintrifft. Was viele nicht wissen: Die allermeisten Feuerwehrleute in Deutschland sind keine Berufsfeuerwehrleute, sondern Freiwillige. Sie gehen einem ganz anderen Beruf nach und lassen alles stehen und liegen, sobald der Alarm kommt. Bundesweit engagieren sich auf diese Weise rund eine Million Menschen. Nur größere Städte unterhalten eine Berufsfeuerwehr.",
    "Dieses System funktioniert nur, wenn ständig neue Helferinnen und Helfer nachrücken. Fast jede Feuerwehr hat deshalb eine Jugendgruppe. In Bayern können Mädchen und Jungen mit zwölf Jahren eintreten. Helm, Jacke und Handschuhe werden gestellt, und einen Mitgliedsbeitrag gibt es nicht.",
    "In den Übungsstunden lernen die Jugendlichen Schritt für Schritt das Handwerk der Feuerwehr. Sie rollen Schläuche aus und kuppeln sie zusammen, üben Knoten, funken miteinander und lernen die Geräte im Löschfahrzeug kennen. Dazu kommt etwas Theorie: Wie entsteht ein Feuer, und warum darf man brennendes Fett niemals mit Wasser löschen? Einen festen Platz hat außerdem die Erste Hilfe. Wer in der Jugendfeuerwehr war, weiß deshalb auch im Alltag, was bei einem Unfall zu tun ist.",
    "An echten Einsätzen nehmen die Jüngeren nicht teil; das wäre zu gefährlich. Mit 16 Jahren dürfen sie in Bayern bei manchen Einsätzen bereits außerhalb des Gefahrenbereichs mithelfen, erst mit 18 Jahren gehören sie vollständig zur Einsatzmannschaft. Bis dahin wird geübt, damit im Ernstfall jeder Handgriff sitzt. Bei Wettbewerben messen sich die Gruppen mit anderen Jugendfeuerwehren und zeigen, wie schnell und genau sie zusammenarbeiten.",
    "Mindestens ebenso wichtig wie die Technik ist die Gemeinschaft. Die Gruppen fahren ins Zeltlager, unternehmen Ausflüge und feiern zusammen. Viele Mitglieder nennen den Zusammenhalt als wichtigsten Grund, dabeizubleiben: Bei der Feuerwehr muss sich jeder auf den anderen verlassen können.",
    "Gebraucht wird der Nachwuchs dringend. Zum einen hat sich die Arbeit der Feuerwehr verändert: Brände machen heute nur noch einen kleinen Teil der Einsätze aus. Viel häufiger rücken die Wehren zu Verkehrsunfällen aus, pumpen nach Unwettern Keller leer oder beseitigen umgestürzte Bäume. Zum anderen wird es vielerorts schwieriger, tagsüber genügend Einsatzkräfte zusammenzubekommen, weil viele Mitglieder weit entfernt von ihrem Wohnort arbeiten.",
    "Für die Jugendlichen selbst zahlt sich die Zeit bei der Feuerwehr ebenfalls aus. Sie lernen, Verantwortung zu übernehmen, in einer Gruppe zu arbeiten und in schwierigen Lagen ruhig zu bleiben. Solche Fähigkeiten sind später auch bei der Suche nach einem Ausbildungsplatz gefragt. Wer möchte, besucht Lehrgänge und leitet eines Tages selbst eine Jugendgruppe."
  ]
});
