/* Aufgaben fuer "Gleichungen loesen", Mathematik 7M und 7R.
   Stufen nach LehrplanPLUS Mittelschule Bayern, Lernbereich M7 7 Gleichungen:
   Terme durch Einsetzen berechnen, Balkenwaage, ax + b = c mit ganzen Zahlen,
   Terme vereinfachen, Probe, Sachsituationen mit Gleichungen darstellen.
   Die Loesungen berechnet rechnen7.js aus Term bzw. Gleichung. */
window.M7_GLEICHUNGEN = {
  gruppen: [
    { id: "grundlagen", titel: "Grundlagen", text: "Terme berechnen und die ersten Gleichungen" },
    { id: "loesen", titel: "Gleichungen lösen", text: "Zwei Schritte, Vorzeichen, zusammenfassen" },
    { id: "sach", titel: "Texte und Sachaufgaben", text: "Vom Text zur Gleichung" },
  ],

  stufen: [
    {
      id: "terme",
      gruppe: "grundlagen",
      titel: "Terme berechnen",
      kurz: "Zahl für x einsetzen",
      typ: "term",
      ziel: "Du setzt für x eine Zahl ein und rechnest den Term aus.",
      lehrplan: "Wert von Termen durch Einsetzen berechnen",
      beispiel: {
        aufgabe: "Berechne 3x + 2 für x = 4.",
        zeilen: [["3 · 4 + 2", ""], ["= 12 + 2", ""], ["= 14", ""]],
        merksatz: "3x bedeutet 3 · x. Setze die Zahl für x ein und schreibe den Malpunkt dazu. Dann gilt: Punkt vor Strich.",
        tabelle: { term: "3x + 2", werte: [1, 2, 3, 4] },
      },
      aufgaben: [
        { term: "x + 5", x: 3 },
        { term: "2x", x: 6 },
        { term: "3x + 1", x: 4 },
        { term: "4x - 2", x: 5 },
        { term: "10 - x", x: 4 },
        { term: "5 + 2x", x: 7 },
        { term: "2x + 3", x: 0 },
        { term: "3x - 4", x: -2 },
      ],
    },
    {
      id: "plusminus",
      gruppe: "grundlagen",
      titel: "Plus und minus",
      kurz: "x + 4 = 9",
      typ: "gleichung",
      ziel: "Du rechnest auf beiden Seiten das Gegenteil: Aus + wird −, aus − wird +.",
      lehrplan: "Gleichungen mit der Balkenwaage verstehen",
      beispiel: {
        aufgabe: "x + 3 = 7",
        zeilen: [["x + 3 = 7", "− 3"], ["x = 4", ""]],
        probe: "4 + 3 = 7 ✓",
        waage: true,
        merksatz: "Eine Gleichung ist wie eine Waage im Gleichgewicht. Was du links wegnimmst, nimmst du auch rechts weg.",
      },
      aufgaben: ["x + 4 = 9", "x + 7 = 15", "x - 3 = 6", "x + 12 = 30", "x - 6 = 10", "9 + x = 21", "15 = x + 8", "x - 11 = 9"],
    },
    {
      id: "mal",
      gruppe: "grundlagen",
      titel: "Mal und geteilt",
      kurz: "3x = 12",
      typ: "gleichung",
      ziel: "3x heißt 3 · x. Das Gegenteil von · 3 ist : 3.",
      lehrplan: "Gleichungen mit der Balkenwaage verstehen",
      beispiel: {
        aufgabe: "3x = 12",
        zeilen: [["3x = 12", ": 3"], ["x = 4", ""]],
        probe: "3 · 4 = 12 ✓",
        waage: true,
        merksatz: "Teile auf beiden Seiten durch die Zahl vor dem x.",
      },
      aufgaben: ["2x = 10", "3x = 12", "5x = 35", "4x = 36", "6x = 48", "10x = 120", "7x = 42", "24 = 8x"],
    },
    {
      id: "zweischritte",
      gruppe: "loesen",
      titel: "Zwei Schritte",
      kurz: "2x + 3 = 11",
      typ: "gleichung",
      ziel: "Erst plus oder minus, dann geteilt: So steht x am Ende allein.",
      lehrplan: "ax + b = c durch Äquivalenzumformungen lösen, Probe",
      beispiel: {
        aufgabe: "2x + 3 = 11",
        zeilen: [["2x + 3 = 11", "− 3"], ["2x = 8", ": 2"], ["x = 4", ""]],
        probe: "2 · 4 + 3 = 11 ✓",
        waage: true,
        merksatz: "Zuerst die Zahl ohne x wegrechnen. Dann durch die Zahl vor dem x teilen.",
      },
      aufgaben: ["2x + 3 = 11", "3x + 5 = 20", "4x - 3 = 21", "2x - 7 = 9", "5x + 10 = 45", "3x - 12 = 18", "6x + 4 = 58", "50 = 4x + 6"],
    },
    {
      id: "negativ",
      gruppe: "loesen",
      titel: "Negative Zahlen",
      kurz: "−3x + 5 = 20",
      typ: "gleichung",
      ziel: "Du rechnest wie bisher, achtest aber genau auf die Vorzeichen.",
      lehrplan: "ax + b = c mit ganzen Zahlen, Rechenregeln rationaler Zahlen",
      beispiel: {
        aufgabe: "-3x + 5 = 20",
        zeilen: [["-3x + 5 = 20", "− 5"], ["-3x = 15", ": (−3)"], ["x = -5", ""]],
        probe: "−3 · (−5) + 5 = 15 + 5 = 20 ✓",
        regeln: ["Plus mal Minus ergibt Minus.", "Minus mal Minus ergibt Plus.", "Beim Teilen gilt dasselbe: 15 : (−3) = −5."],
        merksatz: "Teilst du durch eine negative Zahl, nimm das Minus mit.",
      },
      aufgaben: ["x + 8 = 3", "x - 4 = -10", "3x = -12", "-2x = 14", "2x + 9 = 3", "-3x + 5 = 29", "-4x + 6 = -14", "-5x - 8 = 42"],
    },
    {
      id: "zusammenfassen",
      gruppe: "loesen",
      titel: "Erst zusammen\u00ADfassen",
      kurz: "2x + 3x + 4 = 29",
      typ: "gleichung",
      ziel: "Fasse Gleiches zusammen: x zu x, Zahlen zu Zahlen. Dann löst du wie gewohnt.",
      lehrplan: "Terme mit Rechengesetzen vereinfachen",
      beispiel: {
        aufgabe: "2x + 5 + 3x = 30",
        zeilen: [["2x + 5 + 3x = 30", "zusammenfassen"], ["5x + 5 = 30", "− 5"], ["5x = 25", ": 5"], ["x = 5", ""]],
        probe: "2 · 5 + 5 + 3 · 5 = 10 + 5 + 15 = 30 ✓",
        merksatz: "Nur Gleiches zusammenfassen: 2x + 3x = 5x. Aber 5x + 5 bleibt 5x + 5.",
      },
      aufgaben: ["2x + 3x = 25", "4x + 2x + 3 = 27", "5x - 2x + 7 = 25", "3x + 4 + 2x = 39", "6x + 5 - x = 45", "2x + 8 + 3x - 3 = 50", "7x - 4 - 3x = 36", "3x + 6 - 5x = 16"],
    },
    {
      id: "raetsel",
      gruppe: "sach",
      titel: "Zahlenrätsel",
      kurz: "Ich denke mir eine Zahl …",
      typ: "raetsel",
      ziel: "Du übersetzt den Text in eine Gleichung. Die gesuchte Zahl heißt x.",
      lehrplan: "Sachsituationen mit Gleichungen darstellen",
      beispiel: {
        aufgabe: "Ich denke mir eine Zahl. Ich nehme sie mal 3 und addiere 4. Ich erhalte 19.",
        zeilen: [["x = gedachte Zahl", ""], ["3x + 4 = 19", "− 4"], ["3x = 15", ": 3"], ["x = 5", ""]],
        antwort: "Die Zahl heißt 5.",
        probe: "3 · 5 + 4 = 19 ✓",
        uebersetzung: [
          ["eine Zahl", "x"],
          ["das Doppelte, das Dreifache", "2x, 3x"],
          ["addieren, dazuzählen, vermehren um", "+"],
          ["subtrahieren, abziehen, vermindern um", "−"],
          ["ich erhalte, das ergibt", "="],
        ],
      },
      aufgaben: [
        { text: "Ich denke mir eine Zahl und addiere 9. Ich erhalte 25.", modell: "x + 9 = 25" },
        { text: "Das Dreifache einer Zahl ist 27.", modell: "3x = 27" },
        { text: "Ich nehme eine Zahl mal 2 und addiere 5. Ich erhalte 17.", modell: "2x + 5 = 17" },
        { text: "Ich nehme eine Zahl mal 4 und subtrahiere 7. Ich erhalte 25.", modell: "4x - 7 = 25" },
        { text: "Das Fünffache einer Zahl, vermindert um 3, ergibt 47.", modell: "5x - 3 = 47" },
        { text: "Wenn ich zum Doppelten einer Zahl 11 addiere, erhalte ich 45.", modell: "2x + 11 = 45" },
        { text: "Ich subtrahiere von einer Zahl 12 und erhalte −5.", modell: "x - 12 = -5" },
        { text: "Das Dreifache einer Zahl plus 8 ergibt −13.", modell: "3x + 8 = -13" },
      ].map((aufgabe) => ({ ...aufgabe, frage: "Wie heißt die Zahl?", variable: "x = gedachte Zahl", antwort: "Die Zahl heißt …" })),
    },
    {
      id: "sachaufgaben",
      gruppe: "sach",
      titel: "Sachaufgaben",
      kurz: "Einkauf, Handy, Taxi",
      typ: "sachaufgabe",
      ziel: "Du legst x fest, stellst die Gleichung auf, löst sie und antwortest.",
      lehrplan: "Sachsituationen aus der Lebenswelt mit Gleichungen lösen",
      beispiel: {
        aufgabe: "Ein Handytarif kostet 5 € Grundgebühr im Monat. Jedes Gigabyte kostet 2 €. Emre zahlt im Mai 17 €. Wie viele Gigabyte hat er gebucht?",
        zeilen: [["x = Anzahl der Gigabyte", ""], ["2x + 5 = 17", "− 5"], ["2x = 12", ": 2"], ["x = 6", ""]],
        antwort: "Emre hat 6 Gigabyte gebucht.",
        probe: "2 · 6 + 5 = 17 ✓",
        schritte: ["x festlegen", "Gleichung aufstellen", "Gleichung lösen", "Antwort geben (und Probe am Text)"],
      },
      aufgaben: [
        { text: "Lena kauft 3 gleiche Hefte und einen Block für 2 €. Sie bezahlt zusammen 8 €. Wie viel kostet ein Heft?", variable: "x = Preis für ein Heft (in €)", modell: "3x + 2 = 8" },
        { text: "Tim kauft 2 Kinokarten und eine Tüte Popcorn für 5 €. Er bezahlt zusammen 23 €. Wie viel kostet eine Kinokarte?", variable: "x = Preis für eine Kinokarte (in €)", modell: "2x + 5 = 23" },
        { text: "Ein Handytarif kostet 4 € Grundgebühr im Monat. Jedes Gigabyte kostet 3 €. Mia zahlt im Juni 19 €. Wie viele Gigabyte hat sie gebucht?", variable: "x = Anzahl der Gigabyte", modell: "3x + 4 = 19" },
        { text: "Der Eintritt ins Freibad kostet für Schüler 3 €. Die Klasse 7b bezahlt für alle Schüler und eine Begleitperson (6 €) zusammen 78 €. Wie viele Schüler sind dabei?", variable: "x = Anzahl der Schüler", modell: "3x + 6 = 78" },
        { text: "Ein Taxi kostet 4 € Grundpreis und 2 € für jeden Kilometer. Eine Fahrt kostet 30 €. Wie viele Kilometer ist das Taxi gefahren?", variable: "x = Anzahl der Kilometer", modell: "2x + 4 = 30" },
        { text: "Mia hat schon 15 € in der Spardose. Sie spart jede Woche gleich viel. Nach 6 Wochen hat sie 51 €. Wie viel spart sie pro Woche?", variable: "x = Betrag pro Woche (in €)", modell: "6x + 15 = 51" },
        { text: "Ein Rechteck ist 7 cm lang. Sein Umfang beträgt 24 cm. Wie breit ist das Rechteck?", variable: "x = Breite (in cm)", modell: "2x + 14 = 24", tipp: "Umfang = 2 · Länge + 2 · Breite" },
        { text: "Am Morgen ist es −4 °C. Bis Mittag steigt die Temperatur jede Stunde um 3 °C. Um 12 Uhr sind es 11 °C. Wie viele Stunden ist die Temperatur gestiegen?", variable: "x = Anzahl der Stunden", modell: "3x - 4 = 11" },
      ],
    },
    {
      id: "profi",
      gruppe: "sach",
      titel: "Profi: drei Größen",
      kurz: "vor allem 7M",
      typ: "profi",
      mZug: true,
      ziel: "Drei Mengen, eine Gesamtzahl: Eine Menge ist x, die anderen schreibst du mit x.",
      lehrplan: "Sachsituationen mit Gleichungen darstellen (M-Zug)",
      beispiel: {
        aufgabe: "Eine Schule bestellt 390 Hefte in drei Farben. Von den roten Heften werden 50 mehr bestellt als von den blauen. Von den gelben Heften werden 20 weniger bestellt als von den blauen. Wie viele Hefte jeder Farbe werden bestellt?",
        tabelle3: [["blaue Hefte", "x"], ["rote Hefte", "x + 50"], ["gelbe Hefte", "x − 20"], ["zusammen", "390"]],
        zeilen: [["x + x + 50 + x − 20 = 390", "zusammenfassen"], ["3x + 30 = 390", "− 30"], ["3x = 360", ": 3"], ["x = 120", ""]],
        werte: ["blau: 120", "rot: 120 + 50 = 170", "gelb: 120 − 20 = 100"],
        antwort: "Es werden 120 blaue, 170 rote und 100 gelbe Hefte bestellt.",
        probe: "120 + 170 + 100 = 390 ✓",
      },
      aufgaben: [
        {
          text: "In einem Lager stehen 315 Kartons in drei Reihen. In Reihe A stehen 25 weniger als in Reihe B. In Reihe C stehen 40 mehr als in Reihe B. Wie viele Kartons stehen in jeder Reihe?",
          variable: "x = Kartons in Reihe B",
          terme: ["Reihe B: x", "Reihe A: x − 25", "Reihe C: x + 40"],
          modell: "x + (x - 25) + (x + 40) = 315",
          werte: [{ name: "Reihe A", wert: 75 }, { name: "Reihe B", wert: 100 }, { name: "Reihe C", wert: 140 }],
        },
        {
          text: "Eine Klasse sammelt 210 Pfandflaschen in drei Größen. Von den kleinen Flaschen gibt es 30 mehr als von den mittleren. Von den großen Flaschen gibt es 15 weniger als von den mittleren. Wie viele Flaschen jeder Größe wurden gesammelt?",
          variable: "x = Anzahl der mittleren Flaschen",
          terme: ["mittlere: x", "kleine: x + 30", "große: x − 15"],
          modell: "x + (x + 30) + (x - 15) = 210",
          werte: [{ name: "kleine Flaschen", wert: 95 }, { name: "mittlere Flaschen", wert: 65 }, { name: "große Flaschen", wert: 50 }],
        },
        {
          text: "Ein Sportgeschäft verkauft 310 Bälle in drei Farben. Von den roten Bällen werden 20 mehr verkauft als von den blauen. Von den gelben Bällen werden 10 weniger verkauft als von den blauen. Wie viele Bälle jeder Farbe werden verkauft?",
          variable: "x = Anzahl der blauen Bälle",
          terme: ["blau: x", "rot: x + 20", "gelb: x − 10"],
          modell: "x + (x + 20) + (x - 10) = 310",
          werte: [{ name: "rote Bälle", wert: 120 }, { name: "blaue Bälle", wert: 100 }, { name: "gelbe Bälle", wert: 90 }],
        },
        {
          text: "Eine Bibliothek verleiht in drei Wochen 450 Bücher. In Woche 1 werden 60 Bücher weniger verliehen als in Woche 2. In Woche 3 werden 90 Bücher mehr verliehen als in Woche 2. Wie viele Bücher werden in jeder Woche verliehen?",
          variable: "x = Bücher in Woche 2",
          terme: ["Woche 2: x", "Woche 1: x − 60", "Woche 3: x + 90"],
          modell: "x + (x - 60) + (x + 90) = 450",
          werte: [{ name: "Woche 1", wert: 80 }, { name: "Woche 2", wert: 140 }, { name: "Woche 3", wert: 230 }],
        },
        {
          text: "Eine Bäckerei verkauft 240 Brötchen in drei Sorten. Von den Körnerbrötchen werden 18 weniger verkauft als von den normalen Brötchen. Von den Käsebrötchen werden 42 mehr verkauft als von den normalen. Wie viele Brötchen jeder Sorte werden verkauft?",
          variable: "x = Anzahl der normalen Brötchen",
          terme: ["normale: x", "Körnerbrötchen: x − 18", "Käsebrötchen: x + 42"],
          modell: "x + (x - 18) + (x + 42) = 240",
          werte: [{ name: "Körnerbrötchen", wert: 54 }, { name: "normale Brötchen", wert: 72 }, { name: "Käsebrötchen", wert: 114 }],
        },
        {
          text: "In einer Werkstatt liegen 560 Schrauben in drei Kisten. In der kleinen Kiste liegen 80 weniger als in der mittleren. In der großen Kiste liegen 160 mehr als in der mittleren. Wie viele Schrauben liegen in jeder Kiste?",
          variable: "x = Schrauben in der mittleren Kiste",
          terme: ["mittlere Kiste: x", "kleine Kiste: x − 80", "große Kiste: x + 160"],
          modell: "x + (x - 80) + (x + 160) = 560",
          werte: [{ name: "kleine Kiste", wert: 80 }, { name: "mittlere Kiste", wert: 160 }, { name: "große Kiste", wert: 320 }],
        },
        {
          text: "Eine Gärtnerei verkauft 270 Pflanzen in drei Größen. Von den kleinen Pflanzen werden 45 mehr verkauft als von den mittleren. Von den großen Pflanzen werden 30 weniger verkauft als von den mittleren. Wie viele Pflanzen jeder Größe werden verkauft?",
          variable: "x = Anzahl der mittleren Pflanzen",
          terme: ["mittlere: x", "kleine: x + 45", "große: x − 30"],
          modell: "x + (x + 45) + (x - 30) = 270",
          werte: [{ name: "kleine Pflanzen", wert: 130 }, { name: "mittlere Pflanzen", wert: 85 }, { name: "große Pflanzen", wert: 55 }],
        },
        {
          text: "Für ein Schulfest werden 380 Getränke in drei Sorten gekauft. Von den Wasserflaschen gibt es 40 mehr als von den Saftflaschen. Von den Limonadenflaschen gibt es 20 weniger als von den Saftflaschen. Wie viele Flaschen jeder Sorte gibt es?",
          variable: "x = Anzahl der Saftflaschen",
          terme: ["Saft: x", "Wasser: x + 40", "Limonade: x − 20"],
          modell: "x + (x + 40) + (x - 20) = 380",
          werte: [{ name: "Wasser", wert: 160 }, { name: "Saft", wert: 120 }, { name: "Limonade", wert: 100 }],
        },
      ],
    },
  ],
};
