services:
  - type: web
    name: grumi-mathe-ki
    runtime: node
    plan: free
    rootDir: render-mathe-ki
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
