window.GEO_QUALI = {
  levelLabel: "Kreis",
  themeLine: "Thema: Kreis (Umfang und Flächeninhalt), Mathematik 9. Rechne mit π = 3,14.",
  tasks: [
    {
      id: "1",
      group: "Tabelle",
      title: "Kreis: fehlende Werte",
      text: "Berechne für die Kreise die fehlenden Werte. Rechne mit π = 3,14.",
      table: {
        cols: ["a", "b", "c"],
        rows: [
          { label: "r", cells: ["5 cm", "", ""] },
          { label: "d", cells: ["", "8 cm", ""] },
          { label: "u", cells: ["", "", "31,4 cm"] },
          { label: "A", cells: ["", "", ""] },
        ],
      },
      given: ["a) r = 5 cm", "b) d = 8 cm", "c) u = 31,4 cm"],
      searched: "r, d, Umfang u und Flächeninhalt A",
      noSketch: true,
      plan: ["d = 2 · r", "r = d : 2", "u = 2 · π · r", "r = u : (2 · π)", "A = π · r²"],
      solution: "a) d = 10 cm; u = 2 · 3,14 · 5 = 31,4 cm; A = 3,14 · 5² = 78,5 cm². b) r = 8 : 2 = 4 cm; u = 2 · 3,14 · 4 = 25,12 cm; A = 3,14 · 4² = 50,24 cm². c) r = 31,4 : (2 · 3,14) = 5 cm; d = 10 cm; A = 3,14 · 5² = 78,5 cm².",
      result: "a) d = 10 cm, u = 31,4 cm, A = 78,5 cm²; b) r = 4 cm, u = 25,12 cm, A = 50,24 cm²; c) r = 5 cm, d = 10 cm, A = 78,5 cm²",
    },
    {
      id: "2",
      group: "Grundlagen",
      title: "Umfang aus dem Radius",
      text: "Ein Kreis hat den Radius r = 7 cm. Berechne den Umfang. Rechne mit π = 3,14.",
      given: ["r = 7 cm", "π = 3,14"],
      searched: "Umfang u",
      plan: ["u = 2 · π · r"],
      solution: "u = 2 · 3,14 · 7 = 43,96 cm.",
      result: "u = 43,96 cm",
    },
    {
      id: "3",
      group: "Grundlagen",
      title: "Fläche aus dem Radius",
      text: "Ein Kreis hat den Radius r = 6 cm. Berechne den Flächeninhalt. Rechne mit π = 3,14.",
      given: ["r = 6 cm", "π = 3,14"],
      searched: "Flächeninhalt A",
      plan: ["A = π · r²"],
      solution: "A = 3,14 · 6² = 3,14 · 36 = 113,04 cm².",
      result: "A = 113,04 cm²",
    },
    {
      id: "4",
      group: "Umkehraufgabe",
      title: "Radius aus dem Umfang",
      text: "Ein Kreis hat den Umfang u = 18,84 cm. Berechne den Radius. Rechne mit π = 3,14.",
      given: ["u = 18,84 cm", "π = 3,14"],
      searched: "Radius r",
      plan: ["u = 2 · π · r", "r = u : (2 · π)"],
      solution: "r = 18,84 : (2 · 3,14) = 18,84 : 6,28 = 3 cm.",
      result: "r = 3 cm",
    },
    {
      id: "5",
      group: "Umkehraufgabe",
      title: "Radius aus der Fläche",
      text: "Ein Kreis hat den Flächeninhalt A = 50,24 cm². Berechne den Radius. Rechne mit π = 3,14.",
      given: ["A = 50,24 cm²", "π = 3,14"],
      searched: "Radius r",
      plan: ["A = π · r²", "r² = A : π", "r = √(A : π)"],
      solution: "r² = 50,24 : 3,14 = 16; r = √16 = 4 cm.",
      result: "r = 4 cm",
    },
    {
      id: "6",
      group: "Sachaufgabe",
      title: "Reifen-Umdrehungen",
      text: "Ein Reifen hat den Durchmesser d = 50 cm. a) Berechne den Umfang in Metern. b) Wie viele Umdrehungen macht der Reifen auf einer Strecke von 1 km? Rechne mit π = 3,14 und runde auf ganze Umdrehungen.",
      given: ["d = 50 cm = 0,5 m", "Strecke 1 km = 1000 m", "π = 3,14"],
      searched: "Umfang und Anzahl der Umdrehungen",
      partHints: {
        a: { sketch: true, formulas: ["u = π · d"] },
        b: { sketch: false, formulas: ["Umdrehungen = Strecke : u"] },
      },
      plan: ["u = π · d", "Umdrehungen = Strecke : u"],
      solution: "a) u = 3,14 · 0,5 = 1,57 m. b) Umdrehungen = 1000 : 1,57 ≈ 636,94 → rund 637 Umdrehungen.",
      result: "u = 1,57 m; rund 637 Umdrehungen",
    },
    {
      id: "7",
      group: "Sachaufgabe",
      title: "Wege der Uhrzeiger",
      text: "Eine Turmuhr hat einen Minutenzeiger der Länge 3 m und einen Stundenzeiger der Länge 2 m. a) Welchen Weg legt die Spitze des Minutenzeigers in 12 Stunden zurück? b) Welchen Weg legt die Spitze des Stundenzeigers in 12 Stunden zurück? Rechne mit π = 3,14.",
      given: ["Minutenzeiger 3 m", "Stundenzeiger 2 m", "Zeit 12 Stunden", "π = 3,14"],
      searched: "Wege der Zeigerspitzen",
      partHints: {
        a: { sketch: true, formulas: ["u = 2 · π · r", "Weg = 12 · u"] },
        b: { sketch: false, formulas: ["u = 2 · π · r", "Weg = 1 · u"] },
      },
      plan: ["u = 2 · π · r", "Minutenzeiger: 12 Umläufe in 12 h", "Stundenzeiger: 1 Umlauf in 12 h", "Weg = Anzahl Umläufe · u"],
      solution: "a) u = 2 · 3,14 · 3 = 18,84 m; 12 Umläufe: Weg = 12 · 18,84 = 226,08 m. b) u = 2 · 3,14 · 2 = 12,56 m; 1 Umlauf: Weg = 12,56 m.",
      result: "Minutenzeiger: 226,08 m; Stundenzeiger: 12,56 m",
    },
    {
      id: "8",
      group: "Zusammengesetzt",
      title: "Kreisring",
      text: "Ein Kreisring hat den äußeren Radius R = 8 cm und den inneren Radius r = 5 cm. Berechne den Flächeninhalt des Rings. Rechne mit π = 3,14.",
      given: ["äußerer Radius R = 8 cm", "innerer Radius r = 5 cm", "π = 3,14"],
      searched: "Flächeninhalt des Kreisrings",
      figure: "Großer Kreis (R) mit ausgeschnittenem kleinem Kreis (r) in der Mitte.",
      figureSvg: `<svg viewBox="0 0 220 220" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Kreisring">
  <circle cx="110" cy="110" r="85" fill="rgba(20,184,166,.18)" stroke="#0f766e" stroke-width="2"/>
  <circle cx="110" cy="110" r="53" fill="#ffffff" stroke="#0f766e" stroke-width="2"/>
  <line x1="110" y1="110" x2="195" y2="110" stroke="#0f766e" stroke-width="1.6"/>
  <line x1="110" y1="110" x2="110" y2="57" stroke="#9a3412" stroke-width="1.6"/>
  <circle cx="110" cy="110" r="2.5" fill="#0f766e"/>
  <text x="150" y="103">R = 8 cm</text>
  <text x="80" y="86">r = 5 cm</text>
</svg>`,
      plan: ["A = π · R² − π · r²", "A = π · (R² − r²)"],
      solution: "A = 3,14 · (8² − 5²) = 3,14 · (64 − 25) = 3,14 · 39 = 122,46 cm².",
      result: "A = 122,46 cm²",
    },
    {
      id: "9",
      group: "Sachaufgabe",
      title: "Ziege am Strick",
      text: "Eine Ziege ist mit einem 5 m langen Strick an einem Pflock festgebunden. a) Welche Fläche kann die Ziege abgrasen? b) Der Strick wird auf 10 m verlängert. Welche Fläche kann sie jetzt abgrasen, und wievielmal so groß ist sie? Rechne mit π = 3,14.",
      given: ["Strick zuerst 5 m", "später 10 m", "π = 3,14"],
      searched: "abgraste Fläche und Vergleich",
      partHints: {
        a: { sketch: true, formulas: ["A = π · r²"] },
        b: { sketch: false, formulas: ["A = π · r²", "Vergleich: A_neu : A_alt"] },
      },
      plan: ["A = π · r² (Kreis)", "der Strick ist der Radius", "Vergleich der beiden Flächen"],
      solution: "a) A = 3,14 · 5² = 3,14 · 25 = 78,5 m². b) A = 3,14 · 10² = 3,14 · 100 = 314 m²; das ist 314 : 78,5 = 4-mal so groß (verdoppelt man den Radius, vervierfacht sich die Fläche).",
      result: "a) A = 78,5 m²; b) A = 314 m² (4-mal so groß)",
    },
  ],
  // Erklärvideos (Lehrer Schmidt) je Aufgabentyp: Umfang, Fläche, Umkehrung, Kreisring.
  videos: {
    "1": [{ id: "eASZX0ocAc8", label: "Kreis: Umfang & Fläche" }],
    "2": [{ id: "k9Mpm-PG-Y8", label: "Kreis: Umfang" }],
    "3": [{ id: "8PqMj4L0BsE", label: "Kreis: Fläche" }],
    "4": [{ id: "k9Mpm-PG-Y8", label: "Kreis: Umfang" }],
    "5": [{ id: "suzwj9mYEJg", label: "Radius aus Fläche" }, { id: "8PqMj4L0BsE", label: "Kreis: Fläche" }],
    "6": [{ id: "k9Mpm-PG-Y8", label: "Kreis: Umfang" }],
    "7": [{ id: "k9Mpm-PG-Y8", label: "Kreis: Umfang" }],
    "8": [{ id: "Foio7fElCOE", label: "Kreisring" }, { id: "8PqMj4L0BsE", label: "Kreis: Fläche" }],
    "9": [{ id: "8PqMj4L0BsE", label: "Kreis: Fläche" }],
  },
  // Nur die Grundformel als Tipp (nicht schon umgestellt).
  baseFormulas: {
    "1": ["d = 2 · r", "u = 2 · π · r", "A = π · r²"],
    "2": ["u = 2 · π · r"],
    "3": ["A = π · r²"],
    "4": ["u = 2 · π · r"],
    "5": ["A = π · r²"],
    "8": ["A = π · R² − π · r²"],
  },
  // Schritt für Schritt: Werte einsetzen, dann nach der gesuchten Größe umstellen.
  rearrange: {
    "1": ["Beispiel c) u gegeben, r gesucht", "u = 2 · π · r", "31,4 = 2 · 3,14 · r", "31,4 = 6,28 · r", "| : 6,28:  r = 31,4 : 6,28"],
    "4": ["u = 2 · π · r", "18,84 = 2 · 3,14 · r", "18,84 = 6,28 · r", "| : 6,28:  r = 18,84 : 6,28"],
    "5": ["A = π · r²", "50,24 = 3,14 · r²", "| : 3,14:  r² = 50,24 : 3,14", "r² = 16", "r = √16"],
  },
};
