window.GEO_QUALI = {
  levelLabel: "Vielecke",
  themeLine: "Thema: Regelmäßige Vielecke (Winkel, Umfang, Flächeninhalt, Bestimmungsdreieck), Mathematik 9.",
  tasks: [
    {
      id: "1",
      group: "Winkel",
      title: "Winkel im Vieleck",
      text: "Berechne für die regelmäßigen Vielecke den Mittelpunktswinkel β, den Basiswinkel α und den Innenwinkel.",
      table: {
        cols: ["a", "b", "c", "d"],
        rows: [
          { label: "n", cells: ["5", "6", "8", "12"] },
          { label: "β", cells: ["", "", "", ""] },
          { label: "α", cells: ["", "", "", ""] },
          { label: "Innenw.", cells: ["", "", "", ""] },
        ],
      },
      given: ["a) n = 5", "b) n = 6", "c) n = 8", "d) n = 12"],
      searched: "Mittelpunktswinkel β, Basiswinkel α und Innenwinkel",
      noSketch: true,
      plan: ["β = 360° : n", "α = (180° − β) : 2", "Innenwinkel = 2 · α"],
      solution: "a) n = 5: β = 72°, α = 54°, Innenwinkel = 108°. b) n = 6: β = 60°, α = 60°, Innenwinkel = 120°. c) n = 8: β = 45°, α = 67,5°, Innenwinkel = 135°. d) n = 12: β = 30°, α = 75°, Innenwinkel = 150°.",
      result: "a) 72°/54°/108°; b) 60°/60°/120°; c) 45°/67,5°/135°; d) 30°/75°/150°",
    },
    {
      id: "2",
      group: "Winkel",
      title: "Winkel im Neuneck",
      text: "Berechne für ein regelmäßiges Neuneck den Mittelpunktswinkel β und den Basiswinkel α des Bestimmungsdreiecks.",
      given: ["regelmäßiges Neuneck (n = 9)"],
      searched: "Mittelpunktswinkel β und Basiswinkel α",
      figure: "Bestimmungsdreieck: gleichschenklig, Spitzenwinkel β am Mittelpunkt, zwei Basiswinkel α.",
      plan: ["β = 360° : n", "α = (180° − β) : 2"],
      solution: "β = 360° : 9 = 40°; α = (180° − 40°) : 2 = 140° : 2 = 70°.",
      result: "β = 40°; α = 70°",
    },
    {
      id: "3",
      group: "Grundlagen",
      title: "Umfang eines Sechsecks",
      text: "Ein regelmäßiges Sechseck hat die Seitenlänge s = 5 cm. Berechne den Umfang.",
      given: ["regelmäßiges Sechseck (n = 6)", "s = 5 cm"],
      searched: "Umfang u",
      plan: ["u = n · s"],
      solution: "u = 6 · 5 = 30 cm.",
      result: "u = 30 cm",
    },
    {
      id: "4",
      group: "Fläche",
      title: "Fläche eines Achtecks",
      text: "Ein regelmäßiges Achteck hat die Seitenlänge s = 4 cm. Die Höhe des Bestimmungsdreiecks beträgt h = 4,8 cm. Berechne den Umfang und den Flächeninhalt.",
      given: ["regelmäßiges Achteck (n = 8)", "s = 4 cm", "Bestimmungsdreieck h = 4,8 cm"],
      searched: "Umfang u und Flächeninhalt A",
      figure: "Das Achteck besteht aus 8 gleichen Bestimmungsdreiecken mit Grundseite s und Höhe h.",
      plan: ["u = n · s", "A_Bestimmungsdreieck = (s · h)/2", "A = n · A_Bestimmungsdreieck"],
      solution: "u = 8 · 4 = 32 cm; A_BD = (4 · 4,8)/2 = 9,6 cm²; A = 8 · 9,6 = 76,8 cm².",
      result: "u = 32 cm; A = 76,8 cm²",
    },
    {
      id: "5",
      group: "Pythagoras",
      title: "Bestimmungsdreieck im Neuneck",
      text: "Ein regelmäßiges Neuneck hat den Umkreisradius r = 7,4 cm und die Seitenlänge s = 5 cm. a) Berechne mit dem Satz des Pythagoras die Höhe h des Bestimmungsdreiecks. b) Berechne den Umfang und den Flächeninhalt des Neunecks. Runde auf zwei Dezimalstellen.",
      given: ["regelmäßiges Neuneck (n = 9)", "r = 7,4 cm", "s = 5 cm"],
      searched: "Höhe h, Umfang u und Flächeninhalt A",
      partHints: {
        a: {
          sketch: true,
          formulas: ["(s/2)² + h² = r²"],
          rearrange: ["(s/2)² + h² = r²", "2,5² + h² = 7,4²", "6,25 + h² = 54,76", "| − 6,25:  h² = 48,51", "h = √48,51"],
        },
        b: { sketch: false, formulas: ["u = n · s", "A = n · (s · h)/2"] },
      },
      plan: ["h = √(r² − (s/2)²)", "u = n · s", "A = n · (s · h)/2"],
      solution: "a) h = √(7,4² − 2,5²) = √(54,76 − 6,25) = √48,51 ≈ 6,96 cm. b) u = 9 · 5 = 45 cm; A_BD = (5 · 6,96)/2 = 17,4 cm²; A = 9 · 17,4 = 156,6 cm².",
      result: "h ≈ 6,96 cm; u = 45 cm; A = 156,6 cm²",
    },
    {
      id: "6",
      group: "Sachaufgabe",
      title: "Achteckiges Werbeplakat",
      text: "Ein achteckiges Werbeplakat hat den Umfang u = 16 m und den Flächeninhalt A = 19,2 m². a) Berechne die Seitenlänge s. b) Berechne die Höhe h des Bestimmungsdreiecks.",
      given: ["regelmäßiges Achteck (n = 8)", "u = 16 m", "A = 19,2 m²"],
      searched: "Seitenlänge s und Höhe h des Bestimmungsdreiecks",
      partHints: {
        a: {
          sketch: false,
          formulas: ["u = n · s"],
          rearrange: ["u = n · s", "16 = 8 · s", "| : 8:  s = 16 : 8"],
        },
        b: {
          sketch: true,
          formulas: ["A = n · (s · h)/2"],
          rearrange: ["A = n · (s · h)/2", "19,2 = 8 · (2 · h)/2", "19,2 = 8 · h", "| : 8:  h = 19,2 : 8"],
        },
      },
      plan: ["s = u : n", "A = n · (s · h)/2", "h = 2 · A : (n · s)"],
      solution: "a) s = 16 : 8 = 2 m. b) h = 2 · 19,2 : (8 · 2) = 38,4 : 16 = 2,4 m.",
      result: "s = 2 m; h = 2,4 m",
    },
    {
      id: "7",
      group: "Sachaufgabe",
      title: "Fünfeckiger Springbrunnen",
      text: "Das Becken eines Springbrunnens hat die Form eines regelmäßigen Fünfecks. Der Umfang beträgt u = 20 m, die Beckenfläche A = 27,5 m². a) Berechne die Seitenlänge s. b) Berechne die Höhe h des Bestimmungsdreiecks.",
      given: ["regelmäßiges Fünfeck (n = 5)", "u = 20 m", "A = 27,5 m²"],
      searched: "Seitenlänge s und Höhe h des Bestimmungsdreiecks",
      partHints: {
        a: {
          sketch: false,
          formulas: ["u = n · s"],
          rearrange: ["u = n · s", "20 = 5 · s", "| : 5:  s = 20 : 5"],
        },
        b: {
          sketch: true,
          formulas: ["A = n · (s · h)/2"],
          rearrange: ["A = n · (s · h)/2", "27,5 = 5 · (4 · h)/2", "27,5 = 10 · h", "| : 10:  h = 27,5 : 10"],
        },
      },
      plan: ["s = u : n", "A = n · (s · h)/2", "h = 2 · A : (n · s)"],
      solution: "a) s = 20 : 5 = 4 m. b) h = 2 · 27,5 : (5 · 4) = 55 : 20 = 2,75 m.",
      result: "s = 4 m; h = 2,75 m",
    },
    {
      id: "8",
      group: "Quali-Aufgabe",
      title: "Achteck und Rechteck",
      text: "Ein regelmäßiges Achteck hat die Seitenlänge 4 cm. a) Berechne den Umfang des Achtecks. b) Ein Rechteck hat den gleichen Umfang wie das Achteck. Gib eine mögliche Länge und Breite eines solchen Rechtecks an.",
      given: ["regelmäßiges Achteck (n = 8)", "s = 4 cm"],
      searched: "Umfang und passendes Rechteck",
      partHints: {
        a: { sketch: false, formulas: ["u = n · s"] },
        b: {
          sketch: false,
          formulas: ["2 · (l + b) = u"],
          rearrange: ["2 · (l + b) = u", "2 · (l + b) = 32", "| : 2:  l + b = 32 : 2", "l + b = 16  →  z. B. l = 10, b = 6"],
        },
      },
      plan: ["u = n · s", "Rechteck: 2 · (l + b) = u", "also l + b = u : 2"],
      solution: "a) u = 8 · 4 = 32 cm. b) Rechteck mit gleichem Umfang: 2 · (l + b) = 32, also l + b = 16 cm. Eine Möglichkeit: l = 10 cm und b = 6 cm (denn 10 + 6 = 16).",
      result: "u = 32 cm; z. B. Rechteck 10 cm × 6 cm",
    },
  ],
  // Erklärvideos (Lehrer Schmidt) je Aufgabentyp: Winkel, Vieleck-Grundlagen, Pythagoras.
  videos: {
    "1": [{ id: "POY5kY81v0w", label: "Winkel an Vielecken" }],
    "2": [{ id: "POY5kY81v0w", label: "Winkel an Vielecken" }],
    "3": [{ id: "GJX05j4iwog", label: "Regelmäßige Vielecke" }],
    "4": [{ id: "GJX05j4iwog", label: "Regelmäßige Vielecke" }],
    "5": [{ id: "GJX05j4iwog", label: "Regelmäßige Vielecke" }, { id: "FECtVbC-mgk", label: "Satz des Pythagoras" }],
    "6": [{ id: "GJX05j4iwog", label: "Regelmäßige Vielecke" }],
    "7": [{ id: "GJX05j4iwog", label: "Regelmäßige Vielecke" }],
    "8": [{ id: "GJX05j4iwog", label: "Regelmäßige Vielecke" }, { id: "aWWf6E9-jmQ", label: "Rechteck: Umfang & Fläche" }],
  },
};
