/* Lernkarten zum Modul „Genussmittel, Drogen und Abhängigkeit“ (NT 8). Kennungen k1 … nie neu vergeben – daran hängt der Lernstand. */
NT8Karten.satz("sucht", [
  { id: "k1", art: "begriff", v: "Welche vier Stufen führen vom Genuss zur Abhängigkeit?", h: "Genuss – Gewohnheit – Missbrauch – Abhängigkeit. Bei der Abhängigkeit gelingt das Aufhören nicht mehr." },
  { id: "k2", art: "bild", v: "Welche Stufe fehlt in der Suchtspirale: Gutes Gefühl – Wiederholen – ? – Kontrollverlust",
    bild: '<svg viewBox="0 0 200 120" xmlns="http://www.w3.org/2000/svg"><g fill="#eef3f6" stroke="#2f7f8f" stroke-width="2"><rect x="10" y="10" width="70" height="30" rx="6"/><rect x="120" y="10" width="70" height="30" rx="6"/><rect x="120" y="80" width="70" height="30" rx="6"/><rect x="10" y="80" width="70" height="30" rx="6" fill="#f8d7a6"/></g><g fill="none" stroke="#c0392b" stroke-width="2.5"><path d="M80 25 H116"/><path d="M155 40 V76"/><path d="M120 95 H84"/><path d="M45 80 V44"/></g><g font-size="11" font-weight="700" fill="#15212b" text-anchor="middle"><text x="45" y="29">Gutes Gefühl</text><text x="155" y="29">Wiederholen</text><text x="155" y="99">?</text><text x="45" y="99">Kontrollv.</text></g></svg>',
    h: "Die Gewöhnung: Der Körper und das Gehirn passen sich an, man braucht immer mehr für dieselbe Wirkung." },
  { id: "k3", art: "vergleich", v: "Körperliche und psychische Abhängigkeit: Woran erkennt man den Unterschied?", h: "Körperlich: Der Körper reagiert auf das Weglassen, zum Beispiel mit Zittern oder Schwitzen. Psychisch: starkes Verlangen im Kopf, Gereiztheit, Unruhe." },
  { id: "k4", art: "vergleich", v: "Stoffgebundene und stoffungebundene Sucht: Nenne je ein Beispiel.", h: "Stoffgebunden: zum Beispiel Alkohol oder Nikotin. Stoffungebunden: zum Beispiel Glücksspiel, Computerspiele oder Kaufen." },
  { id: "k5", art: "ursache", v: "Warum ist „Einmal schadet doch nicht“ ein riskanter Satz?", h: "Aus einmal kann Gewohnheit werden. Manche Stoffe, zum Beispiel Nikotin, machen auch schnell abhängig." },
  { id: "k6", art: "versuch", v: "Du schiebst im Reaktionsweg-Versuch die Reaktionszeit von 1 s auf 2 s. Was passiert mit dem Weg?", h: "Er verdoppelt sich: Bei 50 km/h sind es etwa 14 m je Sekunde Reaktionszeit." },
  { id: "k7", art: "anwendung", v: "Warum ist Alkohol im Straßenverkehr so gefährlich?", h: "Er verlängert die Reaktionszeit und verschlechtert das Urteilsvermögen. Der Reaktionsweg wird länger, das Auto steht zu spät." },
  { id: "k8", art: "anwendung", v: "Jemand ist nach einer Feier nicht ansprechbar. Was tust du?", h: "Notruf 112 wählen, in die stabile Seitenlage bringen und bei der Person bleiben, bis Hilfe kommt." },
  { id: "k9", art: "begriff", v: "Welche drei Stoffe stecken im Tabakrauch?", h: "Nikotin macht abhängig, Teer setzt sich in der Lunge ab, Kohlenmonoxid verdrängt Sauerstoff im Blut." },
  { id: "k10", art: "fehler", v: "Finde den Fehler: „Vapes sind harmlos, da ist nur Wasserdampf drin.“", h: "Falsch. Vapes enthalten meist Nikotin und machen abhängig. Der Dampf enthält mehr als Wasser." },
  { id: "k16", art: "begriff", v: "Welche drei Essstörungen gibt es, und woran merkt das Umfeld, dass jemand Hilfe braucht?", h: "Magersucht, Bulimie, Binge-Eating. Anzeichen: Gedanken nur um Essen und Figur, gemeinsames Essen wird gemieden, Rückzug." },
  { id: "k17", art: "begriff", v: "Wie lautet der Weg aus der Sucht in vier Schritten?", h: "Beratung – Entgiftung – Entwöhnung – Nachsorge. Bei einem Rückfall holt man sich wieder Hilfe." },
  { id: "k18", art: "fehler", v: "Finde den Fehler: „Alkohol und Nikotin sind erlaubt, also können sie nicht süchtig machen.“", h: "Falsch. Auch legale Suchtmittel machen abhängig und krank. Bier und Wein erst ab 16, Schnaps, Tabak und E-Zigaretten erst ab 18.", m: true },
  { id: "k19", art: "ursache", v: "Warum ist Passivrauchen gefährlich, besonders für Kinder?", h: "Wer fremden Rauch einatmet, nimmt dieselben Schadstoffe auf wie Raucher. Kinder sind besonders gefährdet.", m: true },
  { id: "k11", art: "transfer", v: "Ben verbringt jeden Abend Stunden am PC, wird bei Verboten wütend und trifft keine Freunde mehr. Was ist das?", h: "Warnzeichen für schädliche Mediennutzung. Er sollte mit einer Vertrauensperson sprechen." },
  { id: "k12", art: "transfer", v: "Nenne zwei Wege, mit Stress oder Langeweile umzugehen, ohne ein Suchtmittel zu nutzen.", h: "Zum Beispiel Sport, Freunde treffen, Musik, ein Hobby oder mit jemandem reden." },
  { id: "k13", art: "begriff", v: "Wo bekommt man Hilfe? Nenne drei Anlaufstellen.", h: "Vertrauenslehrkraft, Jugendsozialarbeit an der Schule, Eltern, Suchtberatungsstelle, „Nummer gegen Kummer“ (116 111)." },
  { id: "k14", art: "transfer", v: "Eine Werbung sagt: „Null Risiko!“ Wie prüfst du diese Aussage?", h: "Frage: Was ist wirklich drin, wer sagt das und was will er verkaufen? Aussagen ohne Belege kritisch sehen.", m: true },
  { id: "k15", art: "ursache", v: "Eine Packung kostet angenommen 8 €. Warum steigen die Kosten für Rauchen so stark?", h: "Kosten wachsen mit der Zeit gleichmäßig: 365 Packungen im Jahr sind 2 920 €, in zehn Jahren 29 200 €.", m: true }
]);
