/* Deutsch 8 · Lesen, Sachtexte und Medien · Modul 1 (M8): Sachtext über Dachbegrünung und Stadtklima – eigener Text.
   Eigene Fassung für M8 (dichter, mit Fachbegriffen und einer kritischen Einordnung der Wirkung), nicht die R8-Fassung mit Zusätzen.
   Aufbau: Problem – Ursachen – Wirkung – Aufbau des Dachs – zwei Formen – weitere Vorzüge – Grenzen – Folgerung (8 Abschnitte). */
D7Texte.add({
  id: "les-daecher-m", titel: "Grüne Dächer gegen heiße Städte", textsorte: "Sachtext", zug: "M8",
  modul: "Lesen, Sachtexte und Medien", unterthema: "Lesestrategie, Abschnitte, Hauptaussagen, Textaufbau", woerter: 706,
  schwierigkeit: "anspruchsvoll", lehrplan: "D8 2.1, 2.3", thema: "Dachbegrünung und Stadtklima",
  quelle: "Eigenständig für GRUMI erstellt.", lizenz: "eigener Text", erstellung: "eigener Text für GRUMI",
  zeilennummern: true, probe: false,
  absaetze: [
    "Wenn im Hochsommer die Sonne tagelang auf Asphalt und Beton brennt, verwandeln sich Innenstädte in Backöfen. Selbst nach Sonnenuntergang bringt die Nacht kaum Abkühlung. Was für Jugendliche vor allem lästig ist, bedeutet für ältere und kranke Menschen eine ernste Gefahr für die Gesundheit. Weil Hitzewellen mit dem Klimawandel häufiger werden und länger andauern, müssen Städte sich anpassen. Stadtplaner richten ihren Blick dabei zunehmend nach oben – auf Flächen, die bisher kaum jemand beachtet hat: die Dächer.",
    "Dass es in der Stadt wärmer ist als im Umland, hat mehrere Ursachen. Asphalt, Beton und Ziegel nehmen tagsüber große Mengen Sonnenenergie auf und geben sie nachts nur langsam wieder ab. Dicht stehende Gebäude bremsen den Wind, der frische Luft heranführen könnte. Hinzu kommt die Abwärme von Motoren, Klimaanlagen und Maschinen. Vor allem aber fehlt es an Pflanzen und offenen Böden: Wo der Boden versiegelt, also mit Asphalt oder Pflaster bedeckt ist, kann kein Wasser verdunsten. Fachleute bezeichnen diese Erscheinung als städtische Wärmeinsel. In windstillen Sommernächten liegt die Temperatur im Zentrum einer Großstadt oft um mehrere Grad über der des Umlands.",
    "Genau hier setzt die Dachbegrünung an. Pflanzen und Substrat – so heißt die spezielle Erdmischung auf dem Dach – speichern Regenwasser und geben es nach und nach an die Luft ab. Für das Verdunsten wird Energie benötigt, die der Umgebung als Wärme entzogen wird; man spricht von Verdunstungskälte. Der Unterschied ist messbar: Während sich ein dunkles, unbegrüntes Flachdach an einem heißen Tag auf weit über 60 Grad aufheizen kann, bleibt die Oberfläche eines Gründachs deutlich kühler. Davon profitiert zunächst das Gebäude selbst, denn die Räume unter dem Dach heizen sich weniger auf. Im Winter wirkt die Pflanzenschicht umgekehrt wie eine zusätzliche Decke, die etwas Heizwärme im Haus hält.",
    "Ein Gründach ist allerdings mehr als ein Beet in luftiger Höhe. Es besteht aus mehreren Schichten, von denen jede eine eigene Aufgabe erfüllt. Zuunterst schützt eine Wurzelschutzfolie die Dachabdichtung davor, von Wurzeln durchbohrt zu werden. Darauf liegt die Dränschicht, die einen Teil des Wassers speichert und den Überschuss zum Abfluss leitet. Ein Filtervlies verhindert, dass feine Erdteilchen in diese Schicht gespült werden und sie verstopfen. Erst darüber folgt das Substrat, ein lockeres Gemisch aus mineralischen Bestandteilen, das leichter ist als Gartenerde und Wasser dennoch gut hält. Es bildet die Grundlage für die Pflanzen.",
    "Je nach Dicke des Substrats unterscheidet man zwei Formen. Bei der extensiven Begrünung genügt eine Schicht von etwa zehn Zentimetern. Darauf gedeihen anspruchslose Arten wie Moose, Kräuter und Mauerpfeffer, die Trockenheit überstehen und mit ein bis zwei Kontrollen im Jahr auskommen. Die intensive Begrünung dagegen gleicht einem Garten: In einer deutlich dickeren Substratschicht wurzeln Stauden, Sträucher und sogar kleine Bäume. Ein solcher Dachgarten lässt sich als Aufenthaltsort nutzen, verlangt aber regelmäßige Pflege und Bewässerung – und ein Gebäude, das die erhebliche Last tragen kann.",
    "Neben der Kühlung hat ein begrüntes Dach weitere Vorzüge. Bei Starkregen hält es einen großen Teil des Wassers zurück und gibt es verzögert ab; dadurch wird die Kanalisation entlastet, und das Risiko überfluteter Straßen und Keller sinkt. Für Wildbienen, Schmetterlinge und manche Vogelarten entstehen mitten in der Stadt Lebensräume, was der Artenvielfalt zugutekommt. Die Pflanzen binden außerdem Staub aus der Luft. Nicht zuletzt schützt die Begrünung die Dachabdichtung vor UV-Strahlung, Hagel und starken Temperaturschwankungen, sodass sie deutlich länger hält als auf einem ungeschützten Dach.",
    "Ein Allheilmittel ist die Dachbegrünung jedoch nicht. In der Anschaffung ist sie teurer als ein herkömmliches Dach, und nicht jedes Gebäude ist geeignet: Mit Wasser vollgesogenes Substrat wiegt viel, weshalb bei bestehenden Häusern zuerst die Tragfähigkeit geprüft werden muss. Auf steilen Dächern lässt sich eine Begrünung nur mit großem Aufwand anbringen. Auch die Wirkung hat Grenzen. Trocknet das Substrat in langen Hitzeperioden aus, verdunstet kaum noch Wasser, und die Kühlung lässt nach. Zudem kühlt ein Gründach vor allem das Gebäude und die Luft in Dachhöhe; unten auf der Straße kommt davon nur wenig an.",
    "Fachleute empfehlen deshalb, Gründächer mit anderen Maßnahmen zu verbinden: mit Bäumen, die Schatten spenden, mit begrünten Fassaden, Parks und Flächen, auf denen Regenwasser versickern kann. Viele Städte fördern Dachbegrünungen inzwischen mit Zuschüssen oder schreiben sie für neue Gebäude mit Flachdach vor. Sogar mit Solaranlagen lassen sie sich kombinieren. Ein einzelnes grünes Dach verändert das Stadtklima kaum. Tausende zusammen können jedoch dazu beitragen, dass Städte auch in heißen Sommern lebenswert bleiben."
  ]
});
