/* Deutsch 8 · Lesen, Sachtexte und Medien · Modul 1 (R8): Sachtext über Dachbegrünung und Stadtklima – eigener Text.
   Aufbau: Problem – Ursachen – Lösung – Aufbau des Dachs – zwei Arten – weitere Vorteile – Grenzen – Ausblick (8 Abschnitte). */
D7Texte.add({
  id: "les-daecher-r", titel: "Grüne Dächer gegen heiße Städte", textsorte: "Sachtext", zug: "R8",
  modul: "Lesen, Sachtexte und Medien", unterthema: "Lesestrategie, Abschnitte, Hauptaussagen, Textaufbau", woerter: 580,
  schwierigkeit: "mittel", lehrplan: "D8 2.1, 2.3", thema: "Dachbegrünung und Stadtklima",
  quelle: "Eigenständig für GRUMI erstellt.", lizenz: "eigener Text", erstellung: "eigener Text für GRUMI",
  zeilennummern: true, probe: false,
  absaetze: [
    "Im Sommer wird es in der Innenstadt oft unerträglich heiß. Auch nachts kühlt die Luft dort kaum ab. Viele Menschen schlafen dann schlecht, und für alte und kranke Menschen kann die Hitze sogar gefährlich werden. Fachleute rechnen damit, dass es durch den Klimawandel in Zukunft noch mehr heiße Tage geben wird. Deshalb suchen Städte nach Wegen, sich abzukühlen. Eine Idee liegt ganz oben: auf den Dächern.",
    "Warum ist es in der Stadt wärmer als auf dem Land? Straßen, Plätze und Hauswände bestehen aus Asphalt, Beton und Stein. Diese Stoffe nehmen tagsüber die Wärme der Sonne auf und speichern sie. In der Nacht geben sie die Wärme langsam wieder ab. Außerdem stehen die Häuser dicht nebeneinander, sodass der Wind kaum hindurchwehen kann. Bäume und Wiesen, die kühlen könnten, gibt es nur wenige. So entsteht eine Wärmeinsel: Die Stadt ist in Sommernächten oft mehrere Grad wärmer als ihre Umgebung.",
    "Ein begrüntes Dach, auch Gründach genannt, wirkt wie eine natürliche Klimaanlage. Die Pflanzen und die Erde speichern Regenwasser. Wenn die Sonne scheint, verdunstet dieses Wasser: Es wird zu Wasserdampf und steigt auf. Dabei wird der Umgebung Wärme entzogen, und die Luft über dem Dach kühlt ab. Ein dunkles Flachdach kann sich an einem Sommertag auf über 60 Grad aufheizen. Ein Gründach bleibt deutlich kühler. Das spüren auch die Bewohner, denn in den Räumen direkt unter dem Dach wird es weniger heiß.",
    "Man kann aber nicht einfach Erde auf ein Dach schütten. Ein Gründach besteht aus mehreren Schichten. Ganz unten liegt eine feste Folie. Sie verhindert, dass Wurzeln in das Dach wachsen und es beschädigen. Darüber kommt eine Schicht, die Wasser speichert und überschüssiges Wasser ableitet. Ein Vlies, also ein dünner Stoff, hält die Erde zurück, damit sie nicht weggeschwemmt wird. Erst dann folgt die Erdschicht, die Fachleute Substrat nennen. Sie ist leichter als normale Gartenerde. Ganz oben wachsen die Pflanzen.",
    "Es gibt zwei Arten von Gründächern. Bei der einfachen Art ist die Erdschicht nur etwa zehn Zentimeter dick. Hier wachsen genügsame Pflanzen wie Moose, Kräuter und der Mauerpfeffer. Sie brauchen wenig Wasser und kaum Pflege. Fachleute sprechen von extensiver Begrünung. Bei der aufwendigen Art, der intensiven Begrünung, ist die Erdschicht viel dicker. Dann können auf dem Dach sogar Sträucher und kleine Bäume wachsen, fast wie in einem Garten. So ein Dachgarten ist aber schwer und teuer, und jemand muss ihn regelmäßig gießen und pflegen.",
    "Gründächer kühlen nicht nur. Bei einem starken Gewitter fließt von einem gewöhnlichen Dach das ganze Wasser sofort in die Kanalisation. Sie kann dann überlaufen, und Straßen und Keller werden überschwemmt. Ein Gründach saugt einen großen Teil des Regens auf wie ein Schwamm und gibt ihn erst nach und nach wieder ab. Außerdem finden Wildbienen, Schmetterlinge und Vögel auf den Dächern Nahrung und Platz zum Leben. Und noch etwas: Unter den Pflanzen ist das Dach vor Sonne, Hagel und Frost geschützt. Deshalb hält es länger als ein Dach ohne Begrünung.",
    "Trotzdem hat nicht jedes Haus ein grünes Dach. Der Bau kostet mehr als bei einem gewöhnlichen Dach. Vor allem aber muss das Dach das Gewicht tragen können, denn nasse Erde ist schwer. Bei älteren Gebäuden müssen das zuerst Fachleute prüfen. Am besten eignen sich flache oder nur leicht geneigte Dächer, zum Beispiel auf Garagen, Schulen oder Supermärkten.",
    "Viele Städte unterstützen den Bau inzwischen mit Geld oder schreiben für Neubauten mit Flachdach eine Begrünung vor. Ein einzelnes Gründach kühlt allerdings keine ganze Stadt. Doch wenn viele Dächer grün werden und Bäume und Parks dazukommen, wird der Sommer in der Stadt erträglicher."
  ]
});
