/* Deutsch 8 · Lesen, Sachtexte und Medien · Modul 2 (R8): Sachtext über Lärm und Gesundheit – eigener Text.
   7 Abschnitte: Einstieg – Was ist Lärm? (Dezibel) – Gehör – Stress und Schlaf – Lernen – Lärmquellen – Schutz. */
D7Texte.add({
  id: "les-laerm-r", titel: "Lärm – die unterschätzte Belastung", textsorte: "Sachtext", zug: "R8",
  modul: "Lesen, Sachtexte und Medien", unterthema: "Aussagen belegen, zitieren, sinngemäß wiedergeben", woerter: 489,
  schwierigkeit: "mittel", lehrplan: "D8 2.1, 2.3, 3.1", thema: "Lärm und Gesundheit",
  quelle: "Eigenständig für GRUMI erstellt.", lizenz: "eigener Text", erstellung: "eigener Text für GRUMI",
  zeilennummern: true, probe: false,
  absaetze: [
    "Ein Moped knattert vorbei, im Nachbarhaus dröhnt ein Bohrer, und irgendwo läuft laute Musik. Viele Menschen haben sich an solche Geräusche gewöhnt. Sie halten Lärm für lästig, aber harmlos. Das ist ein Irrtum: Lärm kann krank machen. Fachleute nennen ihn deshalb eine unterschätzte Belastung.",
    "Aber was ist Lärm eigentlich? Lärm ist jeder Schall, der stört oder der Gesundheit schadet. Wie laut ein Geräusch ist, wird in Dezibel gemessen, abgekürzt dB. Flüstern erreicht etwa 30 Dezibel, ein normales Gespräch etwa 60. An einer stark befahrenen Straße sind es rund 80 Dezibel, und ein Presslufthammer bringt es auf ungefähr 100. Wichtig ist dabei: Zehn Dezibel mehr empfinden wir schon als doppelt so laut.",
    "Sehr lauter Schall schädigt das Gehör. Im Innenohr sitzen winzige Haarzellen. Sie wandeln den Schall in Signale um, die das Gehirn versteht. Bei großer Lautstärke werden diese Zellen überlastet. Nach einem lauten Konzert hört man deshalb oft alles dumpf, oder es pfeift im Ohr. Meistens erholt sich das Gehör nach einigen Stunden wieder. Wer seine Ohren aber immer wieder überfordert, verliert Haarzellen für immer, denn sie wachsen beim Menschen nicht nach. Als gefährlich gilt Dauerlärm ab etwa 85 Dezibel. Laute Musik über Kopfhörer kann diesen Wert deutlich überschreiten.",
    "Lärm schadet jedoch nicht nur den Ohren. Schon viel leisere Geräusche setzen den Körper unter Stress, wenn sie lange andauern. Er schüttet dann Stresshormone aus. Das Herz schlägt schneller, und der Blutdruck steigt. Das geschieht sogar im Schlaf, denn die Ohren lassen sich nicht schließen wie die Augen. Wer an einer lauten Straße wohnt, schläft deshalb oft unruhig, auch wenn er nachts gar nicht aufwacht. Auf Dauer steigt bei diesen Menschen das Risiko für Krankheiten von Herz und Kreislauf.",
    "Auch das Lernen leidet. Bei Lärm fällt es schwer, sich zu konzentrieren, und man macht mehr Fehler. Untersuchungen an Grundschulen in der Nähe großer Flughäfen deuten darauf hin, dass Kinder dort langsamer lesen lernen als Kinder in ruhigen Gegenden. In vielen Klassenzimmern ist es ebenfalls zu laut: Wenn Stühle rücken und alle durcheinanderreden, müssen Lehrkräfte und Schüler immer lauter sprechen, um sich zu verstehen. Das strengt alle an.",
    "Die wichtigste Lärmquelle in Deutschland ist der Straßenverkehr. In Umfragen sagt ein großer Teil der Menschen, dass sie sich zu Hause von Autos, Lastwagen und Motorrädern gestört fühlen. Ob ein Geräusch als Lärm empfunden wird, hängt allerdings nicht nur von der Lautstärke ab. Die eigene Lieblingsmusik stört kaum jemanden, die Musik des Nachbarn dagegen sehr. Dem Gehör ist dieser Unterschied aber gleichgültig: Zu laute Musik schadet ihm, auch wenn sie uns gefällt.",
    "Gegen Lärm kann man etwas tun. Städte bauen Lärmschutzwände, verlegen leiseren Asphalt oder führen Tempo 30 ein. Auch jeder Einzelne kann sein Gehör schützen. Bei Konzerten helfen Ohrstöpsel und ein Platz mit Abstand zu den Lautsprechern. Für Kopfhörer gilt eine Faustregel: höchstens 60 Prozent der möglichen Lautstärke und nach einer Stunde eine Pause. Vor allem aber brauchen die Ohren regelmäßig Ruhe. Stille ist für den Körper keine verlorene Zeit, sondern Erholung."
  ]
});
