/* Deutsch 8 · Lesen, Sachtexte und Medien · Modul 2 (M8): Sachtext über Lärm und Gesundheit – eigener Text.
   Eigene Fassung für M8 (dichter, abstrakter Einstieg, Dezibel-Skala erklärt, Lärmkarten, Einwand gegen Maßnahmen),
   nicht die R8-Fassung mit Zusätzen. 8 Abschnitte: Einstieg – Schall und Lärm – Dezibel – Gehör – Stress und Schlaf –
   Leistung und Lernen – Lärmquellen und Maßnahmen – eigenes Verhalten. */
D7Texte.add({
  id: "les-laerm-m", titel: "Lärm – die unterschätzte Belastung", textsorte: "Sachtext", zug: "M8",
  modul: "Lesen, Sachtexte und Medien", unterthema: "Aussagen belegen, Zitate einbauen und erklären", woerter: 620,
  schwierigkeit: "anspruchsvoll", lehrplan: "D8 2.1, 2.3, 3.1", thema: "Lärm und Gesundheit",
  quelle: "Eigenständig für GRUMI erstellt.", lizenz: "eigener Text", erstellung: "eigener Text für GRUMI",
  zeilennummern: true, probe: false,
  absaetze: [
    "Wer nach den größten Umweltproblemen gefragt wird, denkt an Abgase, Plastikmüll oder verschmutztes Wasser. Lärm fällt den wenigsten ein. Man kann ihn nicht sehen, er hinterlässt keinen Schmutz, und sobald die Quelle verstummt, ist er verschwunden. Gerade deshalb wird er unterschätzt. Dabei zählen Fachleute Lärm heute zu den Umweltbelastungen, die der Gesundheit besonders vieler Menschen schaden.",
    "Physikalisch gesehen ist Lärm nichts anderes als Schall, also Schwingungen der Luft, die unser Ohr auffängt. Zu Lärm wird Schall erst dadurch, dass er stört, belastet oder schädigt. Das macht die Sache kompliziert, denn ob ein Geräusch stört, ist zum Teil subjektiv: Die Musik, die man selbst aufdreht, empfindet man als Genuss, dieselbe Musik aus der Nachbarwohnung als Zumutung. Messen lässt sich deshalb nicht der Lärm selbst, sondern nur die Lautstärke.",
    "Sie wird in Dezibel (dB) angegeben. Die Skala hat eine Besonderheit, die leicht in die Irre führt: Sie steigt nicht gleichmäßig an. Ein Zuwachs von zehn Dezibel wird bereits als Verdoppelung der Lautstärke empfunden. Ein Gespräch mit etwa 60 Dezibel wirkt also doppelt so laut wie ein leises Büro mit 50, eine stark befahrene Straße mit rund 80 Dezibel etwa viermal so laut wie das Gespräch. Ein Presslufthammer erreicht ungefähr 100 Dezibel; bei etwa 120 Dezibel beginnt der Schall zu schmerzen.",
    "Am offensichtlichsten ist die Gefahr für das Gehör. In der Hörschnecke des Innenohrs sitzen mehrere Tausend Haarzellen, die Schallwellen in Nervensignale umwandeln. Werden sie durch große Lautstärke überlastet, hört man zunächst dumpf, oder ein Pfeifen bleibt im Ohr zurück. In der Regel erholen sich die Zellen innerhalb von Stunden. Wiederholt sich die Überlastung jedoch, sterben sie ab – und weil Haarzellen beim Menschen nicht nachwachsen, ist dieser Hörverlust endgültig. Als kritisch gilt eine Dauerbelastung ab etwa 85 Dezibel; an Arbeitsplätzen muss von diesem Wert an ein Gehörschutz getragen werden. Kopfhörer können bei voller Lautstärke deutlich darüber liegen, und dem Gehör ist es gleichgültig, ob uns die Musik gefällt.",
    "Weniger bekannt ist, dass Lärm auch dort schadet, wo das Gehör unversehrt bleibt. Der Körper deutet laute Geräusche als Warnsignal und schüttet Stresshormone aus; Puls und Blutdruck steigen. Diese Reaktion läuft unbewusst ab und lässt sich nicht abstellen – auch nicht im Schlaf, denn das Ohr bleibt immer auf Empfang. Wer an einer Hauptverkehrsstraße oder in einer Einflugschneise wohnt, schläft deshalb weniger tief, selbst wenn er nicht aufwacht und überzeugt ist, sich an den Lärm gewöhnt zu haben. Hält die Belastung über Jahre an, erhöht sich nach heutigem Wissensstand das Risiko für Bluthochdruck und andere Herz-Kreislauf-Erkrankungen.",
    "Auch die geistige Leistungsfähigkeit leidet. Unter Lärm lässt die Konzentration nach, man ermüdet rascher und macht mehr Fehler. Besonders empfindlich reagieren Kinder: Untersuchungen an Grundschulen im Umfeld großer Flughäfen deuten darauf hin, dass dort das Lesenlernen langsamer vorangeht als in ruhigen Wohngebieten. In Klassenzimmern mit starkem Nachhall kommt ein weiterer Effekt hinzu. Je lauter es wird, desto lauter sprechen alle, um verstanden zu werden – und treiben den Pegel damit weiter in die Höhe.",
    "Die bedeutendste Lärmquelle ist hierzulande der Straßenverkehr; in Umfragen gibt ein großer Teil der Bevölkerung an, sich im eigenen Wohnumfeld davon gestört zu fühlen. Größere Städte sind inzwischen verpflichtet, Lärmkarten zu erstellen und Pläne zu entwickeln, wie sich die Belastung verringern lässt. Zu den Mitteln gehören Tempo 30, lärmmindernder Asphalt, Schutzwände und Schallschutzfenster. Solche Maßnahmen kosten allerdings Geld und stoßen nicht überall auf Zustimmung, etwa wenn Autofahrer langsamer fahren sollen.",
    "Einen Teil der Belastung hat jeder selbst in der Hand. Ohrstöpsel bei Konzerten, Abstand zu den Lautsprechern und Pausen für die Ohren beugen Schäden vor. Für Kopfhörer empfiehlt eine verbreitete Faustregel, höchstens 60 Prozent der möglichen Lautstärke zu nutzen und nach spätestens einer Stunde eine Pause einzulegen. Entscheidend ist, dass sich laute und ruhige Zeiten abwechseln. Ruhe ist kein Luxus, sondern eine Voraussetzung dafür, gesund zu bleiben."
  ]
});
