/* Probe-Vorbereitung zu Probe 2 „Energie nutzen“ (NT 8): Übungsaufgaben – nicht die Aufgaben der Probe.
 * Kennungen (id) nie neu vergeben; nurM: true = nur M8. Aufbau der Aufgaben: siehe vorbereitung.js. */
NT8Vorbereitung.pool("energie", [
  /* ----- Energie: Formen, Umwandlung, Erhaltung ----- */
  { id: "e1-b1", modul: "energieformen", art: "begriff", typ: "mc", q: "Welche Energieform hat ein Pfeil, der durch die Luft fliegt?", o: ["Bewegungsenergie", "Spannenergie", "Kernenergie", "chemische Energie"], a: 0,
    e: "Alles, was sich bewegt, hat Bewegungsenergie. Je schneller, desto mehr." },
  { id: "e1-b2", modul: "energieformen", art: "begriff", typ: "mc", q: "Wie heißt die Einheit, in der man Energie misst?", o: ["Joule", "Newton", "Volt", "Gramm"], a: 0,
    e: "Energie misst man in Joule (J) oder Kilojoule (kJ). 1 kJ sind 1000 J." },
  { id: "e1-z1", modul: "energieformen", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Energie kann sich von einer Form in eine andere umwandeln.", true], ["In einem Motor geht Energie für immer verloren.", false], ["Die entstehende Abwärme verteilt sich in der Umgebung und ist kaum nutzbar.", true], ["Je mehr Abwärme ein Gerät erzeugt, desto mehr Nutzenergie bleibt übrig.", false]],
    e: "Energie wird umgewandelt, sie geht nie verloren. Die Abwärme ist entwertet. Mehr Abwärme bedeutet weniger Nutzenergie." },
  { id: "e1-a1", modul: "energieformen", art: "anwendung", typ: "mc", q: "Welche Energiekette beschreibt einen Toaster am besten?", o: ["elektrische Energie → Wärme (und Licht)", "Wärme → elektrische Energie → Bewegung", "chemische Energie → Lageenergie", "Strahlungsenergie → Spannenergie"], a: 0,
    e: "Der Toaster nimmt elektrische Energie auf. Die Heizdrähte werden heiß und glühen dabei etwas." },
  { id: "e1-v1", modul: "energieformen", art: "versuch", typ: "mc", q: "Ein Schüler bohrt mit einem stumpfen Bohrer in ein Holzstück und misst die Temperatur an der Bohrstelle (siehe Tabelle). Was zeigt die Messreihe?",
    tabelle: { titel: "Temperatur an der Bohrstelle", kopf: ["Zeit in s", "Temperatur in °C"], zeilen: [["0", "21"], ["10", "27"], ["20", "34"]] },
    o: ["Die Bewegungsenergie des Bohrers wird zu Wärme.", "Das Holz erzeugt neue Energie.", "Die Wärme kommt aus dem Bohrer, der dabei leichter wird.", "Die Temperatur bleibt gleich."], a: 0,
    e: "Die Reibung wandelt Bewegungsenergie in Wärme um. Die Temperatur steigt, aber keine Energie ist neu entstanden." },
  { id: "e1-d1", modul: "energieformen", art: "diagramm", typ: "mc", q: "Ein Gummiball wird aus 100 cm Höhe fallen gelassen. Das Diagramm zeigt die Höhe nach den ersten Aufprallen. Welche Aussage passt?",
    diagramm: { art: "saeulen", titel: "Höhe des Balls nach dem Aufprall", xTitel: "Aufprall", yTitel: "Höhe in cm", x: ["1.", "2.", "3."], y: [80, 64, 51], text: "Säulendiagramm: Nach dem 1. Aufprall springt der Ball 80 cm hoch, nach dem 2. 64 cm und nach dem 3. 51 cm." },
    o: ["Bei jedem Aufprall wird ein Teil der Energie zu Wärme.", "Bei jedem Aufprall nimmt die Energie des Balls zu.", "Der Ball verliert beim Fallen Masse.", "Die Höhe hängt nicht von der Energie ab."], a: 0,
    e: "Die Lageenergie am höchsten Punkt wird mit jedem Sprung kleiner. Der fehlende Teil ist Wärme, die Summe bleibt gleich." },
  { id: "e1-r1", modul: "energieformen", art: "rechnen", typ: "zahl", q: "Eine Lampe nimmt in einer Sekunde 60 J elektrische Energie auf und gibt 3 J als Licht ab. Wie viel Energie wird in dieser Sekunde zu Wärme?", loesung: 57, toleranz: 0, einheit: "J",
    weg: "Aufgenommene Energie = Licht + Wärme. Also: 60 J − 3 J = 57 J.", e: "Die Summe bleibt gleich: Was nicht Licht wird, ist Abwärme." },
  { id: "e1-r2", modul: "energieformen", art: "rechnen", typ: "zahl", q: "Wie viele Joule sind 3,5 kJ?", loesung: 3500, toleranz: 0, einheit: "J",
    weg: "„Kilo“ heißt tausend: 3,5 · 1000 = 3500.", e: "Es gilt 1 kJ = 1000 J, also 3,5 kJ = 3500 J." },
  { id: "e1-t1", modul: "energieformen", art: "transfer", typ: "offen", q: "Eine Kerze brennt ab. Beschreibe die Energieumwandlung und erkläre, was mit der Energie passiert ist, wenn die Kerze nicht mehr brennt.",
    m: "Die chemische Energie des Wachses wird beim Brennen zu Wärme und Licht. Die Energie ist nicht verloren, sie hat sich als Wärme in der Umgebung verteilt und lässt sich kaum noch nutzen.",
    k: ["chemisch", "wärme|licht", "nicht verloren|erhalten|umgebung|verteilt"], min: 2, e: "Energie geht nie verloren, sie wird umgewandelt und am Ende meist zu kaum nutzbarer Wärme." },
  { id: "e1-t2", modul: "energieformen", art: "transfer", typ: "mc", q: "Ein Skifahrer fährt einen Hang hinab und bremst unten bis zum Stillstand. Welche Aussage über seine Energie stimmt?",
    o: ["Seine Lageenergie wird zu Bewegungsenergie und diese beim Bremsen zu Wärme.", "Seine Bewegungsenergie wird beim Bremsen zu Lageenergie.", "Seine Energie wird beim Bremsen vernichtet.", "Seine Lageenergie wird zu Kernenergie."], a: 0,
    e: "Oben hat er Lageenergie, beim Fahren wird sie zu Bewegungsenergie, beim Bremsen zu Wärme." },
  { id: "e1-n1", modul: "energieformen", art: "rechnen", typ: "zahl", nurM: true, q: "Ein Gerät mit einer Leistung von 5 W läuft 20 Sekunden lang. Wie viele Joule Energie nimmt es auf?", loesung: 100, toleranz: 0, einheit: "J",
    weg: "1 W = 1 Ws = 1 J je Sekunde. 5 W · 20 s = 100 Ws = 100 J.", e: "Es gilt 1 J = 1 Nm = 1 Ws." },
  { id: "e1-n2", modul: "energieformen", art: "zusammenhang", typ: "rf", nurM: true, q: "Prüfe die Aussagen zum Viertaktmotor.",
    aussagen: [["Ein Arbeitsspiel besteht aus zwei Umdrehungen der Kurbelwelle.", true], ["Der Motor gibt in jedem Takt Energie ab.", false], ["Pleuelstange und Kurbelwelle machen aus der Auf-und-ab-Bewegung eine Drehung.", true], ["Beim Verdichten sind beide Ventile geöffnet.", false]],
    e: "Nur im Arbeitstakt gibt der Motor Energie ab. Beim Verdichten sind beide Ventile geschlossen." },
  { id: "e1-n3", modul: "energieformen", art: "anwendung", typ: "mc", nurM: true, q: "Ein Motor nimmt 10 kJ chemische Energie auf und gibt 3 kJ Bewegungsenergie ab. Welche Aussage über die Bilanz stimmt?", o: ["Die übrigen 7 kJ sind Abwärme.", "Die übrigen 7 kJ sind verloren gegangen.", "Die übrigen 7 kJ sind als Spannenergie gespeichert.", "Man kann über die übrigen 7 kJ nichts sagen."], a: 0,
    e: "Energie bleibt erhalten: 10 kJ − 3 kJ = 7 kJ gehen als Abwärme in die Umgebung." },

  /* ----- Elektrische Leistung und Stromkosten ----- */
  { id: "e2-b1", modul: "leistung", art: "begriff", typ: "mc", q: "Was bedeutet die Angabe 1 kW?", o: ["1000 Watt", "100 Watt", "10 Watt", "1 000 000 Watt"], a: 0,
    e: "„Kilo“ heißt tausend. 1 kW = 1000 W." },
  { id: "e2-b2", modul: "leistung", art: "begriff", typ: "mc", q: "Welche Aussage über die Kilowattstunde stimmt?", o: ["Sie ist eine Einheit der Energie und steht auf der Stromrechnung.", "Sie ist eine Einheit der Leistung.", "Sie misst, wie stark der Strom ist.", "Sie gibt an, wie lange ein Gerät hält."], a: 0,
    e: "Die Kilowattstunde ist eine Einheit für Energie: 1 kW mal 1 Stunde." },
  { id: "e2-z1", modul: "leistung", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Ein Gerät im Stand-by braucht trotzdem Energie.", true], ["Energielabel G steht für ein besonders sparsames Gerät.", false], ["Mit einer schaltbaren Steckerleiste lässt sich Stand-by vermeiden.", true], ["Bei gleicher Spannung wird die Leistung kleiner, wenn die Stromstärke größer wird.", false]],
    e: "Stand-by braucht Energie. Label A ist sparsam, G braucht viel. Bei gleicher Spannung ist die Leistung umso größer, je größer die Stromstärke ist." },
  { id: "e2-a1", modul: "leistung", art: "anwendung", typ: "mc", q: "Du willst einen neuen Kühlschrank kaufen. Warum lohnt der Blick auf das Energielabel?", o: ["Es zeigt, wie sparsam das Gerät im Betrieb ist.", "Es zeigt, wie groß das Gerät ist.", "Es zeigt die Farbe des Geräts.", "Es zeigt, wie lange die Garantie läuft."], a: 0,
    e: "A bedeutet sehr sparsam, G einen hohen Energiebedarf. Ein sparsames Gerät senkt die Stromkosten über viele Jahre." },
  { id: "e2-v1", modul: "leistung", art: "versuch", typ: "mc", q: "Eine Lehrkraft schließt ein Gerät an ein Energiemessgerät an. Die Klasse liest das Display ab (siehe Tabelle). Welche Leistung hat das Gerät?",
    tabelle: { titel: "Anzeige des Energiemessgeräts", kopf: ["Laufzeit", "Energie"], zeilen: [["1 h", "0,10 kWh"], ["2 h", "0,20 kWh"], ["3 h", "0,30 kWh"]] },
    o: ["100 W", "10 W", "300 W", "0,1 W"], a: 0,
    e: "Pro Stunde wandelt das Gerät 0,10 kWh um. Das entspricht einer Leistung von 0,1 kW, also 100 W." },
  { id: "e2-d1", modul: "leistung", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt die Leistung von vier Geräten. Welches Gerät wandelt in 10 Minuten am meisten elektrische Energie um?",
    diagramm: { art: "saeulen", titel: "Leistung einiger Geräte", xTitel: "Gerät", yTitel: "Leistung in W", x: ["LED-Lampe", "Fernseher", "Föhn", "Wasserkocher"], y: [8, 100, 1800, 2000], text: "Säulendiagramm: Die LED-Lampe hat 8 W, der Fernseher 100 W, der Föhn 1800 W und der Wasserkocher 2000 W." },
    o: ["der Wasserkocher", "der Föhn", "der Fernseher", "die LED-Lampe"], a: 0,
    e: "Bei gleicher Laufzeit wandelt das Gerät mit der größten Leistung die meiste Energie um." },
  { id: "e2-r1", modul: "leistung", art: "rechnen", typ: "zahl", q: "Ein kleines Radio liegt an einer Spannung von 12 V. Die Stromstärke beträgt 2 A. Welche Leistung hat das Radio?", loesung: 24, toleranz: 0, einheit: "W",
    weg: "P = U · I = 12 V · 2 A = 24 W.", e: "Leistung ist Spannung mal Stromstärke." },
  { id: "e2-r2", modul: "leistung", art: "rechnen", typ: "zahl", q: "Ein Staubsauger mit 1000 W läuft 30 Minuten. 1 kWh kostet 30 Cent. Wie viel kostet der Betrieb?", loesung: 15, toleranz: 0, einheit: "Cent",
    weg: "1000 W = 1 kW. 30 min = 0,5 h. Energie: 1 kW · 0,5 h = 0,5 kWh. Kosten: 0,5 kWh · 30 Cent = 15 Cent.", e: "Erst die Energie in kWh bestimmen, dann mit dem Preis malnehmen." },
  { id: "e2-t1", modul: "leistung", art: "transfer", typ: "offen", q: "Ein Laptop-Netzteil steckt Tag und Nacht in der Steckdose, auch wenn der Laptop nicht angeschlossen ist. Es nimmt dabei etwa 0,5 W auf. Beurteile, ob sich das Herausziehen lohnt.",
    m: "0,5 W sind wenig, aber das Netzteil läuft rund um die Uhr, 8760 Stunden im Jahr. Das sind etwa 4,4 kWh und bei 40 Cent etwa 1,75 Euro im Jahr. Das lohnt sich kaum für ein Gerät, aber bei vielen Geräten zusammen spart man deutlich, am besten mit einer schaltbaren Steckerleiste.",
    k: ["rund um die uhr|dauernd|8760|jahr", "kwh|euro|cent|kosten", "steckerleiste|vielen geräten|zusammen|lohnt"], min: 2, e: "Kleine Leistung mal sehr lange Zeit ergibt eine merkbare Energiemenge." },
  { id: "e2-t2", modul: "leistung", art: "transfer", typ: "mc", q: "Ein Heizlüfter mit 2 kW läuft 3 Stunden, ein Heizkörper mit 1 kW läuft 6 Stunden. Was gilt für die umgewandelte Energie?", o: ["Beide wandeln gleich viel Energie um.", "Der Heizlüfter wandelt mehr Energie um.", "Der Heizkörper wandelt doppelt so viel Energie um.", "Der Heizlüfter wandelt doppelt so viel Energie um."], a: 0,
    e: "2 kW · 3 h = 6 kWh und 1 kW · 6 h = 6 kWh. Es kommt auf Leistung mal Zeit an." },
  { id: "e2-n1", modul: "leistung", art: "rechnen", typ: "zahl", nurM: true, q: "Ein Gerät liegt 8 Stunden an 230 V. Die Stromstärke beträgt 0,5 A. Wie viele Kilowattstunden Energie wandelt es um?", loesung: 0.92, toleranz: 0.01, einheit: "kWh",
    weg: "P = U · I = 230 V · 0,5 A = 115 W = 0,115 kW. E = 0,115 kW · 8 h = 0,92 kWh.", e: "Es gilt E = U · I · t." },
  { id: "e2-n2", modul: "leistung", art: "rechnen", typ: "zahl", nurM: true, q: "Ein Gerät mit 460 W liegt an 230 V. Wie groß ist die Stromstärke?", loesung: 2, toleranz: 0, einheit: "A",
    weg: "Aus P = U · I folgt I = P : U = 460 W : 230 V = 2 A.", e: "Die Formel P = U · I lässt sich nach I umstellen." },
  { id: "e2-n3", modul: "leistung", art: "begriff", typ: "mc", nurM: true, q: "Wie viele Watt sind 750 mW?", o: ["0,75 W", "7,5 W", "750 W", "0,075 W"], a: 0,
    e: "1 W = 1000 mW. Also sind 750 mW genau 0,75 W." },

  /* ----- Kraftwerke und der Weg des Stroms ----- */
  { id: "e3-b1", modul: "kraftwerke", art: "begriff", typ: "mc", q: "Was macht eine Turbine im Kraftwerk?", o: ["Dampf oder Wasser dreht sie, sie liefert die Drehbewegung für den Generator.", "Sie erzeugt aus Wärme direkt die Spannung.", "Sie senkt die Spannung ab.", "Sie kühlt den Dampf."], a: 0,
    e: "Die Turbine ist ein Rad mit Schaufeln. Sie treibt den Generator an, der die elektrische Energie erzeugt." },
  { id: "e3-b2", modul: "kraftwerke", art: "begriff", typ: "mc", q: "Was geschieht in einem Umspannwerk?", o: ["Große Transformatoren ändern die Höhe der Spannung.", "Strom wird aus Kohle erzeugt.", "Strom wird für die Nacht gespeichert.", "Der Strom wird gezählt und bezahlt."], a: 0,
    e: "Umspannwerke heben die Spannung für die Fernleitung an oder senken sie wieder ab." },
  { id: "e3-z1", modul: "kraftwerke", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Im Wasserkraftwerk ist die Lageenergie des Wassers der Start der Energiekette.", true], ["Ein Wasserkraftwerk braucht einen Kessel.", false], ["Im Wärmekraftwerk treibt heißer Dampf die Turbine an.", true], ["Der Wirkungsgrad eines Kraftwerks kann über 100 % liegen.", false]],
    e: "Das Wasserkraftwerk nutzt fallendes Wasser, einen Kessel braucht es nicht. Der Wirkungsgrad ist immer kleiner als 100 %." },
  { id: "e3-a1", modul: "kraftwerke", art: "anwendung", typ: "mc", q: "Warum wird die Spannung am Kraftwerk für die Fernleitung stark erhöht?", o: ["Dann ist die Stromstärke klein und in der Leitung geht wenig Energie verloren.", "Dann fließt der Strom schneller als Licht.", "Dann ist die Leitung leichter.", "Dann wird mehr Energie erzeugt."], a: 0,
    e: "Bei gleicher Leistung bedeutet hohe Spannung kleine Stromstärke. Die Leitung erwärmt sich dann kaum." },
  { id: "e3-v1", modul: "kraftwerke", art: "versuch", typ: "mc", q: "Mit einem Modell-Wasserrad wird untersucht, wie sich die Fallhöhe des Wassers auswirkt (siehe Tabelle, gleiche Wassermenge). Was zeigt die Messreihe?",
    tabelle: { titel: "Modell-Wasserrad", kopf: ["Fallhöhe in cm", "Umdrehungen pro Minute"], zeilen: [["10", "40"], ["20", "80"], ["30", "120"]] },
    o: ["Je größer die Fallhöhe, desto schneller dreht sich das Rad.", "Je größer die Fallhöhe, desto langsamer dreht sich das Rad.", "Die Fallhöhe hat keinen Einfluss.", "Das Rad dreht sich nur bei 20 cm."], a: 0,
    e: "Mehr Fallhöhe bedeutet mehr Bewegungsenergie des Wassers. Das ist der Grund, warum Stauseen hoch liegen." },
  { id: "e3-d1", modul: "kraftwerke", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt den Wirkungsgrad dreier Kraftwerke. Welche Aussage passt?",
    diagramm: { art: "saeulen", titel: "Wirkungsgrad dreier Kraftwerke", xTitel: "Kraftwerk", yTitel: "Wirkungsgrad in %", x: ["Kohle", "Gas", "Wasser"], y: [40, 60, 90], text: "Säulendiagramm: Das Kohlekraftwerk hat etwa 40 %, das Gaskraftwerk bis etwa 60 % und das Wasserkraftwerk etwa 90 % Wirkungsgrad." },
    o: ["Das Wasserkraftwerk macht aus gleich viel Energie am meisten Strom.", "Das Kohlekraftwerk macht am meisten Strom.", "Alle drei machen gleich viel Strom.", "Das Gaskraftwerk hat den kleinsten Wirkungsgrad."], a: 0,
    e: "Der höchste Balken gehört zum Wasserkraftwerk: etwa 90 von 100 Teilen werden zu Strom." },
  { id: "e3-r1", modul: "kraftwerke", art: "rechnen", typ: "zahl", q: "Ein Kraftwerk setzt 500 Einheiten Energie ein und liefert 150 Einheiten elektrische Energie. Wie groß ist der Wirkungsgrad?", loesung: 30, toleranz: 0, einheit: "%",
    weg: "150 : 500 = 0,3. Das sind 30 %.", e: "Wirkungsgrad = Strom geteilt durch eingesetzte Energie." },
  { id: "e3-r2", modul: "kraftwerke", art: "rechnen", typ: "zahl", q: "Ein Kraftwerk mit einem Wirkungsgrad von 25 % setzt 800 Einheiten Energie ein. Wie viele Einheiten werden zu elektrischer Energie?", loesung: 200, toleranz: 0, einheit: "Einheiten",
    weg: "25 % von 800 sind 800 : 4 = 200.", e: "Elektrische Energie = Wirkungsgrad mal eingesetzte Energie." },
  { id: "e3-t1", modul: "kraftwerke", art: "transfer", typ: "offen", q: "Ein Bergdorf hat einen Bach mit starkem Gefälle. Beschreibe, wie dort ein kleines Wasserkraftwerk Strom erzeugen könnte.",
    m: "Das Wasser fließt durch ein Rohr bergab. Seine Lageenergie wird zu Bewegungsenergie. Das schnelle Wasser dreht eine Turbine, die Turbine treibt einen Generator an und der Generator erzeugt elektrische Energie.",
    k: ["lageenergie|gefälle|bergab|fällt", "turbine", "generator", "elektrisch|strom"], min: 3, e: "Kette: Lageenergie → Bewegungsenergie → elektrische Energie. Ein Brennstoff ist nicht nötig." },
  { id: "e3-t2", modul: "kraftwerke", art: "transfer", typ: "mc", q: "Ein Hausbesitzer sagt: „Eine Photovoltaikanlage hat nur 20 % Wirkungsgrad, also lohnt sie nie.“ Welche Antwort ist gut begründet?", o: ["Der Wirkungsgrad ist nur ein Kriterium, die Sonne kostet nichts und es wird nichts verbrannt.", "Ein kleiner Wirkungsgrad ist für ein Kraftwerk der beste Wert.", "Der Wirkungsgrad spielt bei Kraftwerken keine Rolle.", "Photovoltaik braucht nie eine Fläche."], a: 0,
    e: "Man bewertet immer mehrere Kriterien: Wirkungsgrad, Kosten und Umwelt." },
  { id: "e3-n1", modul: "kraftwerke", art: "bewerten", typ: "offen", nurM: true, q: "Ein Plakat sagt: „Windräder sind hässlich.“ Trenne Sachliches und Wertendes und formuliere eine sachliche Aussage über Windräder.",
    m: "„Hässlich“ ist eine Wertung, denn sie hängt von der Meinung ab. Sachlich kann man sagen: Ein Windrad stößt im Betrieb kein CO₂ aus und greift in die Landschaft ein.",
    k: ["wertung|wertend|meinung", "sachlich|nachprüf|messbar|überprüf", "co₂|co2|landschaft|strom nur bei wind"], min: 2, e: "Sachliche Aussagen kann man prüfen, wertende hängen von der Meinung ab." },
  { id: "e3-n2", modul: "kraftwerke", art: "rechnen", typ: "zahl", nurM: true, q: "Ein Betrieb braucht eine Leistung von 23 000 W. Die Zuleitung hat 2300 V. Wie groß ist die Stromstärke?", loesung: 10, toleranz: 0, einheit: "A",
    weg: "I = P : U = 23 000 W : 2300 V = 10 A.", e: "Bei gleicher Leistung gehört zu höherer Spannung eine kleinere Stromstärke." },
  { id: "e3-n3", modul: "kraftwerke", art: "zusammenhang", typ: "mc", nurM: true, q: "Die Stromstärke in einer Leitung wird auf ein Zehntel verkleinert. Was geschieht mit der Wärme in der Leitung?", o: ["Sie sinkt auf ein Hundertstel.", "Sie sinkt auf ein Zehntel.", "Sie bleibt gleich.", "Sie steigt auf das Zehnfache."], a: 0,
    e: "Die Wärme wächst mit dem Quadrat der Stromstärke. Ein Zehntel mal ein Zehntel ergibt ein Hundertstel." },

  /* ----- Energie bei chemischen Reaktionen ----- */
  { id: "e4-b1", modul: "reaktionsenergie", art: "begriff", typ: "mc", q: "Was bedeutet das Wort „exotherm“?", o: ["Die Reaktion gibt Energie an die Umgebung ab.", "Die Reaktion nimmt Energie aus der Umgebung auf.", "Die Reaktion braucht einen Katalysator.", "Bei der Reaktion entsteht Energie aus dem Nichts."], a: 0,
    e: "Exotherm: Energie geht nach außen, meist als Wärme und Licht. Neu entstehen kann Energie nie." },
  { id: "e4-b2", modul: "reaktionsenergie", art: "begriff", typ: "mc", q: "Wofür braucht man die Aktivierungsenergie?", o: ["Damit eine Reaktion überhaupt beginnt.", "Damit eine Reaktion endotherm wird.", "Damit die Produkte schwerer werden.", "Damit der Katalysator verbraucht wird."], a: 0,
    e: "Sie ist die Starthilfe. Im Energiediagramm ist es der Hügel, der überwunden werden muss." },
  { id: "e4-z1", modul: "reaktionsenergie", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Ein Katalysator wird bei der Reaktion nicht verbraucht.", true], ["Die Elektrolyse von Wasser läuft von selbst weiter, wenn der Strom abgeschaltet wird.", false], ["Bei einer exothermen Reaktion liegen die Produkte im Energiediagramm tiefer.", true], ["Ein Katalysator liefert der Reaktion zusätzliche Energie.", false]],
    e: "Der Katalysator senkt nur die Aktivierungsenergie. Die Elektrolyse ist endotherm und stoppt ohne Strom." },
  { id: "e4-a1", modul: "reaktionsenergie", art: "anwendung", typ: "mc", q: "Wozu hat ein Auto einen Abgaskatalysator?", o: ["Er wandelt giftige Abgase in weniger schädliche Stoffe um.", "Er macht den Motor schneller.", "Er erzeugt zusätzliche Bewegungsenergie.", "Er kühlt das Benzin."], a: 0,
    e: "Der Katalysator setzt die Aktivierungsenergie herab und wird dabei nicht aufgebraucht." },
  { id: "e4-v1", modul: "reaktionsenergie", art: "versuch", typ: "mc", q: "Eine Brausetablette wird in Wasser gegeben und die Temperatur gemessen (siehe Tabelle). Was folgt aus der Messreihe?",
    tabelle: { titel: "Temperatur im Wasser", kopf: ["Zeit in min", "Temperatur in °C"], zeilen: [["0", "20"], ["1", "19"], ["2", "18"], ["3", "17"]] },
    o: ["Die Reaktion nimmt Wärme aus dem Wasser auf: Sie ist endotherm.", "Die Reaktion gibt Wärme ab: Sie ist exotherm.", "Es läuft keine Reaktion ab.", "Die Energie geht verloren."], a: 0,
    e: "Sinkt die Temperatur der Umgebung, wird Energie aus der Umgebung aufgenommen." },
  { id: "e4-v2", modul: "reaktionsenergie", art: "versuch", typ: "mc", q: "Beschriebene Beobachtung: Bei der Elektrolyse von Wasser steigen Gasblasen auf. Die Lehrkraft schaltet den Strom aus, und die Bläschen hören sofort auf. Was folgt daraus?", o: ["Die Zersetzung läuft nur, solange Energie zugeführt wird.", "Die Reaktion gibt Energie ab.", "Das Wasser hat sich in Metall verwandelt.", "Die Reaktion braucht keine Energie."], a: 0,
    e: "Ohne Energiezufuhr stoppt die Reaktion: Das ist typisch für eine endotherme Reaktion." },
  { id: "e4-d1", modul: "reaktionsenergie", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt den Temperaturverlauf zweier Reaktionen. Welche Aussage passt?",
    diagramm: { art: "linie", titel: "Temperatur im Reaktionsgefäß", xTitel: "Zeit in min", yTitel: "Temperatur in °C", x: ["0", "1", "2", "3"], reihen: [{ name: "Reaktion X", y: [20, 24, 27, 28] }, { name: "Reaktion Y", y: [20, 18, 16, 15] }], text: "Liniendiagramm: Reaktion X steigt von 20 auf 28 Grad, Reaktion Y sinkt von 20 auf 15 Grad." },
    o: ["X ist exotherm, Y ist endotherm.", "X ist endotherm, Y ist exotherm.", "Beide sind exotherm.", "Beide sind endotherm."], a: 0,
    e: "Steigt die Temperatur, wird Energie abgegeben. Sinkt sie, wird Energie aufgenommen." },
  { id: "e4-r1", modul: "reaktionsenergie", art: "rechnen", typ: "zahl", q: "Im Energiediagramm einer Reaktion liegen die Ausgangsstoffe bei 100 kJ, die Spitze des Hügels bei 130 kJ und die Produkte bei 60 kJ. Wie groß ist die Aktivierungsenergie?", loesung: 30, toleranz: 0, einheit: "kJ",
    diagramm: { art: "saeulen", titel: "Energie in einer Reaktion", xTitel: "Stelle im Diagramm", yTitel: "Energie in kJ", x: ["Ausgangsstoffe", "Spitze", "Produkte"], y: [100, 130, 60], text: "Säulendiagramm: Ausgangsstoffe 100 kJ, Spitze des Hügels 130 kJ, Produkte 60 kJ." },
    weg: "Aktivierungsenergie = Spitze − Ausgangsstoffe = 130 kJ − 100 kJ = 30 kJ.", e: "Die Aktivierungsenergie ist der Weg bis zur Spitze des Hügels." },
  { id: "e4-r2", modul: "reaktionsenergie", art: "rechnen", typ: "zahl", q: "Bei einer Reaktion liegen die Ausgangsstoffe bei 100 kJ und die Produkte bei 60 kJ. Wie viel Energie wird abgegeben?", loesung: 40, toleranz: 0, einheit: "kJ",
    weg: "Abgegebene Energie = 100 kJ − 60 kJ = 40 kJ.", e: "Der Höhenunterschied zwischen Ausgangsstoffen und Produkten ist die abgegebene Energie." },
  { id: "e4-t1", modul: "reaktionsenergie", art: "transfer", typ: "offen", q: "Ein Blatt Papier liegt auf dem Tisch und brennt nicht. Hält man eine Ecke kurz in eine Flamme, brennt es allein weiter. Erkläre das mit Aktivierungsenergie.",
    m: "Die Flamme liefert die Aktivierungsenergie, die zum Start der Reaktion nötig ist. Danach brennt das Papier von selbst weiter, weil die Reaktion exotherm ist und selbst Wärme abgibt.",
    k: ["aktivierungsenergie|anstoß|starthilfe|flamme", "von selbst|weiter", "exotherm|wärme|energie ab|abgegeben"], min: 2, e: "Die Starthilfe ist nötig, danach liefert die Reaktion selbst genug Wärme." },
  { id: "e4-t2", modul: "reaktionsenergie", art: "transfer", typ: "mc", q: "Beim Aufbrechen eines Kühlpacks wird der Beutel in der Hand kalt. Was folgt daraus?", o: ["Im Beutel läuft eine Reaktion ab, die Wärme aufnimmt.", "Im Beutel entsteht Kälte aus dem Nichts.", "Der Beutel gibt Wärme an die Hand ab.", "Im Beutel läuft keine Reaktion ab."], a: 0,
    e: "Das Kühlpack nimmt Wärme aus der Umgebung auf. Es erzeugt keine Kälte." },
  { id: "e4-n1", modul: "reaktionsenergie", art: "zusammenhang", typ: "mc", nurM: true, q: "Was gilt für die innere Energie bei einer endothermen Reaktion?", o: ["Die Produkte haben mehr innere Energie als die Ausgangsstoffe.", "Die Produkte haben weniger innere Energie als die Ausgangsstoffe.", "Die innere Energie bleibt gleich und es wird Wärme frei.", "Die innere Energie verschwindet."], a: 0,
    e: "Der Unterschied muss von außen zugeführt werden, deshalb liegen die Produkte im Diagramm höher." },
  { id: "e4-n2", modul: "reaktionsenergie", art: "begriff", typ: "mc", nurM: true, q: "Warum können Enzyme im Körper bei etwa 37 °C Reaktionen schnell ablaufen lassen?", o: ["Sie setzen als Katalysatoren die Aktivierungsenergie herab.", "Sie liefern die gesamte Energie der Reaktion.", "Sie werden bei jeder Reaktion aufgebraucht.", "Sie machen jede Reaktion exotherm."], a: 0,
    e: "Enzyme sind Katalysatoren im Körper. Sie bleiben nach der Reaktion erhalten." },
  { id: "e4-n3", modul: "reaktionsenergie", art: "rechnen", typ: "zahl", nurM: true, q: "Beim Verbrennen von Wasserstoff werden für eine bestimmte Wassermenge 240 kJ frei. Wie viel Energie braucht man mindestens, um genau diese Wassermenge wieder zu zerlegen?", loesung: 240, toleranz: 0, einheit: "kJ",
    weg: "Hin- und Rückreaktion setzen gleich viel Energie um. Zerlegen kostet also 240 kJ.", e: "Wegen der Energieerhaltung ist die Rückreaktion endotherm mit demselben Betrag." }
]);
