/* Probe-Vorbereitung zu Probe 3 „Mensch und Gesundheit“ (NT 8): Übungsaufgaben – nicht die Aufgaben der Probe.
 * Kennungen (id) nie neu vergeben; nurM: true = nur M8. Aufbau der Aufgaben: siehe vorbereitung.js.
 * Alle Personen sind erfunden. Es wird nie nach eigenem Konsum, eigenem Körper oder eigenen Erfahrungen gefragt. */
NT8Vorbereitung.pool("gesundheit", [
  /* ----- Mikroorganismen ----- */
  { id: "g1-b1", modul: "mikroorganismen", art: "begriff", typ: "mc", q: "Welche Aussage über Bakterien stimmt?", o: ["Es sind einzellige Lebewesen, deren Erbgut frei im Zellplasma liegt.", "Es sind Zellen mit Zellkern und Chloroplasten.", "Es sind winzige Teilchen, die sich nur in Wirtszellen vermehren.", "Es sind mehrzellige Pilze, die Knospen bilden."], a: 0,
    e: "Bakterien bestehen aus einer einzigen Zelle. Sie haben keinen Zellkern, ihr Erbgut liegt frei im Zellplasma. Nur Viren vermehren sich ausschließlich in Wirtszellen." },
  { id: "g1-b2", modul: "mikroorganismen", art: "begriff", typ: "mc", q: "Was versteht man unter einem Nährboden?", o: ["Ein Gelee mit Nährstoffen, auf dem Mikroorganismen wachsen.", "Die Erde unter einem Laubwald.", "Ein Behälter, in dem Joghurt gekühlt wird.", "Ein Mittel, das Bakterien abtötet."], a: 0,
    e: "Auf einem Nährboden finden Mikroorganismen Futter. So werden aus einzelnen Bakterien sichtbare Flecken, die Kolonien." },
  { id: "g1-z1", modul: "mikroorganismen", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Hefe ist ein winziger Pilz aus einer Zelle.", true], ["Ein Virus vermehrt sich selbstständig durch Teilung.", false], ["Pilze und Bakterien zersetzen Totes und setzen dabei Mineralstoffe frei.", true], ["Bakterien brauchen zum Wachsen Kälte und Trockenheit.", false]],
    e: "Hefe ist ein Pilz. Viren brauchen eine Wirtszelle. Destruenten setzen Mineralstoffe frei. Mikroorganismen brauchen Wärme, Feuchtigkeit und Nahrung." },
  { id: "g1-a1", modul: "mikroorganismen", art: "anwendung", typ: "mc", q: "Pizza aus der Tiefkühltruhe hält sich monatelang. Warum?", o: ["Bei sehr tiefen Temperaturen vermehren sich Mikroorganismen kaum.", "Beim Einfrieren sterben alle Mikroorganismen sofort ab.", "Gefrorenes Essen enthält keine Nährstoffe.", "Kälte macht Essen trocken und salzig."], a: 0,
    e: "Kälte bremst die Vermehrung der Mikroorganismen. Sie sterben dabei nicht alle ab, deshalb verdirbt aufgetautes Essen schnell." },
  { id: "g1-v1", modul: "mikroorganismen", art: "versuch", typ: "mc", q: "Eine Lehrkraft stellt gleich viel Milch mit Joghurtkultur an vier Orte mit verschiedener Temperatur (siehe Tabelle). Was folgt aus der Messreihe?",
    tabelle: { titel: "Zustand der Milch nach sechs Stunden", kopf: ["Temperatur", "Zustand"], zeilen: [["4 °C", "flüssig"], ["20 °C", "etwas dicker"], ["42 °C", "fest wie Joghurt"], ["80 °C", "flüssig"]] },
    o: ["Die Bakterien arbeiten bei etwa 42 °C am besten, bei 80 °C sind sie abgestorben.", "Die Bakterien arbeiten bei 4 °C am besten.", "Je heißer, desto besser arbeiten die Bakterien.", "Die Temperatur hat keinen Einfluss auf die Bakterien."], a: 0,
    e: "Bei Wärme teilen sich die Milchsäurebakterien und bilden Milchsäure, die die Milch dick macht. Zu kalt bremst sie, zu heiß tötet sie." },
  { id: "g1-d1", modul: "mikroorganismen", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt, wie lange Milch bei verschiedenen Temperaturen haltbar ist (Modellwerte). Was kannst du ablesen?",
    diagramm: { art: "saeulen", titel: "Haltbarkeit von Milch (Modell)", xTitel: "Lagerort", yTitel: "Tage bis zum Verderben", x: ["Kühlschrank (5 °C)", "Zimmer (20 °C)", "warmer Raum (30 °C)"], y: [7, 2, 1], text: "Säulendiagramm: Im Kühlschrank bei 5 Grad ist die Milch 7 Tage haltbar, im Zimmer bei 20 Grad 2 Tage und in einem warmen Raum bei 30 Grad nur 1 Tag." },
    o: ["Je wärmer die Milch steht, desto kürzer ist sie haltbar.", "Je wärmer die Milch steht, desto länger ist sie haltbar.", "Die Temperatur hat keinen Einfluss auf die Haltbarkeit.", "Im warmen Raum hält die Milch am längsten."], a: 0,
    e: "Bei Wärme vermehren sich die Mikroorganismen in der Milch schneller. Deshalb verdirbt sie dort früher." },
  { id: "g1-t1", modul: "mikroorganismen", art: "transfer", typ: "offen", q: "Ein angebrochenes Marmeladenglas steht im Sommer geöffnet auf der Fensterbank. Nach einer Woche wächst Schimmel darauf. Erkläre mit den Lebensbedingungen von Mikroorganismen, warum das passiert.",
    m: "Auf der Marmelade findet der Schimmelpilz Nahrung, nämlich Zucker. Die Marmelade ist feucht, und im Sommer ist es auf der Fensterbank warm. Mit Nahrung, Feuchtigkeit und Wärme vermehrt sich der Pilz schnell.",
    k: ["nahrung|zucker|futter", "warm|wärme|waerme", "feucht|wasser"], min: 2, e: "Mikroorganismen brauchen Wärme, Feuchtigkeit und Nahrung. Sind alle drei da, vermehren sie sich schnell." },
  { id: "g1-t2", modul: "mikroorganismen", art: "transfer", typ: "mc", q: "Maja stellt einen frisch angesetzten Hefeteig in den kalten Keller (5 °C). Nach einer Stunde ist er kaum aufgegangen. Warum?", o: ["Bei Kälte arbeitet die Hefe nur sehr langsam und bildet wenig Gas.", "Die Kälte hat alle Hefezellen sofort abgetötet.", "Hefe braucht kein Gas, um den Teig aufzulockern.", "Im Keller fehlt der Zucker im Teig."], a: 0,
    e: "Hefe bildet Gas und lockert so den Teig. Kälte bremst sie, sie stirbt aber nicht. Erst große Hitze tötet sie." },
  { id: "g1-w1", modul: "mikroorganismen", art: "bewerten", typ: "mc", q: "Ein Mitschüler behauptet: „Alle Bakterien sind gefährlich, man sollte sie am besten alle abtöten.“ Welche Antwort ist am besten begründet?", o: ["Das stimmt nicht: Die meisten Bakterien sind harmlos oder nützlich, zum Beispiel im Joghurt und im Boden.", "Das stimmt: Jedes Bakterium macht krank.", "Das stimmt, aber nur im Winter.", "Das stimmt nur für Bakterien im Joghurt."], a: 0,
    e: "Viele Bakterien helfen uns: Milchsäurebakterien machen Joghurt, Destruenten zersetzen Totes. Nur wenige machen krank." },
  { id: "g1-n1", modul: "mikroorganismen", art: "rechnen", typ: "zahl", nurM: true, q: "Aus 5 Bakterien wird unter guten Bedingungen alle 20 Minuten die doppelte Zahl. Wie viele Bakterien sind es nach 100 Minuten?", loesung: 160, toleranz: 0, einheit: "Bakterien",
    weg: "100 min : 20 min = 5 Teilungen. 5 · 2⁵ = 5 · 32 = 160.", e: "Bei n Teilungen wird die Anfangszahl mit 2ⁿ malgenommen." },
  { id: "g1-n2", modul: "mikroorganismen", art: "begriff", typ: "mc", nurM: true, q: "Eine Zelle hat Zellkern, Zellwand und Chloroplasten. Um welchen Zelltyp handelt es sich?", o: ["Pflanzenzelle", "Tierzelle", "Bakterium", "Hefezelle"], a: 0,
    e: "Chloroplasten gibt es nur in Pflanzenzellen. Eine Tierzelle hat keine Zellwand, ein Bakterium keinen Zellkern, und die Hefezelle hat keine Chloroplasten." },
  { id: "g1-n3", modul: "mikroorganismen", art: "zusammenhang", typ: "offen", nurM: true, q: "Bakterien in einer Nährlösung vermehren sich zuerst immer schneller, dann flacht die Kurve ab. Begründe, warum.",
    m: "Am Anfang gibt es genug Nahrung und Platz, deshalb verdoppelt sich die Zahl immer wieder. Später wird die Nahrung knapp und Abfallstoffe sammeln sich an, deshalb kommen weniger neue Bakterien dazu.",
    k: ["nahrung|futter", "abfall|platz|knapp"], min: 2, e: "Das Wachstum bremst sich selbst: Ohne genug Nahrung und Platz teilen sich weniger Zellen." },

  /* ----- Infektionen, Immunsystem und Impfung ----- */
  { id: "g2-b1", modul: "infektion", art: "begriff", typ: "mc", q: "Was geschieht während der Inkubationszeit?", o: ["Die Erreger vermehren sich, man spürt aber noch nichts.", "Die Krankheitszeichen sind am stärksten.", "Der Körper ist wieder ganz gesund.", "Die Erreger gelangen erst durch die Haut."], a: 0,
    e: "Zwischen der Infektion (Ansteckung) und dem Ausbruch der Krankheit liegt die Inkubation (Inkubationszeit). Man kann in dieser Zeit schon ansteckend sein." },
  { id: "g2-b2", modul: "infektion", art: "begriff", typ: "mc", q: "Warum gelten Viren als Sonderfall unter den Erregern?", o: ["Sie sind keine Zellen und vermehren sich nur in Wirtszellen.", "Sie sind größer als Bakterien.", "Sie haben einen eigenen Stoffwechsel.", "Antibiotika wirken gegen sie besonders gut."], a: 0,
    e: "Ein Virus ist viel kleiner als ein Bakterium und besteht nur aus Erbgut und Hülle. Antibiotika wirken nicht gegen Viren." },
  { id: "g2-z1", modul: "infektion", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Händewaschen schützt vor einer Schmierinfektion.", true], ["Zecken können Borreliose und FSME übertragen.", true], ["Gegen Borreliose gibt es eine Impfung.", false], ["Fußpilz wird von Bakterien ausgelöst.", false]],
    e: "Erreger gelangen von den Händen in Mund oder Nase. Gegen FSME gibt es eine Impfung, gegen Borreliose nicht. Fußpilz ist eine Pilzinfektion." },
  { id: "g2-a1", modul: "infektion", art: "anwendung", typ: "mc", q: "Nach dem Schwimmbadbesuch juckt es bei einem Kind zwischen den Zehen: Fußpilz. Welcher Erreger steckt dahinter?", o: ["Ein Pilz, der sich in feuchter Wärme wohlfühlt.", "Ein Virus aus der Luft.", "Bakterien aus einer Zecke.", "Milchsäurebakterien."], a: 0,
    e: "Fußpilz wird von einem Pilz verursacht. In feuchter Wärme, etwa in Schwimmbädern, fühlt er sich wohl." },
  { id: "g2-v1", modul: "infektion", art: "versuch", typ: "mc", q: "In einem Modell mit festen Werten wird gezählt, wie viele Kinder nach einem Nieser angesteckt werden (siehe Tabelle). Was zeigt die Tabelle?",
    tabelle: { titel: "Angesteckte Kinder nach einem Nieser (Modell)", kopf: ["Schutz", "Angesteckte Kinder"], zeilen: [["kein Schutz", "9"], ["nur lüften", "6"], ["lüften und Abstand halten", "3"], ["lüften, Abstand, Hände waschen", "1"]] },
    o: ["Jede zusätzliche Schutzmaßnahme senkt die Zahl der Ansteckungen.", "Lüften erhöht die Zahl der Ansteckungen.", "Die Schutzmaßnahmen haben keinen Einfluss.", "Abstand halten wirkt nur zusammen mit Antibiotika."], a: 0,
    e: "Mit jeder Maßnahme sinkt die Zahl der Angesteckten. Zusammen wirken sie am besten." },
  { id: "g2-d1", modul: "infektion", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt die Körpertemperatur eines erkrankten Kindes. An welchem Tag lag sie zum ersten Mal über 38 °C?",
    diagramm: { art: "linie", titel: "Körpertemperatur eines erkrankten Kindes", xTitel: "Tag", yTitel: "Körpertemperatur in °C", x: ["0", "1", "2", "3", "4", "5"], y: [36.8, 37.2, 38.4, 39.0, 38.1, 37.0], text: "Liniendiagramm: Tag 0 mit 36,8 Grad, Tag 1 mit 37,2, Tag 2 mit 38,4, Tag 3 mit 39,0, Tag 4 mit 38,1 und Tag 5 mit 37,0 Grad." },
    o: ["an Tag 2", "an Tag 1", "an Tag 3", "an Tag 4"], a: 0,
    e: "An Tag 1 sind es 37,2 °C, an Tag 2 schon 38,4 °C. Der Gipfel liegt an Tag 3." },
  { id: "g2-t1", modul: "infektion", art: "transfer", typ: "offen", q: "Nach einem Grillfest erkranken mehrere Gäste an Salmonellen. Alle hatten Hähnchenfleisch gegessen, das innen noch roh war. Erkläre, wie es zur Ansteckung kam, und nenne eine Schutzmaßnahme.",
    m: "Die Salmonellen waren im rohen Fleisch. Weil es nicht richtig durchgegart war, gelangten die Erreger mit dem Essen in den Körper. Schützen kann man sich, indem man Fleisch gut durchgart und die Küche sauber hält.",
    k: ["fleisch|essen", "durchgar|sauber|hände|haende|waschen"], min: 2, e: "Über Essen und Wasser können Erreger in den Körper gelangen. Gut durchgaren und Sauberkeit in der Küche schützen." },
  { id: "g2-t2", modul: "infektion", art: "transfer", typ: "mc", q: "Beim Basteln hat sich ein Kind tief in den Finger geschnitten. Was ist am sinnvollsten?", o: ["Die Wunde reinigen und abdecken, damit weniger Erreger eindringen.", "Die Wunde offen lassen und mit Erde bestreuen.", "Sofort ein Antibiotikum nehmen.", "Nichts tun, denn die Haut schützt immer."], a: 0,
    e: "Eine Wunde ist ein Tor für Erreger. Sauber machen und abdecken verringert das Risiko." },
  { id: "g2-w1", modul: "infektion", art: "bewerten", typ: "mc", q: "Eine Schülerin will nicht neben einem Mitschüler sitzen, der HIV hat. Wie beurteilst du das?", o: ["Das ist unbegründet: Im normalen Alltag wie Händeschütteln oder gemeinsamem Trinken wird HIV nicht übertragen.", "Das ist richtig: HIV wird beim Atmen übertragen.", "Das ist richtig: HIV wird über Türklinken weitergegeben.", "Das ist richtig, denn HIV steckt schon bei einem Blickkontakt an."], a: 0,
    e: "HIV wird über Blut, ungeschützten Geschlechtsverkehr und von der Mutter auf das Kind übertragen, nicht im normalen Alltag. Ausgrenzung ist deshalb nicht begründet." },
  { id: "g2-n1", modul: "infektion", art: "zusammenhang", typ: "rf", nurM: true, q: "Prüfe die Aussagen zur gezielten Abwehr.",
    aussagen: [["Ein Antikörper passt nur auf ein bestimmtes Merkmal eines Erregers.", true], ["Gedächtniszellen entstehen bei der passiven Immunisierung.", false], ["Beim zweiten Kontakt mit demselben Erreger bilden sich Antikörper schneller.", true], ["Antikörper wirken bei jedem Erreger gleich gut.", false]],
    e: "Antikörper arbeiten nach dem Schlüssel-Schloss-Prinzip. Gedächtniszellen entstehen nur, wenn der Körper selbst reagiert, also bei der aktiven Immunisierung." },
  { id: "g2-n2", modul: "infektion", art: "anwendung", typ: "mc", nurM: true, q: "Warum nützt es ungeimpften Menschen, wenn viele andere geimpft sind?", o: ["Der Erreger findet kaum noch Ungeimpfte zum Weitergeben, die Ansteckungsketten reißen ab.", "Geimpfte geben ihre Antikörper an Ungeimpfte weiter.", "Ungeimpfte werden durch die Impfung der anderen selbst immun.", "Erreger sterben aus, sobald eine Person geimpft ist."], a: 0,
    e: "Das nennt man Herdenschutz. Der Schutz hält nur, solange genug Menschen geimpft sind." },
  { id: "g2-n3", modul: "infektion", art: "bewerten", typ: "mc", nurM: true, q: "Ein Patient setzt sein Antibiotikum nach zwei Tagen ab, weil es ihm besser geht. Wie beurteilst du das?", o: ["Das ist ungünstig: Unempfindliche Bakterien können überleben und sich vermehren, es entstehen resistente Bakterien.", "Das ist richtig, denn Antibiotika schaden bei längerer Einnahme immer.", "Das ist richtig, weil die Viren dann nicht stärker werden.", "Das ist egal, denn Resistenz gibt es nur bei Viren."], a: 0,
    e: "Verordnete Antibiotika nimmt man bis zum Ende. Sonst fördert man Resistenz, und das Antibiotikum wirkt später nicht mehr." },

  /* ----- Genussmittel, Drogen und Abhängigkeit ----- */
  { id: "g3-b1", modul: "sucht", art: "begriff", typ: "mc", q: "Was bedeutet Gewöhnung bei einem Suchtmittel?", o: ["Man braucht immer mehr, damit dieselbe Wirkung eintritt.", "Man braucht immer weniger davon.", "Das Mittel wirkt jedes Mal stärker.", "Man vergisst, dass man es genommen hat."], a: 0,
    e: "Der Körper stellt sich um. Deshalb braucht man mehr oder öfter, damit es noch wirkt." },
  { id: "g3-b2", modul: "sucht", art: "begriff", typ: "mc", q: "Welches Beispiel gehört zur stoffungebundenen Sucht?", o: ["Abhängigkeit vom Glücksspiel", "Abhängigkeit von Nikotin", "Abhängigkeit von Alkohol", "Abhängigkeit von Cannabis"], a: 0,
    e: "Bei der stoffungebundenen Sucht ist man von einem Verhalten abhängig, zum Beispiel Glücksspiel, Computerspielen oder Kaufen." },
  { id: "g3-z1", modul: "sucht", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Nikotin macht abhängig.", true], ["Teer setzt sich beim Rauchen in der Lunge ab.", true], ["Kohlenmonoxid verbessert die Versorgung des Bluts mit Sauerstoff.", false], ["Vapes und E-Zigaretten sind völlig harmlos.", false]],
    e: "Nikotin macht abhängig, Teer bleibt in der Lunge, Kohlenmonoxid verdrängt Sauerstoff. Auch Vapes enthalten meist Nikotin." },
  { id: "g3-a1", modul: "sucht", art: "anwendung", typ: "mc", q: "Welche Folge kann eine Sucht im Alltag haben?", o: ["Die Konzentration und die Noten sinken, Freundschaften leiden.", "Man hat auf einmal mehr Zeit für Freunde.", "Man spart viel Geld.", "Man schläft immer besser."], a: 0,
    e: "Sucht verändert das ganze Leben: Schule, Freunde, Familie und Geld sind betroffen." },
  { id: "g3-v1", modul: "sucht", art: "versuch", typ: "mc", q: "Ein Auto fährt mit 10 m/s. Die Tabelle zeigt, wie weit es bei verschiedenen Reaktionszeiten ungebremst rollt. Was zeigt die Messreihe?",
    tabelle: { titel: "Reaktionsweg bei 10 m/s", kopf: ["Reaktionszeit", "Reaktionsweg"], zeilen: [["0,6 s", "6 m"], ["1,2 s", "12 m"], ["1,8 s", "18 m"]] },
    o: ["Je länger die Reaktionszeit ist, desto länger ist der Reaktionsweg.", "Die Reaktionszeit hat keinen Einfluss auf den Reaktionsweg.", "Der Reaktionsweg wird mit der Reaktionszeit kürzer.", "Der Reaktionsweg hängt nur vom Gewicht des Autos ab."], a: 0,
    e: "Reaktionsweg = Geschwindigkeit · Reaktionszeit. Doppelte Reaktionszeit bedeutet doppelten Reaktionsweg. Alkohol verlängert die Reaktionszeit." },
  { id: "g3-d1", modul: "sucht", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt den Reaktionsweg dreier Fahrer bei 10 m/s. Welcher Fahrer hatte die längste Reaktionszeit?",
    diagramm: { art: "saeulen", titel: "Reaktionsweg bei 10 m/s", xTitel: "Fahrer", yTitel: "Reaktionsweg in m", x: ["Fahrer A", "Fahrer B", "Fahrer C"], y: [8, 12, 15], text: "Säulendiagramm: Fahrer A hat einen Reaktionsweg von 8 Metern, Fahrer B von 12 Metern und Fahrer C von 15 Metern." },
    o: ["Fahrer C", "Fahrer A", "Fahrer B", "Alle drei gleich"], a: 0,
    e: "Bei gleicher Geschwindigkeit gehört der längste Reaktionsweg zur längsten Reaktionszeit: 15 m : 10 m/s = 1,5 s." },
  { id: "g3-t1", modul: "sucht", art: "transfer", typ: "offen", q: "Eine Jugendliche (erfunden) ist vor Klassenarbeiten sehr gestresst. Ein Bekannter rät ihr, sich mit einem Suchtmittel zu beruhigen. Erkläre, wie so eine Gewohnheit zur Abhängigkeit werden kann, und nenne zwei bessere Möglichkeiten gegen Stress.",
    m: "Wer Stress mit einem Suchtmittel wegschiebt, wiederholt es, gewöhnt sich daran und braucht immer mehr, bis er nicht mehr aufhören kann. Besser helfen Sport, Freunde, ein Hobby oder ein Gespräch mit einer Vertrauensperson.",
    k: ["wiederhol|gewöhn|immer mehr|aufhören|abhängig", "sport|freunde|hobby|gespräch|gespraech|vertrauens"], min: 2, e: "Gegen Stress und Langeweile helfen Bewegung, Freunde, Hobbys und Gespräche. Ein Suchtmittel verschiebt das Problem nur." },
  { id: "g3-t2", modul: "sucht", art: "transfer", typ: "mc", q: "Mias Freundin gibt immer mehr Geld für ein Handyspiel aus und leiht sich sogar Geld. Was ist der beste erste Schritt für Mia?", o: ["Mit der Freundin in Ruhe sprechen und eine Vertrauensperson einbeziehen.", "Nichts sagen, denn das geht sie nichts an.", "Die Freundin vor der Klasse bloßstellen.", "Der Freundin selbst noch mehr Geld leihen."], a: 0,
    e: "Ein ruhiges Gespräch zeigt, dass man sich sorgt. Eine Vertrauenslehrkraft oder Beratungsstelle kann weiterhelfen." },
  { id: "g3-w1", modul: "sucht", art: "bewerten", typ: "mc", q: "Ein Junge sagt: „Computerspiele können nicht süchtig machen, weil man dabei nichts einnimmt.“ Wie beurteilst du die Aussage?", o: ["Sie ist falsch: Auch ein Verhalten kann zur Abhängigkeit werden.", "Sie ist richtig: Nur Stoffe machen abhängig.", "Sie ist richtig, aber nur bei Kindern.", "Sie ist falsch: Nur Erwachsene werden süchtig."], a: 0,
    e: "Es gibt stoffgebundene und stoffungebundene Sucht. Spielsucht gehört zur zweiten Gruppe." },
  { id: "g3-n1", modul: "sucht", art: "bewerten", typ: "offen", nurM: true, q: "Emmas Eltern wollen ihr das Handy ohne ein Gespräch für immer wegnehmen, weil sie zu viel spielt. Beurteile dieses Vorgehen.",
    m: "Ein Verbot allein bekämpft nur das Verhalten, nicht die Gründe wie Stress, Langeweile oder Rückzug. Besser ist ein ruhiges Gespräch mit gemeinsamen Regeln, eventuell mit einer Vertrauensperson.",
    k: ["gründe|grund|ursache|stress|verhalten", "gespräch|gespraech|regeln|vertrauens"], min: 2, e: "Gespräch und klare Absprachen nehmen den Jugendlichen ernst. Verbote ohne Gespräch zerstören Vertrauen." },
  { id: "g3-n2", modul: "sucht", art: "zusammenhang", typ: "rf", nurM: true, q: "Prüfe die Aussagen zur Abhängigkeit.",
    aussagen: [["Körperliche Abhängigkeit zeigt sich beim Weglassen durch Beschwerden wie Zittern oder Schwitzen.", true], ["Psychische Abhängigkeit bedeutet ein starkes Verlangen im Kopf.", true], ["Beim Entzug gibt es nie Beschwerden.", false], ["Wer abhängig ist, kann jederzeit ohne Hilfe aufhören.", false]],
    e: "Eine Abhängigkeit kann körperlich, psychisch oder beides sein. Gerade das Aufhören gelingt oft nicht allein." },

  /* ----- Schwangerschaft, Verhütung, Verantwortung ----- */
  { id: "g4-b1", modul: "entwicklung", art: "begriff", typ: "mc", q: "Was geschieht beim Eisprung?", o: ["Eine reife Eizelle verlässt den Eierstock und gelangt in den Eileiter.", "Die Gebärmutterschleimhaut wird abgebaut.", "Die Zellkugel setzt sich in der Gebärmutter fest.", "Das Kind wird geboren."], a: 0,
    e: "Der Eisprung liegt etwa in der Mitte des Zyklus. Danach ist die Eizelle nur etwa einen Tag befruchtungsfähig." },
  { id: "g4-b2", modul: "entwicklung", art: "begriff", typ: "mc", q: "Wie heißt das Ungeborene in den ersten etwa zwei Monaten der Schwangerschaft?", o: ["Embryo", "Fetus", "Eizelle", "Spermium"], a: 0,
    e: "In den ersten zwei Monaten werden die Organe angelegt: Embryo. Ab dem 3. Monat heißt das Kind Fetus." },
  { id: "g4-z1", modul: "entwicklung", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Die Befruchtung findet normalerweise im Eileiter statt.", true], ["Das Blut von Mutter und Kind vermischt sich in der Plazenta nicht.", true], ["Die Fruchtblase versorgt das Kind mit Sauerstoff und Nährstoffen.", false], ["Die Einnistung der Zellkugel ist schon nach einem Tag abgeschlossen.", false]],
    e: "Sauerstoff und Nährstoffe kommen über die Plazenta zum Kind. Die Einnistung folgt etwa eine Woche nach der Befruchtung." },
  { id: "g4-a1", modul: "entwicklung", art: "anwendung", typ: "mc", q: "Welche Aufgabe hat das Fruchtwasser in der Fruchtblase?", o: ["Es wirkt wie ein Polster und schützt das Kind vor Stößen.", "Es versorgt das Kind mit Sauerstoff.", "Es verhindert den Eisprung.", "Es öffnet bei der Geburt den Weg nach draußen."], a: 0,
    e: "Das Fruchtwasser federt Stöße ab. Versorgt wird das Kind über Plazenta und Nabelschnur." },
  { id: "g4-v1", modul: "entwicklung", art: "versuch", typ: "mc", q: "Ein Modell zeigt die Zahl der Zellen nach der Befruchtung (siehe Tabelle, Modellwerte). Was erkennst du?",
    tabelle: { titel: "Zellteilungen nach der Befruchtung (Modell)", kopf: ["Schritt", "Zahl der Zellen"], zeilen: [["1", "2"], ["2", "4"], ["3", "8"], ["4", "16"]] },
    o: ["Die Zahl der Zellen verdoppelt sich bei jedem Schritt.", "Es kommen bei jedem Schritt 2 Zellen dazu.", "Die Zellen werden bei jedem Schritt größer.", "Die Zahl der Zellen bleibt gleich."], a: 0,
    e: "Die Zellen teilen sich immer wieder und werden dabei nicht größer, nur zahlreicher." },
  { id: "g4-d1", modul: "entwicklung", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt die Länge eines Kindes vor der Geburt. Wie lang ist das Kind am Ende des 6. Monats etwa?",
    diagramm: { art: "saeulen", titel: "Länge des Kindes vor der Geburt", xTitel: "Zeitpunkt", yTitel: "Länge in cm", x: ["Ende 3. Monat", "Ende 6. Monat", "Ende 9. Monat"], y: [9, 30, 50], text: "Säulendiagramm: Am Ende des 3. Monats ist das Kind etwa 9 cm lang, am Ende des 6. Monats etwa 30 cm und am Ende des 9. Monats etwa 50 cm." },
    o: ["etwa 30 cm", "etwa 9 cm", "etwa 50 cm", "etwa 21 cm"], a: 0,
    e: "Die mittlere Säule gehört zum Ende des 6. Monats und reicht bis etwa 30 cm." },
  { id: "g4-t1", modul: "entwicklung", art: "transfer", typ: "offen", q: "Eine Tante ist schwanger und möchte etwas gegen Kopfschmerzen einnehmen. Was rätst du ihr und warum?",
    m: "Ich rate ihr, vorher die Ärztin, den Arzt oder die Apotheke zu fragen. Manche Medikamente gelangen über die Plazenta zum Kind und können es schädigen.",
    k: ["ärztin|arzt|apotheke|aerzt|frag", "plazenta|kind|schad"], min: 2, e: "Medikamente nimmt man in der Schwangerschaft nur nach Rücksprache mit der Ärztin oder dem Arzt." },
  { id: "g4-t2", modul: "entwicklung", art: "transfer", typ: "mc", q: "Ein Paar sagt über Verhütung: „Wir passen einfach gut auf, das reicht.“ Welche Antwort stimmt?", o: ["Aufpassen ist unsicher, eine Schwangerschaft ist trotzdem möglich.", "Aufpassen ist sicherer als die Pille.", "Aufpassen schützt auch vor Krankheiten.", "Aufpassen wirkt, wenn man es nur selten tut."], a: 0,
    e: "„Aufpassen“ gehört nicht zu den sicheren Methoden. Beratung hilft bei der Wahl einer passenden Verhütung." },
  { id: "g4-w1", modul: "entwicklung", art: "bewerten", typ: "mc", q: "Eine 16-Jährige (erfunden) vermutet, schwanger zu sein, und traut sich nicht, mit den Eltern zu sprechen. Welcher Rat ist am besten begründet?", o: ["Sich an eine Beratungsstelle wenden: Dort wird kostenlos und vertraulich geholfen, eine eigene Entscheidung zu finden.", "Niemandem etwas sagen und abwarten.", "Nur in einem Internetforum nachlesen.", "Warten, bis jemand anderes etwas bemerkt."], a: 0,
    e: "Beratungsstellen helfen kostenlos und vertraulich, auch Jugendlichen ohne Eltern. Es gibt auch das Hilfetelefon „Schwangere in Not“." },
  { id: "g4-n1", modul: "entwicklung", art: "zusammenhang", typ: "mc", nurM: true, q: "Warum kann eine Schwangerschaft schon einige Tage vor dem Eisprung entstehen?", o: ["Spermien können mehrere Tage im Körper der Frau überleben.", "Die Eizelle ist mehrere Wochen befruchtungsfähig.", "Vor dem Eisprung gibt es noch keine Gebärmutterschleimhaut.", "Der Zyklus dauert bei allen genau gleich lang."], a: 0,
    e: "Die Eizelle lebt nur etwa einen Tag, Spermien mehrere Tage. Deshalb gibt es mehrere fruchtbare Tage, und der Eisprung lässt sich nicht sicher vorhersagen." },
  { id: "g4-n2", modul: "entwicklung", art: "bewerten", typ: "offen", nurM: true, q: "Vergleiche Kondom und Pille: Wie wirken sie, und worin unterscheiden sie sich beim Schutz vor Krankheiten?",
    m: "Das Kondom verhindert, dass Spermien zur Eizelle gelangen, und schützt auch vor vielen sexuell übertragbaren Krankheiten. Die Pille verhindert mit Hormonen den Eisprung, schützt aber nicht vor Krankheiten.",
    k: ["kondom|spermien", "pille|hormon|eisprung", "krankheit|schütz"], min: 3, e: "Nur das Kondom schützt zugleich vor einer Schwangerschaft und vor vielen Krankheiten." },

  /* ----- Schall und Gehör ----- */
  { id: "g5-b1", modul: "schall", art: "begriff", typ: "mc", q: "In welcher Einheit misst man die Frequenz eines Tons?", o: ["Hertz (Hz)", "Dezibel (dB)", "Meter pro Sekunde", "Joule"], a: 0,
    e: "1 Hz bedeutet eine Schwingung pro Sekunde. Dezibel misst die Lautstärke." },
  { id: "g5-b2", modul: "schall", art: "begriff", typ: "mc", q: "Welche Aufgabe haben Hammer, Amboss und Steigbügel?", o: ["Sie übertragen die Schwingung des Trommelfells und verstärken sie.", "Sie wandeln Schall in Nervensignale um.", "Sie melden dem Gehirn die Lage des Kopfes.", "Sie fangen den Schall wie ein Trichter auf."], a: 0,
    e: "Die Gehörknöchelchen liegen im Mittelohr. Die Sinneszellen in der Schnecke erzeugen die Nervensignale." },
  { id: "g5-z1", modul: "schall", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Ohne Teilchen gibt es keinen Schall.", true], ["Im luftleeren Raum breitet sich Schall aus.", false], ["Je dichter die Teilchen liegen, desto schneller reicht eine Schwingung weiter.", true], ["In Wasser ist Schall langsamer als in Luft.", false]],
    e: "Schall ist eine Schwingung, die von Teilchen zu Teilchen weitergegeben wird. In Wasser und Stahl ist er schneller als in Luft." },
  { id: "g5-a1", modul: "schall", art: "anwendung", typ: "mc", q: "Auf einer Baustelle ist es dauerhaft sehr laut. Welcher Schutz passt?", o: ["Kapselgehörschutz tragen", "Lauter sprechen", "Ohren mit den Händen zuhalten, wenn es knallt", "Musik über Kopfhörer hören"], a: 0,
    e: "Gehörschutz senkt die Lautstärke am Ohr. Zusätzliche Musik würde die Belastung erhöhen." },
  { id: "g5-v1", modul: "schall", art: "versuch", typ: "mc", q: "Ein Lineal wird an der Tischkante angeschlagen. Die Tabelle zeigt die Messwerte. Was zeigt die Messreihe?",
    tabelle: { titel: "Lineal an der Tischkante", kopf: ["Überstehende Länge", "Schwingungen pro Sekunde"], zeilen: [["25 cm", "9"], ["15 cm", "25"], ["8 cm", "60"]] },
    o: ["Je kürzer das überstehende Stück, desto höher die Frequenz und desto höher der Ton.", "Je kürzer das überstehende Stück, desto tiefer der Ton.", "Die Länge hat keinen Einfluss auf die Frequenz.", "Je kürzer das Stück, desto langsamer die Schwingung."], a: 0,
    e: "Kurze Stücke schwingen schneller. Mehr Schwingungen in einer Sekunde ergeben einen höheren Ton." },
  { id: "g5-d1", modul: "schall", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt die Lautstärke einiger Geräuschquellen. Welche Quellen liegen über der Grenze von 85 dB, ab der Lärm auf Dauer schadet?",
    diagramm: { art: "saeulen", titel: "Lautstärke einiger Geräuschquellen", xTitel: "Geräuschquelle", yTitel: "Lautstärke in dB", x: ["Flüstern", "Straßenverkehr", "Rasenmäher", "Disco"], y: [30, 80, 90, 105], text: "Säulendiagramm: Flüstern hat etwa 30 dB, Straßenverkehr 80 dB, ein Rasenmäher 90 dB und eine Disco 105 dB." },
    o: ["Rasenmäher und Disco", "nur die Disco", "Straßenverkehr und Rasenmäher", "alle vier"], a: 0,
    e: "Über 85 dB liegen der Rasenmäher (90 dB) und die Disco (105 dB). Der Straßenverkehr liegt mit 80 dB knapp darunter." },
  { id: "g5-r1", modul: "schall", art: "rechnen", typ: "zahl", q: "Du siehst einen Blitz und hörst den Donner 6 Sekunden später. Schall legt in Luft etwa 340 m pro Sekunde zurück. Wie weit ist das Gewitter etwa entfernt?", loesung: 2040, toleranz: 0, einheit: "m",
    weg: "Das Licht ist praktisch sofort da. Entfernung = 340 m/s · 6 s = 2040 m.", e: "Weg = Geschwindigkeit · Zeit." },
  { id: "g5-t1", modul: "schall", art: "transfer", typ: "offen", q: "Bei einem Gewitter siehst du zuerst den Blitz und hörst erst später den Donner. Erkläre, warum.",
    m: "Das Licht des Blitzes ist praktisch sofort da. Der Schall legt in der Luft nur etwa 340 m in jeder Sekunde zurück und kommt deshalb später an.",
    k: ["licht|blitz", "340|langsam|später|spaeter|zeit"], min: 2, e: "Schall ist viel langsamer als Licht. Je weiter das Gewitter weg ist, desto größer ist der Abstand zwischen Blitz und Donner." },
  { id: "g5-t2", modul: "schall", art: "transfer", typ: "mc", q: "Welche Gewohnheit schützt das Gehör beim Musikhören am besten?", o: ["Die Lautstärke begrenzen und Hörpausen einlegen.", "Die Musik immer lauter drehen.", "Nur nachts mit Kopfhörern hören.", "Den Gehörgang jeden Tag reinigen."], a: 0,
    e: "Sehr laute oder lange Geräusche schädigen die Sinneszellen in der Schnecke. Leiser hören und Pausen schützen sie." },
  { id: "g5-w1", modul: "schall", art: "bewerten", typ: "mc", q: "Eine Schülerin sagt: „Nach einem lauten Konzert macht mein Gehör einfach Pause und wächst wieder nach. Lärm ist mir egal.“ Wie beurteilst du das?", o: ["Das ist falsch: Zerstörte Sinneszellen in der Schnecke wachsen nicht nach, der Schaden bleibt.", "Das ist richtig: Das Gehör erneuert sich immer vollständig.", "Das ist richtig, aber nur bei Kindern.", "Das ist richtig: Nur das Trommelfell kann geschädigt werden."], a: 0,
    e: "Lärmschäden an den Sinneszellen sind bleibend. Deshalb ist Vorbeugen so wichtig." },
  { id: "g5-n1", modul: "schall", art: "diagramm", typ: "mc", nurM: true, q: "Zwei Töne A und B werden im selben Zeitausschnitt gezeigt. Im Schwingungsbild von B sind gleich viele Wellen zu sehen wie bei A, aber die Wellen sind höher. Wie klingt B im Vergleich zu A?", o: ["gleich hoch, aber lauter", "höher und gleich laut", "tiefer und gleich laut", "gleich hoch, aber leiser"], a: 0,
    e: "Gleich viele Wellen bedeuten gleiche Frequenz und damit gleiche Tonhöhe. Eine größere Amplitude bedeutet einen lauteren Ton." },
  { id: "g5-n2", modul: "schall", art: "rechnen", typ: "zahl", nurM: true, q: "Im Schwingungsbild eines Tons zählst du 5 Schwingungen in 0,02 Sekunden. Welche Frequenz hat der Ton?", loesung: 250, toleranz: 0, einheit: "Hz",
    weg: "f = Anzahl : Zeit = 5 : 0,02 s = 250 Schwingungen pro Sekunde = 250 Hz.", e: "Die Frequenz ist die Zahl der Schwingungen pro Sekunde." }
]);
