/* Probe-Vorbereitung zu Probe 1 „Magnetismus und Induktion“ (NT 8): Übungsaufgaben – nicht die Aufgaben der Probe.
 * Kennungen (id) nie neu vergeben; nurM: true = nur M8. Aufbau der Aufgaben: siehe vorbereitung.js. */
NT8Vorbereitung.pool("magnet", [
  /* ----- Der Elektromagnet ----- */
  { id: "m2-b1", modul: "elektromagnet", art: "begriff", typ: "mc", q: "Woraus besteht ein Elektromagnet?", o: ["aus einer Spule mit Strom, meist mit Eisenkern", "aus zwei zusammengeklebten Dauermagneten", "aus einem Stück Kupfer ohne Strom", "aus einer Batterie und einem Holzstab"], a: 0,
    e: "Eine Spule, durch die Strom fließt, hat ein Magnetfeld. Ein Eisenkern verstärkt es." },
  { id: "m2-z1", modul: "elektromagnet", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Je mehr Windungen die Spule hat, desto stärker ist der Elektromagnet.", true], ["Ohne Strom bleibt ein Elektromagnet magnetisch.", false], ["Eine größere Stromstärke macht das Magnetfeld schwächer.", false], ["Ein Eisenkern verstärkt das Magnetfeld.", true]],
    e: "Stärker wird der Elektromagnet durch mehr Windungen, größere Stromstärke und einen Eisenkern. Ohne Strom gibt es kein Magnetfeld." },
  { id: "m2-v1", modul: "elektromagnet", art: "versuch", typ: "mc", q: "Sieh dir den Versuch an. Was wurde zwischen den beiden Durchgängen verändert?",
    labor: { art: "elektromagnet", modus: "film", start: { an: true, n: 200, i: 2, kern: false },
      schritte: [{ z: { an: true, n: 200, i: 2, kern: false }, t: "Durchgang 1: Wie viele Büroklammern hängen am Elektromagneten?", ms: 3200 }, { z: { an: true, n: 200, i: 2, kern: true }, t: "Durchgang 2: Jetzt sind es deutlich mehr.", ms: 3200 }] },
    o: ["Ein Eisenkern wurde in die Spule gesteckt.", "Die Stromstärke wurde verkleinert.", "Die Spule bekam weniger Windungen.", "Der Strom wurde ausgeschaltet."], a: 0,
    e: "Windungszahl und Stromstärke sind gleich geblieben. Der Eisenkern hat das Magnetfeld verstärkt." },
  { id: "m2-d1", modul: "elektromagnet", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt eine Messreihe (mit Eisenkern, immer 100 Windungen). Welche Aussage passt?",
    diagramm: { art: "saeulen", titel: "Elektromagnet: Stromstärke und Büroklammern", xTitel: "Stromstärke", yTitel: "Büroklammern", x: ["1 A", "2 A", "3 A"], y: [1, 2, 3], text: "Säulendiagramm: bei 1 A eine Büroklammer, bei 2 A zwei, bei 3 A drei." },
    o: ["Je größer die Stromstärke, desto mehr Büroklammern hält der Elektromagnet.", "Die Stromstärke hat keinen Einfluss.", "Je größer die Stromstärke, desto weniger Büroklammern hält er.", "Bei 2 A hält er die meisten Büroklammern."], a: 0,
    e: "Die Säulen werden mit der Stromstärke höher: Mehr Stromstärke bedeutet ein stärkeres Magnetfeld." },
  { id: "m2-r1", modul: "elektromagnet", art: "rechnen", typ: "zahl", q: "Ein Elektromagnet hält mit 150 Windungen 3 Büroklammern. Wie viele hält er etwa mit 300 Windungen (alles andere bleibt gleich)?", loesung: 6, toleranz: 0, einheit: "Büroklammern",
    weg: "300 Windungen sind doppelt so viele wie 150 – also etwa doppelt so viele Büroklammern: 2 · 3 = 6.", e: "Doppelte Windungszahl, etwa doppelte Wirkung." },
  { id: "m2-a1", modul: "elektromagnet", art: "anwendung", typ: "mc", q: "Warum nimmt man an der Haustür einen Elektromagneten für den Türöffner und keinen Dauermagneten?", o: ["Der Riegel soll nur zurückgezogen werden, solange jemand den Knopf drückt.", "Ein Dauermagnet wäre zu schwer für die Tür.", "Ein Elektromagnet braucht keine Energie.", "Dauermagnete ziehen kein Eisen an."], a: 0,
    e: "Ein Elektromagnet lässt sich ein- und ausschalten – genau das braucht ein Türöffner." },
  { id: "m2-t1", modul: "elektromagnet", art: "transfer", typ: "offen", q: "Ein Sortierband im Recyclinghof soll mit einem Elektromagneten Eisendosen aus dem Müll ziehen und über einem Container fallen lassen. Erkläre, wie das funktioniert.",
    m: "Über dem Band ist der Strom eingeschaltet: Der Elektromagnet zieht die Eisendosen an. Über dem Container wird der Strom ausgeschaltet, das Magnetfeld verschwindet und die Dosen fallen hinein.",
    k: ["strom", "an|eingeschaltet|einschalt|fließt", "aus|abgeschaltet|abschalt|ausschalt", "fallen|fällt|loslassen|lässt los"], min: 3, e: "Mit Strom hält er fest, ohne Strom lässt er los." },
  { id: "m2-t2", modul: "elektromagnet", art: "transfer", typ: "mc", nurM: true, q: "Zwei Gruppen vergleichen ihre Elektromagnete. Gruppe A: 200 Windungen, 1 A, mit Kern. Gruppe B: 200 Windungen, 3 A, mit Kern. Gruppe B hält mehr Büroklammern. Was darf man daraus schließen?",
    o: ["Die größere Stromstärke macht den Elektromagneten stärker – nur sie war verschieden.", "Mehr Windungen machen ihn stärker.", "Der Eisenkern von Gruppe B ist besser.", "Man kann nichts schließen, weil zwei Dinge verändert wurden."], a: 0,
    e: "Windungszahl und Kern sind gleich, nur die Stromstärke unterscheidet sich – ein fairer Vergleich." },
  { id: "m2-n1", modul: "elektromagnet", art: "anwendung", typ: "mc", nurM: true, q: "Ein Relais schaltet mit einem schwachen Strom einen starken Strom. Was bewegt dabei den Schalter im zweiten Stromkreis?", o: ["der Anker, den der Elektromagnet anzieht", "eine Feder ganz allein", "der starke Strom selbst", "ein Dauermagnet in der Spule"], a: 0,
    e: "Der kleine Strom im Steuerstromkreis macht die Spule zum Elektromagneten. Er zieht den Anker an, und der Anker schließt den Schalter im zweiten, getrennten Stromkreis." },

  /* ----- Magnete: Pole, Kräfte und Felder ----- */
  { id: "m1-b1", modul: "magnetismus", art: "begriff", typ: "mc", q: "Welches Material wird von einem Magneten nicht angezogen?", o: ["Aluminium", "Nickel", "Cobalt", "Stahl"], a: 0,
    e: "Ein Magnet zieht Eisen, Nickel, Cobalt und Stahl an (Stahl enthält viel Eisen). Aluminium ist ein Metall, wird aber nicht angezogen." },
  { id: "m1-b2", modul: "magnetismus", art: "begriff", typ: "mc", q: "Was bedeutet der Begriff „Pol“ bei einem Magneten?", o: ["eine der beiden Stellen, an denen die Magnetkraft am größten ist", "die Mitte des Magneten", "die Farbe des Magneten", "der Stoff, aus dem der Magnet besteht"], a: 0,
    e: "Jeder Magnet hat zwei Pole, Nordpol und Südpol. Dort ist die Kraft am größten." },
  { id: "m1-z1", modul: "magnetismus", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Zwei Nordpole stoßen sich ab.", true], ["Ein Nordpol und ein Südpol ziehen sich an.", true], ["Die Magnetkraft wirkt nur, wenn sich die Magnete berühren.", false], ["Ein Magnet zieht Kupfer an.", false], ["Zwei Südpole ziehen sich an.", false]],
    e: "Gleichnamige Pole stoßen sich ab, ungleichnamige ziehen sich an. Die Kraft wirkt auch ohne Berührung. Kupfer wird nicht angezogen." },
  { id: "m1-v1", modul: "magnetismus", art: "versuch", typ: "mc", q: "Du hängst einen Stabmagneten an einem langen Faden auf. Er dreht sich und bleibt stehen, das rote Ende zeigt nach Norden. Was hast du damit nachgebaut?",
    o: ["einen einfachen Kompass", "einen Elektromagneten", "einen Generator", "einen Stromwender"], a: 0,
    e: "Ein frei drehbarer Magnet richtet sich im Magnetfeld der Erde aus – genau das macht die Nadel im Kompass." },
  { id: "m1-d1", modul: "magnetismus", art: "diagramm", typ: "mc", q: "Ein Stabmagnet wurde in einen Haufen Büroklammern gelegt. Das Diagramm zeigt, wie viele Büroklammern an drei Stellen hängen. Was folgt daraus?",
    diagramm: { art: "saeulen", titel: "Büroklammern am Stabmagneten", xTitel: "Stelle am Magneten", yTitel: "Büroklammern", x: ["linkes Ende", "Mitte", "rechtes Ende"], y: [9, 1, 9], text: "Säulendiagramm: Am linken Ende hängen 9 Büroklammern, in der Mitte 1 und am rechten Ende 9." },
    o: ["An den Polen ist die Magnetkraft am größten.", "In der Mitte ist die Magnetkraft am größten.", "Die Magnetkraft ist überall gleich groß.", "Büroklammern hängen nur am Nordpol."], a: 0,
    e: "An den Enden, den Polen, hängen die meisten Büroklammern. Dort ist das Magnetfeld am stärksten." },
  { id: "m1-a1", modul: "magnetismus", art: "anwendung", typ: "mc", q: "Ein Magnet soll Stahlschrauben von Kunststoffteilen trennen. Warum klappt das?", o: ["Er zieht Stahl an, Kunststoff nicht.", "Er zieht alle festen Stoffe an.", "Er schmilzt die Schrauben.", "Er zieht Kunststoff stärker an als Stahl."], a: 0,
    e: "Stahl enthält Eisen und wird angezogen. Kunststoff wird nicht angezogen und bleibt liegen." },
  { id: "m1-t1", modul: "magnetismus", art: "transfer", typ: "mc", q: "Du hältst nacheinander die beiden Enden eines Eisenstabs an den Nordpol eines Magneten. Ein Ende wird angezogen, das andere abgestoßen. Was weißt du über den Stab?",
    o: ["Er ist selbst ein Magnet.", "Er ist ein unmagnetisches Eisenstück.", "Er besteht aus Aluminium.", "Er hat nur einen Pol."], a: 0,
    e: "Abstoßen gibt es nur zwischen zwei Magneten (gleichnamige Pole). Ein unmagnetisches Eisenstück würde an beiden Enden nur angezogen." },
  { id: "m1-t2", modul: "magnetismus", art: "transfer", typ: "offen", q: "Auf einer Baustelle sollen verlorene Stahlnägel aus dem Sand eingesammelt werden. Beschreibe, wie du dafür einen Magneten einsetzt, und erkläre, warum der Sand liegen bleibt.",
    m: "Ich ziehe den Magneten dicht über den Sand. Er zieht die Stahlnägel an, weil Stahl Eisen enthält. Sand ist nicht magnetisch, deshalb wird er nicht angezogen und bleibt liegen.",
    k: ["magnet", "stahl|eisen|nägel", "nicht angezogen|nicht magnetisch|bleibt liegen|kein eisen"], min: 3, e: "Ein Magnet zieht nur Eisen, Nickel, Cobalt und Stahl an." },
  { id: "m1-n1", modul: "magnetismus", art: "anwendung", typ: "mc", nurM: true, q: "Ein Stabmagnet liegt mit dem Nordpol rechts vor dir. Oberhalb des Magneten liegt eine Kompassnadel auf einer Feldlinie. Wohin zeigt ihr Nordpol?",
    o: ["nach links, zum Südpol des Magneten", "nach rechts, zum Nordpol des Magneten", "senkrecht nach oben", "senkrecht nach unten"], a: 0,
    e: "Außerhalb des Magneten laufen die Feldlinien vom Nordpol zum Südpol, hier also nach links. Der Nordpol der Nadel zeigt in Richtung der Feldlinie." },
  { id: "m1-n2", modul: "magnetismus", art: "zusammenhang", typ: "rf", nurM: true, q: "Prüfe die Aussagen zu Feldlinien und zum Modell der Elementarmagnete.",
    aussagen: [["Feldlinien können sich nicht schneiden.", true], ["Ein Nagel ist magnetisch, wenn seine Elementarmagnete ungeordnet liegen.", false], ["Mit dem Modell der Elementarmagnete erklärt man, wie ein Magnet entmagnetisiert wird.", true], ["Die Erde wirkt wie ein riesiger Stabmagnet.", true]],
    e: "An jedem Ort gibt es nur eine Feldrichtung. Ungeordnete Elementarmagnete heben ihre Wirkung auf." },

  /* ----- Elektromotor ----- */
  { id: "m3-b1", modul: "elektromotor", art: "begriff", typ: "mc", q: "Aus welchen Teilen besteht ein einfacher Gleichstrommotor?", o: ["Magnet, Spule, Stromwender und Kontakte", "Spule, Kondensator, Lampe und Schalter", "zwei Magnete und ein Eisenkern", "Batterie, Lampe und Kabel"], a: 0,
    e: "Der Magnet steht fest. Die Spule dreht sich auf der Achse. Der Stromwender und die Kontakte bringen den Strom in die Spule." },
  { id: "m3-z1", modul: "elektromotor", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Es geht um die Leiterschaukel.",
    aussagen: [["Ohne Strom schlägt der Draht nicht aus.", true], ["Kehrt man die Stromrichtung um, schlägt der Draht zur anderen Seite aus.", true], ["Der Draht schlägt auch ohne Magnet aus.", false], ["Kehrt man Stromrichtung und Magnetfeld gleichzeitig um, schlägt der Draht zur anderen Seite aus.", false]],
    e: "Die Kraft entsteht nur durch Strom im Magnetfeld. Eine einzelne Umkehrung wechselt die Seite, zwei Umkehrungen heben sich auf." },
  { id: "m3-v1", modul: "elektromotor", art: "versuch", typ: "mc", q: "Bei der Leiterschaukel schlägt der Draht nach rechts aus. Du vertauschst die Pole des Hufeisenmagneten, die Stromrichtung bleibt gleich. Was beobachtest du?",
    o: ["Der Draht schlägt nach links aus.", "Der Draht schlägt wieder nach rechts aus.", "Der Draht bleibt in Ruhe.", "Der Draht glüht auf."], a: 0,
    e: "Kehrt man nur das Magnetfeld um, wechselt die Kraft die Richtung – der Draht schlägt zur anderen Seite aus." },
  { id: "m3-d1", modul: "elektromotor", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt, wie weit eine Leiterschaukel bei verschiedenen Stromstärken ausschlägt. Welche Aussage passt?",
    diagramm: { art: "saeulen", titel: "Ausschlag der Leiterschaukel", xTitel: "Stromstärke", yTitel: "Ausschlag in cm", x: ["1 A", "2 A", "3 A"], y: [2, 4, 6], text: "Säulendiagramm: Bei 1 A schlägt der Draht 2 cm aus, bei 2 A 4 cm und bei 3 A 6 cm." },
    o: ["Je größer die Stromstärke, desto größer der Ausschlag.", "Der Ausschlag hängt nicht von der Stromstärke ab.", "Bei 3 A schlägt der Draht am wenigsten aus.", "Mit zunehmender Stromstärke wird der Ausschlag kleiner."], a: 0,
    e: "Die Säulen werden höher: Eine größere Stromstärke bedeutet eine größere Kraft auf den Draht." },
  { id: "m3-a1", modul: "elektromotor", art: "anwendung", typ: "mc", q: "Welche Energieumwandlung findet in einem laufenden Mixer hauptsächlich statt?", o: ["elektrische Energie → Bewegungsenergie (und etwas Wärme)", "Bewegungsenergie → elektrische Energie", "Wärme → Bewegungsenergie", "Licht → elektrische Energie"], a: 0,
    e: "Der Elektromotor nimmt elektrische Energie auf und gibt Bewegungsenergie ab. Ein kleiner Teil wird zu Wärme." },
  { id: "m3-t1", modul: "elektromotor", art: "transfer", typ: "offen", q: "Ein Spielzeugauto mit Elektromotor fährt vorwärts. Du drehst die Batterie im Fach um. Was geschieht, und warum?",
    m: "Das Auto fährt rückwärts. Die Stromrichtung im Motor ist umgekehrt, deshalb zeigt die Kraft auf die Spule in die andere Richtung und der Motor dreht sich andersherum.",
    k: ["rückwärts|andersherum|andere richtung|gegenrichtung", "stromrichtung|umgekehrt|umgepolt|batterie umgedreht", "kraft|dreht|spule"], min: 2, e: "Wie bei der Leiterschaukel: Kehrt man die Stromrichtung um, wechselt die Kraft die Richtung." },
  { id: "m3-t2", modul: "elektromotor", art: "transfer", typ: "mc", q: "Ein Tischventilator ist lange gelaufen. Sein Gehäuse fühlt sich warm an. Wie lässt sich das erklären?", o: ["Ein Teil der elektrischen Energie wird im Motor zu Wärme.", "Der Magnet im Motor erzeugt Wärme von selbst.", "Der Stromwender kühlt den Motor.", "Der Ventilator wandelt Wärme in Bewegung um."], a: 0,
    e: "Kein Motor arbeitet verlustfrei: Neben der Bewegungsenergie entsteht immer auch etwas Wärme." },
  { id: "m3-n1", modul: "elektromotor", art: "anwendung", typ: "mc", nurM: true, q: "Linke Hand, Drei-Finger-Regel: Daumen = Bewegungsrichtung der Elektronen, Zeigefinger = Magnetfeld. In der Zeichenebene bewegen sich die Elektronen nach unten, das Magnetfeld zeigt auf dich zu. Wohin zeigt die Kraft (Mittelfinger)?",
    o: ["nach rechts", "nach links", "nach oben", "in die Zeichenebene hinein"], a: 0,
    e: "Kraft, Strom und Feld stehen paarweise senkrecht aufeinander. Daumen nach unten (Elektronen), Zeigefinger zu dir: Der Mittelfinger der linken Hand zeigt nach rechts." },
  { id: "m3-n2", modul: "elektromotor", art: "begriff", typ: "mc", nurM: true, q: "Welcher Teil eines Elektromotors heißt Stator?", o: ["der feststehende Teil", "der drehbare Teil", "der Stromwender", "die Achse"], a: 0,
    e: "Der Stator (Ständer) steht fest (hier der Magnet), der Rotor (Läufer) dreht sich, der Kommutator (Polwender) ist der Stromwender." },

  /* ----- Induktion ----- */
  { id: "m4-b1", modul: "induktion", art: "begriff", typ: "mc", q: "Wie heißt die Spannung, die in einer Spule durch ein sich änderndes Magnetfeld entsteht?", o: ["Induktionsspannung", "Netzspannung", "Gleichspannung der Batterie", "Reibungsspannung"], a: 0,
    e: "Das Entstehen einer Spannung durch ein sich änderndes Magnetfeld nennt man Induktion." },
  { id: "m4-z1", modul: "induktion", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Ein Magnet, der still in der Spule liegt, erzeugt keine Spannung.", true], ["Je mehr Windungen die Spule hat, desto kleiner ist die Induktionsspannung.", false], ["Wird die Spule über einen ruhenden Magneten geschoben, entsteht ebenfalls Spannung.", true], ["Beim Herausziehen schlägt der Zeiger zur selben Seite aus wie beim Hineinschieben.", false]],
    e: "Entscheidend ist die Änderung des Magnetfelds in der Spule. Mehr Windungen geben mehr Spannung, und Hinein und Heraus sind entgegengesetzte Bewegungen." },
  { id: "m4-v1", modul: "induktion", art: "versuch", typ: "mc", q: "Sieh dir den Versuch an. Worin unterscheiden sich die beiden Durchgänge?",
    labor: { art: "induktion", modus: "film", start: { n: 300, tempo: "langsam" }, text: "Ein Magnet wird zweimal gleich langsam in eine Spule geschoben. Beim zweiten Durchgang ist die Spule gewechselt.",
      schritte: [{ tu: "rein", t: "Durchgang 1: Der Magnet wird in die Spule geschoben.", ms: 3800 }, { tu: { n: 1200 }, t: "Die Spule wird gewechselt.", ms: 1500 }, { tu: "rein", t: "Durchgang 2: Der Magnet wird in die Spule geschoben.", ms: 3800 }] },
    o: ["Die Spule hat beim zweiten Durchgang mehr Windungen.", "Der Magnet wird beim zweiten Durchgang schneller bewegt.", "Der Magnet ist beim zweiten Durchgang umgedreht.", "Beim zweiten Durchgang ruht der Magnet."], a: 0,
    e: "Das Tempo und der Magnet bleiben gleich. Nur die Windungszahl ist größer – und damit der Ausschlag." },
  { id: "m4-d1", modul: "induktion", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt den Ausschlag eines Spannungsmessers bei verschiedenen Spulen (gleicher Magnet, gleiches Tempo). Welche Aussage passt?",
    diagramm: { art: "saeulen", titel: "Ausschlag bei verschiedenen Spulen", xTitel: "Windungen", yTitel: "Ausschlag (Skalenteile)", x: ["250", "500", "750"], y: [5, 10, 15], text: "Säulendiagramm: Bei 250 Windungen beträgt der Ausschlag 5 Skalenteile, bei 500 Windungen 10 und bei 750 Windungen 15." },
    o: ["Je mehr Windungen, desto größer der Ausschlag.", "Je mehr Windungen, desto kleiner der Ausschlag.", "Die Windungszahl hat keinen Einfluss.", "Bei 500 Windungen ist der Ausschlag am größten."], a: 0,
    e: "Die Säulen wachsen mit der Windungszahl: Jede Windung trägt zur Spannung bei." },
  { id: "m4-r1", modul: "induktion", art: "rechnen", typ: "zahl", q: "Bei 400 Windungen misst du einen Ausschlag von 8 Skalenteilen (gleicher Magnet, gleiches Tempo). Wie groß ist der Ausschlag bei 1000 Windungen?", loesung: 20, toleranz: 0, einheit: "Skalenteile",
    weg: "1000 Windungen sind das 2,5-Fache von 400 Windungen. Also ist der Ausschlag 2,5 · 8 = 20 Skalenteile.", e: "Der Ausschlag wächst im gleichen Verhältnis wie die Windungszahl." },
  { id: "m4-a1", modul: "induktion", art: "anwendung", typ: "mc", q: "Warum wird das Licht am Fahrraddynamo heller, wenn man schneller fährt?", o: ["Der Magnet dreht sich schneller, das Feld ändert sich schneller und die Spannung wird größer.", "Die Spule bekommt dabei mehr Windungen.", "Der Dynamo lädt eine Batterie auf.", "Der Magnet im Dynamo wird stärker."], a: 0,
    e: "Je schneller sich das Magnetfeld in der Spule ändert, desto größer ist die Induktionsspannung." },
  { id: "m4-t1", modul: "induktion", art: "transfer", typ: "offen", q: "Eine Spule ist an einen Spannungsmesser angeschlossen. Ein Kind lässt einen Stabmagneten durch ein Kunststoffrohr fallen, das die Spule umschließt. Beschreibe, was der Zeiger zeigt, und erkläre es.",
    m: "Der Zeiger schlägt kurz aus, solange der Magnet durch die Spule fällt, weil sich dabei das Magnetfeld in der Spule ändert. Ist der Magnet hindurch, ändert sich nichts mehr und der Zeiger steht wieder auf 0.",
    k: ["zeiger|ausschlag|spannung", "magnetfeld|ändert|bewegung|fällt", "0|wieder|zurück|nach"], min: 2, e: "Spannung entsteht nur, solange sich das Magnetfeld in der Spule ändert." },
  { id: "m4-n1", modul: "induktion", art: "anwendung", typ: "mc", nurM: true, q: "Ein Handy wird kabellos geladen. Welche Bedingung ist dafür entscheidend, dass in der Handyspule Spannung entsteht?",
    o: ["Das Magnetfeld der Ladespule ändert sich ständig.", "Das Handy bewegt sich in der Ladeschale.", "In der Ladeplatte dreht sich ein Magnet.", "Das Magnetfeld der Ladespule ist konstant."], a: 0,
    e: "Die Ladespule führt wechselnden Strom, ihr Magnetfeld ändert sich dauernd. Dadurch wird in der Handyspule Spannung induziert." },
  { id: "m4-n2", modul: "induktion", art: "zusammenhang", typ: "offen", nurM: true, q: "Ein Magnet fällt durch zwei gleiche Spulen. Bei der unteren Spule schlägt der Zeiger doppelt so weit aus. Nenne zwei mögliche Ursachen.",
    m: "Die untere Spule könnte doppelt so viele Windungen haben. Oder der Magnet fällt dort schneller, weil er beim Fallen schneller wird, und das Magnetfeld ändert sich schneller.",
    k: ["windung", "schneller|tempo|geschwindigkeit"], min: 2, e: "Die Induktionsspannung wächst mit der Windungszahl und mit dem Tempo, mit dem sich das Magnetfeld ändert." },

  /* ----- Generator, Wechselspannung und Transformator ----- */
  { id: "m5-b1", modul: "generator-trafo", art: "begriff", typ: "mc", q: "Wie heißt die Spule eines Transformators, an die die Wechselspannung angeschlossen wird?", o: ["Primärspule", "Sekundärspule", "Kernspule", "Ladespule"], a: 0,
    e: "Primär heißt „erste“: Hier geht die Spannung hinein. Aus der Sekundärspule kommt die neue Spannung heraus." },
  { id: "m5-z1", modul: "generator-trafo", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Ein Transformator braucht Wechselspannung.", true], ["Die Netzspannung hat eine Frequenz von 50 Hz.", true], ["Ein Generator gibt Spannung ab, auch wenn er still steht.", false], ["Bei Gleichspannung schwingen die Elektronen im Draht hin und her.", false]],
    e: "Nur eine Wechselspannung ändert das Magnetfeld im Kern ständig. Ein Generator liefert nur Spannung, solange er gedreht wird." },
  { id: "m5-v1", modul: "generator-trafo", art: "versuch", typ: "mc", q: "Sieh dir den Versuch an. Was zeigt der Spannungsmesser an der Sekundärspule nach der Umstellung im letzten Schritt?",
    labor: { art: "trafo", modus: "film", start: { u1: 12, n1: 200, n2: 400, art: "wechsel", kern: true }, text: "Ein Transformator mit N₁ = 200 und N₂ = 400 liegt an 12 V Wechselspannung. Im letzten Schritt wird die Spannungsquelle auf Gleichspannung umgestellt.",
      schritte: [{ z: {}, t: "Zuerst liegt Wechselspannung an: N₁ = 200, N₂ = 400.", ms: 2800 }, { z: { art: "gleich" }, t: "Jetzt wird die Spannungsquelle umgestellt.", ms: 3000 }] },
    o: ["0 V – bei Gleichspannung entsteht an der Sekundärspule keine Spannung.", "24 V wie zuvor", "12 V", "6 V"], a: 0,
    e: "Bei Gleichspannung ändert sich das Magnetfeld im Kern nicht. Ohne Änderung gibt es keine Induktion." },
  { id: "m5-d1", modul: "generator-trafo", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt die Spannung U₂ eines Transformators mit N₁ = 200 und U₁ = 10 V für verschiedene Windungszahlen N₂. Welche Aussage stimmt?",
    diagramm: { art: "saeulen", titel: "Sekundärspannung bei N₁ = 200, U₁ = 10 V", xTitel: "Windungen N₂", yTitel: "U₂ in V", x: ["100", "200", "400"], y: [5, 10, 20], text: "Säulendiagramm: Bei N₂ = 100 beträgt U₂ 5 V, bei N₂ = 200 sind es 10 V und bei N₂ = 400 sind es 20 V." },
    o: ["Je mehr Windungen die Sekundärspule hat, desto größer ist U₂.", "U₂ hängt nicht von N₂ ab.", "Bei 100 Windungen ist U₂ am größten.", "U₂ ist immer gleich U₁."], a: 0,
    e: "U₂ wächst im gleichen Verhältnis wie N₂. Bei N₂ = N₁ ist U₂ gleich U₁." },
  { id: "m5-r1", modul: "generator-trafo", art: "rechnen", typ: "zahl", q: "Ein Transformator ohne angeschlossenes Gerät hat N₁ = 900 und N₂ = 300 Windungen. An der Primärspule liegen U₁ = 60 V. Wie groß ist U₂?", loesung: 20, toleranz: 0, einheit: "V",
    weg: "900 : 300 = 3. Die Primärseite hat dreimal so viele Windungen, also ist U₂ = 60 V : 3 = 20 V.", e: "U₁ : U₂ = N₁ : N₂ – die Spannung ändert sich um den Faktor der Windungen." },
  { id: "m5-r2", modul: "generator-trafo", art: "rechnen", typ: "zahl", q: "Ein Netzteil soll aus 230 V genau 23 V machen. Die Sekundärspule hat 150 Windungen. Wie viele Windungen braucht die Primärspule?", loesung: 1500, toleranz: 0, einheit: "Windungen",
    weg: "230 V : 23 V = 10. Die Primärspule braucht zehnmal so viele Windungen: 150 · 10 = 1500.", e: "Der Faktor der Spannungen ist auch der Faktor der Windungen." },
  { id: "m5-a1", modul: "generator-trafo", art: "anwendung", typ: "mc", q: "Warum steckt in einem Handy-Ladegerät ein Transformator?", o: ["Er senkt die 230 V der Steckdose auf eine kleine Spannung.", "Er erzeugt Strom aus dem Akku.", "Er wandelt Wechselspannung in Bewegungsenergie um.", "Er speichert elektrische Energie für später."], a: 0,
    e: "Das Handy braucht nur wenige Volt. Die Sekundärspule hat viel weniger Windungen als die Primärspule." },
  { id: "m5-t1", modul: "generator-trafo", art: "transfer", typ: "offen", q: "Ein Windrad treibt einen Generator an. Bei stärkerem Wind dreht es sich schneller. Beschreibe, was sich an der Spannung des Generators ändert, und begründe.",
    m: "Die Spannung wird größer, weil sich das Magnetfeld in der Spule schneller ändert. Außerdem steigt die Frequenz: Es gibt mehr Schwingungen in jeder Sekunde.",
    k: ["spannung|größer", "schneller", "frequenz|schwingung|hz"], min: 2, e: "Je schneller die Drehung, desto größer die Spannung." },
  { id: "m5-t2", modul: "generator-trafo", art: "transfer", typ: "mc", q: "Jemand baut einen Transformator mit offenem Eisenkern. Die Spannung an der Sekundärspule ist viel kleiner als erwartet. Was ist die Ursache?",
    o: ["Das Magnetfeld erreicht die Sekundärspule nur zu einem kleinen Teil.", "Der Eisenkern erzeugt zu viel Spannung.", "Die Frequenz hat sich verdoppelt.", "Die Primärspule hat keine Windungen."], a: 0,
    e: "Der geschlossene Eisenkern führt das wechselnde Magnetfeld fast vollständig durch die Sekundärspule." },
  { id: "m5-n1", modul: "generator-trafo", art: "rechnen", typ: "zahl", nurM: true, q: "Ein idealer Transformator hat N₁ = 300 und N₂ = 1500 Windungen. In der Primärspule fließen 5 A. Wie groß ist die Stromstärke I₂ in der Sekundärspule?", loesung: 1, toleranz: 0, einheit: "A",
    weg: "I₁ : I₂ = N₂ : N₁ = 1500 : 300 = 5. Also ist I₂ = 5 A : 5 = 1 A.", e: "Bei hoher Spannung ist die Stromstärke klein: Die Stromstärken verhalten sich umgekehrt wie die Windungszahlen." },
  { id: "m5-n2", modul: "generator-trafo", art: "rechnen", typ: "zahl", nurM: true, q: "Eine Wechselspannung hat die Periode T = 0,25 s. Wie groß ist die Frequenz f?", loesung: 4, toleranz: 0, einheit: "Hz",
    weg: "f = 1 : T = 1 : 0,25 s = 4 Hz.", e: "Frequenz und Periode gehören zusammen: f = 1 : T." }
]);
