/* Probe-Vorbereitung zu Probe 5 „Säuren, Laugen und Salze“ (NT 8): Übungsaufgaben – nicht die Aufgaben der Probe.
 * Kennungen (id) nie neu vergeben; nurM: true = nur M8. Aufbau der Aufgaben: siehe vorbereitung.js. */
NT8Vorbereitung.pool("saeuren", [
  /* ----- Saure und basische Lösungen im Alltag ----- */
  { id: "s1-b1", modul: "sauer-basisch", art: "begriff", typ: "mc", q: "Wie nennt man eine Lösung, die weder sauer noch basisch ist?", o: ["neutral", "alkalisch", "konzentriert", "ätzend"], a: 0,
    e: "Reines Wasser ist neutral. „Alkalisch“ ist ein anderes Wort für basisch, „konzentriert“ sagt nur, wie viel Stoff gelöst ist." },
  { id: "s1-b2", modul: "sauer-basisch", art: "begriff", typ: "mc", q: "Welches Signalwort auf dem Etikett warnt vor den schwereren Gefahren?", o: ["Gefahr", "Achtung", "Hinweis", "Vorsicht"], a: 0,
    e: "„Gefahr“ steht bei schweren Schäden, „Achtung“ bei weniger schweren." },
  { id: "s1-z1", modul: "sauer-basisch", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Zitronensaft ist eine saure Lösung.", true], ["Seifenlösung ist eine saure Lösung.", false], ["Saure Lösungen lösen Kalk.", true], ["Basische Lösungen fühlen sich seifig an und lösen Fett.", true]],
    e: "Zitronensaft ist sauer und löst Kalk. Seifenlösung ist basisch: Sie fühlt sich seifig an und löst Fett." },
  { id: "s1-a1", modul: "sauer-basisch", art: "anwendung", typ: "mc", q: "In der Dusche hat sich ein weißer Kalkbelag gebildet. Welches Mittel passt am besten?", o: ["ein Entkalker mit Zitronensäure", "eine Seifenlösung", "ein Rohrreiniger", "reines Wasser"], a: 0,
    e: "Kalk wird von sauren Lösungen aufgelöst. Seifenlösung und Rohrreiniger sind basisch, reines Wasser ist neutral." },
  { id: "s1-v1", modul: "sauer-basisch", art: "versuch", typ: "mc", q: "Ein Stück Kreide wird in drei Gläser gelegt. In Haushaltsessig steigen Bläschen auf, in Leitungswasser und in Seifenlösung passiert nichts. Was zeigt der Versuch?", o: ["Essig ist sauer und löst den Kalk der Kreide.", "Essig ist basisch und löst den Kalk.", "Kreide löst sich in jeder Flüssigkeit.", "Leitungswasser und Seifenlösung sind sauer."], a: 0,
    e: "Kreide besteht aus Kalk. Nur die saure Lösung löst ihn, dabei sprudelt es. Wasser (neutral) und Seifenlösung (basisch) lösen ihn nicht." },
  { id: "s1-t1", modul: "sauer-basisch", art: "transfer", typ: "offen", q: "Auf einer Flasche sind der Totenkopf und das Signalwort „Gefahr“ abgebildet. Ein Kind meint: „Ich probiere nur ein winziges bisschen.“ Nimm Stellung.",
    m: "Das ist falsch. Schon kleine Mengen eines solchen Stoffs können tödlich sein. Das Piktogramm warnt genau davor. Chemikalien probiert man nie, auch nicht ein wenig.",
    k: ["klein|wenig|winzig|menge", "tödlich|toedlich|gift|schaden", "nie|nicht|falsch"], min: 2, e: "Der Totenkopf warnt vor Giftstoffen. Chemikalien probiert man nie – auch nicht in kleinen Mengen." },
  { id: "s1-t2", modul: "sauer-basisch", art: "transfer", typ: "mc", q: "Eine Freundin füllt Reste eines Reinigers in eine leere Limonadenflasche. Was ist das Problem?", o: ["Jemand kann die Flasche für Limonade halten und trinken.", "Der Reiniger wird in der Flasche schwächer.", "Die Flasche wird dadurch sauer.", "Es gibt kein Problem, wenn die Flasche leer war."], a: 0,
    e: "Chemikalien gehören nie in Getränkeflaschen: Besonders Kinder können sie mit einem Getränk verwechseln. Reste kommen in die Originalflasche oder zur Schadstoffsammlung." },
  { id: "s1-n1", modul: "sauer-basisch", art: "begriff", typ: "mc", nurM: true, q: "Was ist der Unterschied zwischen H-Sätzen und P-Sätzen auf einem Etikett?", o: ["H-Sätze beschreiben die Gefahr, P-Sätze nennen Schutzmaßnahmen.", "H-Sätze nennen Schutzmaßnahmen, P-Sätze beschreiben die Gefahr.", "H-Sätze gelten nur für Säuren, P-Sätze nur für Laugen.", "H- und P-Sätze geben nur die Füllmenge an."], a: 0,
    e: "H steht für Gefahrenhinweis (was kann passieren?), P für Sicherheitshinweis (was soll ich tun?)." },
  { id: "s1-n2", modul: "sauer-basisch", art: "bewerten", typ: "rf", nurM: true, q: "Prüfe die Aussagen zum Etikett eines Reinigers.",
    aussagen: [["Der Satz „Verursacht schwere Verätzungen der Haut“ ist ein Gefahrenhinweis.", true], ["Der Satz „Schutzhandschuhe tragen“ ist ein Gefahrenhinweis.", false], ["Der Satz „Darf nicht in die Hände von Kindern gelangen“ ist ein Sicherheitshinweis.", true]],
    e: "Gefahrenhinweise (H) beschreiben die Gefahr, Sicherheitshinweise (P) sagen, was man zum Schutz tut." },

  /* ----- Indikatoren und pH-Wert ----- */
  { id: "s2-b1", modul: "ph-wert", art: "begriff", typ: "mc", q: "Was zeigt ein Indikator an?", o: ["ob eine Lösung sauer, neutral oder basisch ist", "wie warm eine Lösung ist", "wie viel Wasser in einer Lösung steckt", "ob eine Lösung giftig ist"], a: 0,
    e: "Ein Indikator ist ein Farbstoff, der je nach Lösung seine Farbe ändert. Giftigkeit zeigt er nicht an." },
  { id: "s2-b2", modul: "ph-wert", art: "begriff", typ: "mc", q: "Welche Farbe hat Blaukrautsaft in einer basischen Lösung?", o: ["blau bis grün", "rot bis rosa", "violett", "farblos"], a: 0,
    e: "Blaukrautsaft: sauer rot bis rosa, neutral violett, basisch blau, grün bis gelb." },
  { id: "s2-v1", modul: "ph-wert", art: "versuch", typ: "mc", q: "Vier farblose Flüssigkeiten wurden mit Universalindikator geprüft. Die Tabelle zeigt das Ergebnis. Welche Flüssigkeit ist neutral?",
    tabelle: { titel: "Universalindikator", kopf: ["Flüssigkeit", "Farbe des Universalindikators"], zeilen: [["K", "orange"], ["L", "grün"], ["M", "violett"], ["N", "rot"]] },
    o: ["Flüssigkeit L", "Flüssigkeit K", "Flüssigkeit M", "Flüssigkeit N"], a: 0,
    e: "Grün bedeutet neutral. Orange und rot zeigen sauer, violett zeigt basisch." },
  { id: "s2-d1", modul: "ph-wert", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt die pH-Werte beim Verdünnen einer sauren Lösung. Welche Aussage passt?",
    diagramm: { art: "linie", titel: "Verdünnen einer sauren Lösung", xTitel: "Stufe", yTitel: "pH-Wert", x: ["0", "1", "2", "3"], y: [1.0, 1.6, 2.2, 2.8], text: "Liniendiagramm: Stufe 0 hat den pH-Wert 1,0, Stufe 1 den Wert 1,6, Stufe 2 den Wert 2,2 und Stufe 3 den Wert 2,8." },
    o: ["Die Lösung wird weniger sauer, bleibt aber sauer.", "Die Lösung wird ab Stufe 2 basisch.", "Die Lösung wird immer saurer.", "Die Lösung bleibt in jeder Stufe gleich sauer."], a: 0,
    e: "Der pH-Wert steigt von 1,0 auf 2,8: weniger sauer. Alle Werte liegen unter 7, die Lösung bleibt sauer." },
  { id: "s2-r1", modul: "ph-wert", art: "rechnen", typ: "zahl", q: "Eine Lösung hat in Stufe 0 den pH-Wert 4,0 und nach drei Verdünnungsstufen den pH-Wert 5,5. Um wie viele pH-Einheiten ist der Wert gestiegen?", loesung: 1.5, toleranz: 0.05, einheit: "pH-Einheiten",
    weg: "5,5 − 4,0 = 1,5 pH-Einheiten.", e: "Der Unterschied ist die Differenz der beiden Werte." },
  { id: "s2-r2", modul: "ph-wert", art: "rechnen", typ: "zahl", q: "Eine Essig-Lösung hat den pH-Wert 3. Wie viele ganze pH-Stufen sind es bis zum neutralen Wert?", loesung: 4, toleranz: 0, einheit: "Stufen",
    weg: "Neutral ist pH 7. Von 3 bis 7 sind es 7 − 3 = 4 Stufen.", e: "Der neutrale Wert ist pH 7. Die Differenz zu 3 ist 4." },
  { id: "s2-a1", modul: "ph-wert", art: "anwendung", typ: "mc", q: "Das Wasser in einem Aquarium soll neutral sein. Eine Probe färbt Universalindikator orange. Was sagt das?", o: ["Das Wasser ist sauer, der pH-Wert liegt unter 7.", "Das Wasser ist basisch.", "Das Wasser ist neutral und passt für die Fische.", "Das Wasser ist farblos und deshalb in Ordnung."], a: 0,
    e: "Orange gehört zu den sauren Lösungen. Neutral wäre grün." },
  { id: "s2-t1", modul: "ph-wert", art: "transfer", typ: "offen", q: "Ein Kind sagt: „Mein Duschgel ist ‚pH-hautneutral‘, also hat es den pH-Wert 7.“ Nimm Stellung.",
    m: "Das stimmt nicht. „pH-hautneutral“ heißt, dass das Duschgel an die Haut angepasst ist. Die Haut ist leicht sauer, ihr pH-Wert liegt bei etwa 5,5. Neutral im Sinne der Chemie wäre pH 7.",
    k: ["nicht|falsch|nein", "haut", "5,5|sauer|angepasst"], min: 2, e: "Die Haut trägt einen leicht sauren Schutzfilm (pH etwa 5,5). „Hautneutral“ bedeutet: dazu passend." },
  { id: "s2-t2", modul: "ph-wert", art: "transfer", typ: "mc", q: "Zu einer starken Lauge (pH 13) wird sehr viel Wasser gegeben. Was ist für den pH-Wert zu erwarten?", o: ["Er sinkt in Richtung 7, die Lösung wird aber nie sauer.", "Er springt auf 0.", "Er steigt auf 14.", "Er wird 7 und danach sauer."], a: 0,
    e: "Wasser ist neutral. Beim Verdünnen nähert sich der pH-Wert 7, geht aber nie auf die andere Seite." },
  { id: "s2-n1", modul: "ph-wert", art: "rechnen", typ: "zahl", nurM: true, q: "Lösung A hat den pH-Wert 4, Lösung B den pH-Wert 6. Ein pH-Schritt bedeutet eine zehnmal so starke Wirkung. Wie oft so stark sauer ist A wie B?", loesung: 100, toleranz: 0, einheit: "mal so stark",
    weg: "Zwei pH-Schritte: 10 · 10 = 100.", e: "Jeder Schritt auf der pH-Skala bedeutet das Zehnfache. Bei zwei Schritten ergibt das 100." },

  /* ----- Säuren und Laugen: Herstellung und Anwendung ----- */
  { id: "s3-b1", modul: "saeuren-laugen", art: "begriff", typ: "mc", q: "Welche Stoffgruppe ergibt mit Wasser eine Säure?", o: ["Nichtmetalloxide", "Metalloxide", "Salze", "Metalle"], a: 0,
    e: "Merkregel: Nichtmetalloxid + Wasser → Säure, Metalloxid + Wasser → Lauge." },
  { id: "s3-b2", modul: "saeuren-laugen", art: "begriff", typ: "mc", q: "Was entsteht, wenn Calciumoxid mit Wasser reagiert?", o: ["Calciumlauge (Kalkwasser)", "Kohlensäure", "schweflige Säure", "Natriumchlorid"], a: 0,
    e: "Calcium ist ein Metall, Calciumoxid ein Metalloxid. Mit Wasser entsteht eine Lauge." },
  { id: "s3-v1", modul: "saeuren-laugen", art: "versuch", typ: "mc", q: "Ein Metall verbrennt zu einem weißen Pulver. Das Pulver wird in Wasser mit Universalindikator gegeben, der Indikator färbt sich blau. Was ist entstanden?", o: ["eine Lauge", "eine Säure", "ein Nichtmetalloxid", "reines Wasser"], a: 0,
    e: "Blau zeigt eine basische Lösung. Das Metalloxid hat mit Wasser eine Lauge gebildet." },
  { id: "s3-z1", modul: "saeuren-laugen", art: "zusammenhang", typ: "rf", q: "Prüfe die Aussagen über Säuren und Laugen.",
    aussagen: [["Säuren greifen unedle Metalle an, dabei entsteht Wasserstoff.", true], ["Laugen lösen Kalk besonders gut.", false], ["Laugen zersetzen Fett und Eiweiß.", true], ["Saurer Regen kann Kalkstein auflösen.", true]],
    e: "Säuren lösen Kalk und greifen unedle Metalle an. Laugen zersetzen Fett und Eiweiß. Kalkstein besteht aus Kalk und wird von saurem Regen angegriffen." },
  { id: "s3-a1", modul: "saeuren-laugen", art: "anwendung", typ: "mc", q: "Wofür werden Laugen in Haushalt und Technik genutzt?", o: ["zur Herstellung von Seife und zum Reinigen von Tanks und Rohren", "zum Lösen von Kalk im Wasserkocher", "zum Süßen von Getränken", "zum Haltbarmachen von Gurken"], a: 0,
    e: "Laugen zersetzen Fett und Eiweiß. Kalk löst man mit Säure, Gurken macht man mit Essigsäure haltbar." },
  { id: "s3-t1", modul: "saeuren-laugen", art: "transfer", typ: "offen", q: "In einem Lehrerversuch verbrennt Kohlenstoff. Das entstehende Gas wird in Wasser mit Universalindikator geleitet, der Indikator wird orange. Erkläre die Beobachtung mit einer Wortgleichung.",
    m: "Kohlenstoff verbrennt zu Kohlenstoffdioxid. Kohlenstoffdioxid + Wasser → Kohlensäure. Die Lösung ist sauer, deshalb wird der Indikator orange.",
    k: ["kohlenstoffdioxid", "kohlensäure|kohlensaeure", "sauer"], min: 3, e: "Kohlenstoff ist ein Nichtmetall. Sein Oxid ergibt mit Wasser eine Säure, die den Indikator rot bis orange färbt." },
  { id: "s3-t2", modul: "saeuren-laugen", art: "transfer", typ: "mc", q: "Eine Bäckerei taucht Brezeln kurz in stark verdünnte Natronlauge. Welche Aussage ist richtig?", o: ["Das macht nur die Bäckerei, zu Hause wäre es zu gefährlich.", "Das kann jeder zu Hause mit Rohrreiniger nachmachen.", "Natronlauge ist eine Säure.", "Nach dem Backen ist die Brezel ätzend."], a: 0,
    e: "Natronlauge ist stark ätzend. Die Bäckerei arbeitet mit stark verdünnter Lösung und Schutz. Nach dem Backen ist die Brezel unbedenklich." },
  { id: "s3-n1", modul: "saeuren-laugen", art: "begriff", typ: "mc", nurM: true, q: "Welche Formel gehört zur schwefligen Säure?", o: ["H₂SO₃", "H₂CO₃", "NaOH", "Mg(OH)₂"], a: 0,
    e: "H₂SO₃ ist die schweflige Säure (aus SO₂ + H₂O). H₂CO₃ ist die Kohlensäure, NaOH das Natriumhydroxid, Mg(OH)₂ das Magnesiumhydroxid." },
  { id: "s3-n2", modul: "saeuren-laugen", art: "zusammenhang", typ: "rf", nurM: true, q: "Prüfe die Aussagen über Säuren und Basen.",
    aussagen: [["Eine Säure gibt in Wasser H⁺-Ionen ab.", true], ["Ein Protonenakzeptor gibt H⁺ ab.", false], ["Basische Lösungen enthalten OH⁻-Ionen.", true]],
    e: "Säuren sind Protonendonatoren (sie geben H⁺ ab), Basen Protonenakzeptoren (sie nehmen H⁺ auf). Basische Lösungen enthalten OH⁻-Ionen." },

  /* ----- Neutralisation und Salze ----- */
  { id: "s4-b1", modul: "salze", art: "begriff", typ: "mc", q: "Wie lautet die allgemeine Wortgleichung der Neutralisation?", o: ["Säure + Lauge → Salz + Wasser", "Säure + Salz → Lauge + Wasser", "Lauge + Wasser → Säure + Salz", "Säure + Wasser → Lauge"], a: 0,
    e: "Bei der Neutralisation heben sich Säure und Lauge auf: Es entstehen ein Salz und Wasser." },
  { id: "s4-b2", modul: "salze", art: "begriff", typ: "mc", q: "Welchen Teil des Salzes liefert die Säure?", o: ["den Säurerest", "den Metallanteil", "die Flammenfarbe", "das Wasser"], a: 0,
    e: "Der Metallanteil kommt aus der Lauge, der Säurerest aus der Säure." },
  { id: "s4-z1", modul: "salze", art: "zusammenhang", typ: "rf", q: "Prüfe die Aussagen über Kochsalz.",
    aussagen: [["Kochsalz bildet kleine Würfel (Kristalle).", true], ["Ein fester Kochsalzkristall leitet den Strom.", false], ["Kochsalz löst sich gut in Wasser.", true], ["Kochsalz ist biegsam wie ein Metall.", false]],
    e: "Kochsalz ist kristallin, spröde und gut wasserlöslich. Die Salzlösung leitet den Strom, der feste Kristall nicht." },
  { id: "s4-a1", modul: "salze", art: "anwendung", typ: "mc", q: "Ein Magenmittel enthält einen basischen Stoff. Wozu dient er bei Sodbrennen?", o: ["Er neutralisiert überschüssige Magensäure.", "Er bildet mehr Magensäure.", "Er färbt den Magen.", "Er senkt den Gefrierpunkt."], a: 0,
    e: "Ein basischer Stoff hebt die Wirkung der Säure auf: Das ist eine Neutralisation." },
  { id: "s4-v1", modul: "salze", art: "versuch", typ: "mc", q: "Bei einer Flammenprobe färbt ein weißes Salz die Brennerflamme gelb. Welcher Metallanteil steckt im Salz?", o: ["Natrium", "Calcium", "Chlorid", "Sulfat"], a: 0,
    e: "Natrium färbt die Flamme gelb, Calcium ziegelrot bis orangerot. Chlorid und Sulfat sind Säurereste, sie ändern die Farbe nicht." },
  { id: "s4-d1", modul: "salze", art: "diagramm", typ: "mc", q: "Auf der Straße hat es −9 °C. Das Diagramm zeigt die Gefrierpunkte von Salzlösungen. Welche der gezeigten Lösungen mit dem geringsten Salzanteil taut das Eis noch?",
    diagramm: { art: "linie", titel: "Salzlösung und Gefrierpunkt (Beispielwerte)", xTitel: "Salz in der Lösung in %", yTitel: "Gefrierpunkt in °C", x: ["0", "5", "10", "15", "20"], y: [0, -3, -7, -11, -16], text: "Liniendiagramm: 0 % Salz gefriert bei 0 °C, 5 % bei −3 °C, 10 % bei −7 °C, 15 % bei −11 °C und 20 % bei −16 °C." },
    o: ["die 15-%-Lösung", "die 5-%-Lösung", "die 10-%-Lösung", "die 0-%-Lösung"], a: 0,
    e: "Die Lösung muss erst unterhalb von −9 °C gefrieren. Das ist bei 15 % (−11 °C) der Fall, bei 10 % (−7 °C) ist sie bei −9 °C schon fest." },
  { id: "s4-r1", modul: "salze", art: "rechnen", typ: "zahl", q: "Zu Salzsäure wird Lauge getropft. Bei 6 Tropfen hat die Lösung den pH-Wert 2, nach 15 Tropfen ist sie neutral. Wie viele Tropfen kommen zwischen diesen beiden Punkten dazu?", loesung: 9, toleranz: 0, einheit: "Tropfen",
    weg: "15 − 6 = 9 Tropfen.", e: "Die Differenz der beiden Tropfenzahlen ergibt die Zahl der Tropfen dazwischen." },
  { id: "s4-r2", modul: "salze", art: "rechnen", typ: "zahl", q: "Die Tabelle zeigt Beispielwerte. Um wie viel °C liegt der Gefrierpunkt der 15-%-Lösung tiefer als der der 3-%-Lösung?",
    tabelle: { titel: "Salzlösung und Gefrierpunkt (Beispielwerte)", kopf: ["Salz in der Lösung", "3 %", "9 %", "15 %"], zeilen: [["Gefrierpunkt", "−2 °C", "−6 °C", "−11 °C"]] },
    loesung: 9, toleranz: 0, einheit: "°C", weg: "−2 °C − (−11 °C) = 9 °C. Die 15-%-Lösung gefriert 9 °C tiefer.", e: "Man bildet den Unterschied zwischen −11 °C und −2 °C." },
  { id: "s4-t1", modul: "salze", art: "transfer", typ: "offen", q: "Ein kleiner See wird durch sauren Regen immer saurer. Ein Vorschlag lautet, Kalk in den See zu geben. Erkläre, warum das helfen kann.",
    m: "Kalk wirkt basisch. Er neutralisiert die Säure im Wasser: Säure und Base heben sich in ihrer Wirkung auf, und der pH-Wert steigt in Richtung 7.",
    k: ["basisch|lauge", "neutralis|aufheb", "säure|saeure|sauer"], min: 2, e: "Wie beim Kalken saurer Böden hebt der basische Kalk die Wirkung der Säure auf." },
  { id: "s4-t2", modul: "salze", art: "transfer", typ: "mc", q: "Zwei weiße Salze färben beide die Brennerflamme gelb. Was folgt daraus?", o: ["Beide enthalten Natrium, sie können sich im Säurerest unterscheiden.", "Beide enthalten Chlorid.", "Beide sind Calciumsalze.", "Beide sind dasselbe Salz."], a: 0,
    e: "Die Flammenfarbe verrät nur den Metallanteil. Gelb heißt Natrium. Der Säurerest kann verschieden sein, zum Beispiel Chlorid oder Sulfat." },
  { id: "s4-n1", modul: "salze", art: "begriff", typ: "mc", nurM: true, q: "Mit welcher Lösung weist man Chlorid nach?", o: ["Silbernitrat-Lösung", "Bariumchlorid-Lösung", "Universalindikator", "Blaukrautsaft"], a: 0,
    e: "Chlorid ergibt mit Silbernitrat-Lösung einen weißen Niederschlag. Sulfat weist man mit Bariumchlorid-Lösung nach." },
  { id: "s4-n2", modul: "salze", art: "zusammenhang", typ: "mc", nurM: true, q: "Magnesium wird in Salzsäure gegeben, es sprudelt. Welche Stoffe entstehen?", o: ["Magnesiumchlorid und Wasserstoff", "Magnesiumchlorid und Wasser", "Magnesiumoxid und Chlor", "Magnesiumsulfat und Wasserstoff"], a: 0,
    e: "Metall + Säure → Salz + Wasserstoff. Das Gas Wasserstoff verursacht das Sprudeln, der Säurerest der Salzsäure ist Chlorid." }
]);
