/* Probe-Vorbereitung zu Probe 4 „Atome, Ionen und chemische Reaktionen“ (NT 8): Übungsaufgaben – nicht die Aufgaben der Probe.
 * Kennungen (id) nie neu vergeben; nurM: true = nur M8. Aufbau der Aufgaben: siehe vorbereitung.js. */
NT8Vorbereitung.pool("stoffe", [
  /* ----- Vom Atom zum Ion ----- */
  { id: "a1-b1", modul: "atom-ion", art: "begriff", typ: "mc", q: "Wie heißen die positiv geladenen Teilchen im Atomkern?", o: ["Protonen", "Elektronen", "Neutronen", "Außenelektronen"], a: 0,
    e: "Im Kern sitzen die positiv geladenen Protonen und die ungeladenen Neutronen. Elektronen bewegen sich auf den Schalen." },
  { id: "a1-b2", modul: "atom-ion", art: "begriff", typ: "mc", q: "Was ist ein Ion?", o: ["ein geladenes Teilchen", "ein Atom ohne Elektronen und ohne Kern", "ein besonders großes Atom", "ein Teilchen, das nur aus Neutronen besteht"], a: 0,
    e: "Ein Ion entsteht, wenn ein Atom Elektronen abgibt oder aufnimmt. Es hat dann mehr oder weniger Elektronen als Protonen und ist geladen." },
  { id: "a1-z1", modul: "atom-ion", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Ein Atom hat gleich viele Protonen und Elektronen.", true], ["Gibt ein Atom Elektronen ab, wird es negativ geladen.", false], ["Bei der Bildung eines Ions bleibt die Protonenzahl gleich.", true], ["Das Schalenmodell zeigt Atome so, wie sie unter dem Mikroskop aussehen.", false]],
    e: "Ein Atom ist ungeladen. Wer Elektronen abgibt, hat mehr Protonen als Elektronen und ist positiv. Der Kern bleibt unverändert. Das Schalenmodell ist nur ein Denkmodell." },
  { id: "a1-r1", modul: "atom-ion", art: "rechnen", typ: "zahl", q: "Ein Kalium-Atom hat 19 Protonen und 19 Elektronen und gibt ein Elektron ab. Wie viele Elektronen hat das K⁺-Ion?", loesung: 18, toleranz: 0, einheit: "Elektronen",
    weg: "19 Elektronen − 1 abgegebenes Elektron = 18 Elektronen. Ladung: 19 − 18 = +1.", e: "Beim Abgeben sinkt die Elektronenzahl, die Protonenzahl bleibt gleich." },
  { id: "a1-r2", modul: "atom-ion", art: "rechnen", typ: "zahl", q: "Ein Sauerstoff-Ion O²⁻ hat 8 Protonen. Wie viele Elektronen hat es?", loesung: 10, toleranz: 0, einheit: "Elektronen",
    weg: "Ladung = Protonen − Elektronen, also −2 = 8 − Elektronen. Damit sind es 8 + 2 = 10 Elektronen.", e: "Zweifach negativ heißt: zwei Elektronen mehr als Protonen." },
  { id: "a1-a1", modul: "atom-ion", art: "anwendung", typ: "mc", q: "Auf einem Mineralwasser-Etikett steht „Mg²⁺“. Was bedeutet das?", o: ["Ein Magnesium-Teilchen mit zwei Elektronen weniger als Protonen", "Zwei Magnesium-Atome ohne Ladung", "Ein Magnesium-Teilchen mit zwei Elektronen mehr als Protonen", "Magnesium, das zweimal gemessen wurde"], a: 0,
    e: "Die hochgestellte 2+ zeigt die Ladung: Es fehlen zwei Elektronen, darum überwiegt die positive Ladung." },
  { id: "a1-d1", modul: "atom-ion", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt für vier Teilchen die Zahl der Protonen und der Elektronen. Welches Teilchen ist ein negativ geladenes Ion?",
    diagramm: { art: "saeulen", titel: "Protonen und Elektronen", xTitel: "Teilchen", yTitel: "Anzahl", x: ["Teilchen 1", "Teilchen 2", "Teilchen 3", "Teilchen 4"], reihen: [{ name: "Protonen", y: [9, 12, 17, 3] }, { name: "Elektronen", y: [10, 10, 17, 2] }],
      text: "Säulendiagramm mit je zwei Säulen: Teilchen 1 hat 9 Protonen und 10 Elektronen, Teilchen 2 hat 12 Protonen und 10 Elektronen, Teilchen 3 hat 17 Protonen und 17 Elektronen, Teilchen 4 hat 3 Protonen und 2 Elektronen." },
    o: ["Teilchen 1", "Teilchen 2", "Teilchen 3", "Teilchen 4"], a: 0,
    e: "Negativ geladen ist ein Teilchen mit mehr Elektronen als Protonen: Teilchen 1 (9 Protonen, 10 Elektronen). Teilchen 2 und 4 sind positiv, Teilchen 3 ist ein Atom." },
  { id: "a1-t1", modul: "atom-ion", art: "transfer", typ: "offen", q: "Ein Schwefel-Atom hat 16 Protonen und 16 Elektronen. Es nimmt zwei Elektronen auf. Beschreibe das entstehende Teilchen: Zahl der Protonen und Elektronen und Ladung.",
    m: "Das Teilchen hat noch 16 Protonen, aber jetzt 18 Elektronen. Es hat zwei Elektronen mehr als Protonen und ist deshalb zweifach negativ geladen.",
    k: ["16", "18", "negativ"], min: 3, e: "Protonen bleiben gleich, die Elektronen steigen auf 18. Ladung = 16 − 18 = −2." },
  { id: "a1-t2", modul: "atom-ion", art: "transfer", typ: "mc", q: "Ein Teilchen hat 19 Protonen und 18 Elektronen. Welche Aussage stimmt?", o: ["Es ist ein positiv geladenes Ion.", "Es ist ein negativ geladenes Ion.", "Es ist ein ungeladenes Atom.", "Es ist ein Atom eines anderen Elements."], a: 0,
    e: "Eine Elektronenzahl, die kleiner als die Protonenzahl ist, bedeutet positive Ladung: 19 − 18 = +1." },
  { id: "a1-n1", modul: "atom-ion", art: "anwendung", typ: "mc", nurM: true, q: "Magnesium steht in der 2. Hauptgruppe. Welches Ion bildet es?", o: ["Mg²⁺ – es gibt zwei Elektronen ab", "Mg²⁻ – es nimmt zwei Elektronen auf", "Mg⁺ – es gibt ein Elektron ab", "Mg⁷⁺ – es gibt sieben Elektronen ab"], a: 0,
    e: "Atome der 2. Hauptgruppe geben 2 Elektronen ab. Es entsteht ein zweifach positives Ion, ein Kation." },
  { id: "a1-n2", modul: "atom-ion", art: "zusammenhang", typ: "rf", nurM: true, q: "Prüfe die Aussagen zur Valenzstrichschreibweise.",
    aussagen: [["Ein Strich steht für ein Elektronenpaar.", true], ["Ein Punkt steht für zwei Elektronen.", false], ["Ein Anion zeichnet man in eckigen Klammern und schreibt die Ladung dahinter.", true], ["Ein Kation heißt so, weil es negativ geladen ist.", false]],
    e: "Ein Strich sind zwei Elektronen, ein Punkt ist ein einzelnes Elektron. Ein Kation ist positiv geladen, ein Anion negativ." },

  /* ----- Alkalimetalle, Halogene und die Ionenbindung ----- */
  { id: "a2-b1", modul: "ionenbindung", art: "begriff", typ: "mc", q: "Wie heißt die Anziehung zwischen positiven und negativen Ionen?", o: ["Ionenbindung", "Schwerkraft", "Magnetismus", "Reibung"], a: 0,
    e: "Entgegengesetzt geladene Ionen ziehen sich an. Diese Anziehung nennt man Ionenbindung." },
  { id: "a2-b2", modul: "ionenbindung", art: "begriff", typ: "mc", q: "Welches Element gehört zu den Halogenen?", o: ["Fluor", "Lithium", "Neon", "Natrium"], a: 0,
    e: "Fluor und Chlor stehen in der 7. Hauptgruppe und heißen Halogene. Lithium und Natrium sind Alkalimetalle, Neon ist ein Edelgas." },
  { id: "a2-z1", modul: "ionenbindung", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["Alkalimetalle stehen in der 1. Hauptgruppe.", true], ["Halogene haben sieben Außenelektronen.", true], ["Edelgase reagieren besonders heftig.", false], ["Salzkristalle sind kugelförmig, weil die Ionen rund sind.", false]],
    e: "Alkalimetalle haben 1, Halogene 7 Außenelektronen. Edelgase haben eine volle Außenschale und reagieren kaum. Salzkristalle sind würfelförmig, weil die Ionen im Gitter regelmäßig liegen." },
  { id: "a2-a1", modul: "ionenbindung", art: "anwendung", typ: "mc", q: "Natriumfluorid in der Zahnpasta ist ungefährlich, obwohl Fluor giftig ist. Welche Aussage erklärt das?", o: ["Bei der Reaktion ist ein neuer Stoff mit ganz anderen Eigenschaften entstanden.", "Das Fluor ist in der Zahnpasta nur stark verdünnt, bleibt aber unverändert giftig.", "Natriumfluorid ist ein giftiges Gas.", "Fluor ist nur in Zahnpasta ungiftig."], a: 0,
    e: "Wie beim Kochsalz entsteht aus Element und Metall ein neuer Stoff aus Ionen. Er hat andere Eigenschaften als die Ausgangsstoffe." },
  { id: "a2-r1", modul: "ionenbindung", art: "rechnen", typ: "zahl", q: "Ein Fluor-Atom hat 9 Elektronen und nimmt ein Elektron auf. Wie viele Elektronen hat das Fluorid-Ion?", loesung: 10, toleranz: 0, einheit: "Elektronen",
    weg: "9 Elektronen + 1 aufgenommenes Elektron = 10 Elektronen. Das sind genauso viele wie beim Neon-Atom.", e: "Das F⁻-Ion hat die Schalen 2 | 8, also eine volle Außenschale." },
  { id: "a2-r2", modul: "ionenbindung", art: "rechnen", typ: "zahl", q: "Ein Lithium-Atom hat 3 Elektronen und gibt sein Außenelektron ab. Wie viele Elektronen hat das Li⁺-Ion?", loesung: 2, toleranz: 0, einheit: "Elektronen",
    weg: "3 Elektronen − 1 abgegebenes Elektron = 2 Elektronen.", e: "Li⁺ hat 2 Elektronen, genau wie Helium. Die erste Schale ist damit voll." },
  { id: "a2-d1", modul: "ionenbindung", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt die Zahl der Außenelektronen von fünf Atomen. Welche beiden Atome gehören zu den Alkalimetallen?",
    diagramm: { art: "saeulen", titel: "Außenelektronen", xTitel: "Atom", yTitel: "Zahl der Außenelektronen", x: ["Lithium", "Natrium", "Fluor", "Chlor", "Neon"], y: [1, 1, 7, 7, 8], text: "Säulendiagramm: Lithium hat 1 Außenelektron, Natrium 1, Fluor 7, Chlor 7 und Neon 8." },
    o: ["Lithium und Natrium", "Fluor und Chlor", "Chlor und Neon", "Natrium und Fluor"], a: 0,
    e: "Alkalimetalle haben 1 Außenelektron: Lithium und Natrium. Fluor und Chlor haben 7 (Halogene), Neon hat 8 (Edelgas)." },
  { id: "a2-t1", modul: "ionenbindung", art: "transfer", typ: "offen", q: "Im Salzkristall liegen Na⁺ und Cl⁻ immer abwechselnd. Erkläre, warum zwei Na⁺-Ionen nicht direkt nebeneinander liegen.",
    m: "Gleich geladene Ionen stoßen sich ab. Ungleich geladene Ionen ziehen sich an. Darum wechseln sich Na⁺ und Cl⁻ im Gitter ab.",
    k: ["abstoß|stoßen", "gleich", "anzieh|abwechselnd|wechseln"], min: 2, e: "Plus und Plus stoßen sich ab, Plus und Minus ziehen sich an. So entsteht das regelmäßige Ionengitter." },
  { id: "a2-t2", modul: "ionenbindung", art: "transfer", typ: "mc", q: "Rubidium steht in der 1. Hauptgruppe unter Kalium. Wie viele Außenelektronen hat ein Rubidium-Atom?", o: ["1", "7", "8", "2"], a: 0,
    e: "Alle Atome der 1. Hauptgruppe haben ein Außenelektron. Darum verhalten sich die Alkalimetalle ähnlich." },
  { id: "a2-n1", modul: "ionenbindung", art: "anwendung", typ: "mc", nurM: true, q: "Im Kristall aus Li⁺- und F⁻-Ionen gleichen sich die Ladungen aus. Wie lautet die Verhältnisformel?", o: ["LiF", "Li₂F", "LiF₂", "Li₂F₂"], a: 0,
    e: "Auf ein Li⁺ kommt ein F⁻. Das Verhältnis ist 1 : 1, also LiF." },
  { id: "a2-n2", modul: "ionenbindung", art: "rechnen", typ: "zahl", nurM: true, q: "Chlor kommt als Cl₂-Molekül vor. Wie viele Natrium-Atome braucht man in der Gleichung, damit genau ein Cl₂-Molekül reagiert?", loesung: 2, toleranz: 0, einheit: "Natrium-Atome",
    weg: "Jedes Chlor-Atom braucht ein Natrium-Atom. Ein Cl₂-Molekül hat zwei Chlor-Atome, also 2 Na: 2 Na + Cl₂ → 2 NaCl.", e: "Links und rechts müssen von jeder Sorte gleich viele Atome stehen." },

  /* ----- Chemische Reaktionen erkennen ----- */
  { id: "a3-b1", modul: "reaktionen", art: "begriff", typ: "mc", q: "Wie nennt man einen festen Stoff, der aus einer Lösung ausfällt?", o: ["Niederschlag", "Ausgangsstoff", "Gas", "Lösungsmittel"], a: 0,
    e: "Ein Niederschlag ist ein Anzeichen für eine chemische Reaktion: Die Flüssigkeit wird trüb und feste Flocken sinken ab." },
  { id: "a3-b2", modul: "reaktionen", art: "begriff", typ: "mc", q: "Wo stehen in einer Wortgleichung die Produkte?", o: ["rechts vom Reaktionspfeil", "links vom Reaktionspfeil", "über dem Reaktionspfeil", "unter dem Reaktionspfeil"], a: 0,
    e: "Links stehen die Ausgangsstoffe, rechts die Produkte. Der Pfeil heißt „reagiert zu“." },
  { id: "a3-z1", modul: "reaktionen", art: "zusammenhang", typ: "rf", q: "Prüfe die Aussagen über chemische Reaktionen.",
    aussagen: [["Bei einer chemischen Reaktion entsteht ein neuer Stoff mit neuen Eigenschaften.", true], ["Wenn eine Flüssigkeit sprudelt, ist das immer eine chemische Reaktion.", false], ["Beim Lösen von Zucker in Tee entsteht ein neuer Stoff.", false], ["Im Kugelmodell werden die Atome bei einer Reaktion neu angeordnet.", true]],
    e: "Sprudeln kann auch beim Kochen vorkommen. Sicher ist nur: Es entsteht ein neuer Stoff. Beim Lösen bleibt der Stoff derselbe." },
  { id: "a3-a1", modul: "reaktionen", art: "anwendung", typ: "mc", q: "Papier verbrennt zu Asche und Rauch. Woran erkennt man, dass eine chemische Reaktion abläuft?", o: ["Es entstehen neue Stoffe wie Asche und Gase.", "Das Papier wird kleiner.", "Das Papier verändert seine Form.", "Das Papier liegt im Licht."], a: 0,
    e: "Asche und Rauchgase sind neue Stoffe mit anderen Eigenschaften als Papier. Das Kleinerwerden allein sagt noch nichts." },
  { id: "a3-r1", modul: "reaktionen", art: "rechnen", typ: "zahl", q: "Vor einer Reaktion gibt es 10 Wasserstoff-Atome und 5 Sauerstoff-Atome. Wie viele Wasserstoff-Atome gibt es nachher?", loesung: 10, toleranz: 0, einheit: "Atome",
    weg: "Bei einer Reaktion geht kein Atom verloren und es kommt keines dazu. Also bleiben es 10 Wasserstoff-Atome.", e: "Die Atome werden nur neu angeordnet." },
  { id: "a3-r2", modul: "reaktionen", art: "rechnen", typ: "zahl", q: "Aus 6 H₂-Teilchen und 3 O₂-Teilchen entsteht Wasser. Wie viele Wasser-Teilchen (H₂O) entstehen?", loesung: 6, toleranz: 0, einheit: "Teilchen",
    weg: "6 H₂ enthalten 12 H-Atome, 3 O₂ enthalten 6 O-Atome. Jedes Wasser-Teilchen braucht 2 H und 1 O. Also entstehen 6 H₂O.", e: "Von jeder Atomsorte sind vorher und nachher gleich viele da." },
  { id: "a3-d1", modul: "reaktionen", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt, wie viele Atome es vor und nach einer Reaktion gibt. Was zeigt es?",
    diagramm: { art: "saeulen", titel: "Atome vor und nach der Reaktion", xTitel: "Atomsorte", yTitel: "Anzahl der Atome", x: ["Wasserstoff", "Sauerstoff"], reihen: [{ name: "vorher", y: [8, 4] }, { name: "nachher", y: [8, 4] }],
      text: "Säulendiagramm mit je zwei Säulen: Wasserstoff-Atome vorher 8 und nachher 8, Sauerstoff-Atome vorher 4 und nachher 4." },
    o: ["Von beiden Atomsorten gibt es vorher und nachher gleich viele Atome.", "Nachher gibt es mehr Wasserstoff-Atome.", "Nachher sind Sauerstoff-Atome verschwunden.", "Es sind neue Atomsorten entstanden."], a: 0,
    e: "Bei einer chemischen Reaktion bleibt die Zahl der Atome jeder Sorte gleich." },
  { id: "a3-v1", modul: "reaktionen", art: "versuch", typ: "mc", q: "Ein Wärmekissen enthält Eisenpulver. Nach dem Auspacken misst ein Kind die Temperatur (siehe Tabelle). Was zeigt die Messreihe?",
    tabelle: { titel: "Temperatur am Wärmekissen", kopf: ["Zeit in min", "Temperatur in °C"], zeilen: [["0", "20"], ["5", "31"], ["10", "38"]] },
    o: ["Im Kissen läuft eine Reaktion ab, die Wärme abgibt.", "Das Kissen wird von außen geheizt.", "Das Eisenpulver schmilzt.", "Es ändert sich nur der Zustand des Eisens."], a: 0,
    e: "Die Temperatur steigt, ohne dass man heizt. Das ist ein Anzeichen für eine chemische Reaktion (Eisen reagiert mit Sauerstoff)." },
  { id: "a3-t1", modul: "reaktionen", art: "transfer", typ: "offen", q: "Ein Kind sagt: „Beim Brennen einer Kerze verschwindet das Wachs einfach.“ Erkläre mit dem Kugelmodell, was wirklich passiert.",
    m: "Das Wachs verschwindet nicht. Seine Atome werden neu angeordnet und bilden neue Stoffe, zum Beispiel Gase. Dabei geht kein Atom verloren.",
    k: ["neu angeordnet|umgruppier|neu zusammen", "kein atom|verloren|nichts verschwindet|bleiben erhalten", "neue stoffe|neuer stoff|gase|gas"], min: 2, e: "Im Kugelmodell werden Atome nur neu gruppiert. Aus den Atomen des Wachses entstehen andere Stoffe." },
  { id: "a3-t2", modul: "reaktionen", art: "transfer", typ: "mc", q: "Ein Eiswürfel liegt in der Sonne, schmilzt und das Wasser verdunstet später. Welche Aussage stimmt?", o: ["Es sind nur physikalische Vorgänge, denn der Stoff bleibt Wasser.", "Es ist eine chemische Reaktion, denn es wird dabei warm.", "Es ist eine chemische Reaktion, denn die Form ändert sich.", "Es entsteht ein neuer Stoff, denn Wasserdampf ist unsichtbar."], a: 0,
    e: "Schmelzen und Verdunsten ändern nur den Zustand. Eis, Wasser und Wasserdampf sind derselbe Stoff." },
  { id: "a3-n1", modul: "reaktionen", art: "rechnen", typ: "zahl", nurM: true, q: "2 g Wasserstoff und 16 g Sauerstoff reagieren vollständig zu Wasser. Wie viel Wasser entsteht?", loesung: 18, toleranz: 0, einheit: "g",
    weg: "Die Masse bleibt erhalten: 2 g + 16 g = 18 g.", e: "Erhaltung der Masse: Die Produkte wiegen zusammen so viel wie die Ausgangsstoffe." },
  { id: "a3-n2", modul: "reaktionen", art: "anwendung", typ: "mc", nurM: true, q: "Silbernitrat-Lösung und Lithiumchlorid-Lösung werden gemischt. Es fällt ein weißer Niederschlag aus, die Stoffe tauschen ihre Partner. Welche Wortgleichung stimmt?", o: ["Silbernitrat + Lithiumchlorid → Silberchlorid + Lithiumnitrat", "Silbernitrat → Silber + Nitrat", "Silber + Lithiumchlorid → Silbernitrat + Lithium", "Silbernitrat + Lithiumchlorid → Silberchlorid"], a: 0,
    e: "Bei der Umsetzung werden die Partner getauscht: Silber verbindet sich mit Chlorid, Lithium mit Nitrat." },

  /* ----- Reaktionen verstehen und auswerten ----- */
  { id: "a4-b1", modul: "reaktionen-auswerten", art: "begriff", typ: "mc", q: "Wie nennt man eine begründete Vermutung, die man mit einem Versuch prüfen kann?", o: ["Hypothese", "Beobachtung", "Produkt", "Messwert"], a: 0,
    e: "Eine Hypothese wird durch den Versuch bestätigt oder widerlegt. Auch eine widerlegte Hypothese ist ein Ergebnis." },
  { id: "a4-b2", modul: "reaktionen-auswerten", art: "begriff", typ: "mc", q: "Welches Laborgerät misst Flüssigkeitsmengen genau?", o: ["der Messzylinder", "die Tiegelzange", "der Spatel", "der Trichter"], a: 0,
    e: "Im Messzylinder liest man das Volumen auf Augenhöhe ab. Die Tiegelzange hält Heißes, der Spatel portioniert Feststoffe, der Trichter füllt in enge Gefäße." },
  { id: "a4-z1", modul: "reaktionen-auswerten", art: "zusammenhang", typ: "rf", q: "Richtig oder falsch? Entscheide bei jeder Aussage.",
    aussagen: [["„Das Wasser färbt sich blau“ ist eine Beobachtung.", true], ["„Es hat sich ein neuer Stoff gebildet“ ist eine Beobachtung.", false], ["Eine widerlegte Hypothese ist ein wertloses Ergebnis.", false], ["Bei einem fairen Versuch ändert man nur eine Größe.", true]],
    e: "Eine Farbe sieht man. Dass ein neuer Stoff entstanden ist, schließt man daraus. Auch eine widerlegte Hypothese bringt Wissen." },
  { id: "a4-a1", modul: "reaktionen-auswerten", art: "anwendung", typ: "mc", q: "Welches Verhalten im Labor ist richtig?", o: ["Lange Haare zusammenbinden und eine Schutzbrille tragen.", "Den Geruch prüfen, indem man die Nase direkt über das Gefäß hält.", "Eine kleine Probe vorsichtig probieren.", "Das Reagenzglas beim Erhitzen mit der Öffnung zum Nachbarn halten."], a: 0,
    e: "Haare und Augen müssen geschützt sein. Man riecht nur durch Zufächeln, probiert nie und richtet die Öffnung nie auf eine Person." },
  { id: "a4-r1", modul: "reaktionen-auswerten", art: "rechnen", typ: "zahl", q: "Die Tabelle zeigt, wie hoch das Wasser im Reagenzglas mit rostender Eisenwolle gestiegen ist. Wie viele Millimeter ist es zwischen dem 2. und dem 6. Tag gestiegen?", loesung: 6, toleranz: 0, einheit: "mm",
    tabelle: { titel: "Rostende Eisenwolle", kopf: ["Tag", "Wasser gestiegen in mm"], zeilen: [["0", "0"], ["2", "7"], ["4", "11"], ["6", "13"]] },
    weg: "Am 6. Tag sind es 13 mm, am 2. Tag 7 mm. Also 13 mm − 7 mm = 6 mm.", e: "Man liest beide Werte in der Tabelle ab und bildet die Differenz." },
  { id: "a4-d1", modul: "reaktionen-auswerten", art: "diagramm", typ: "mc", q: "Das Diagramm zeigt, wie lange eine Brausetablette bei verschiedenen Wassertemperaturen sprudelt. Wie lange sprudelt sie bei 35 °C?",
    diagramm: { art: "linie", titel: "Brausetablette", xTitel: "Wassertemperatur in °C", yTitel: "Zeit in s", x: ["15", "25", "35", "45"], y: [80, 50, 34, 26], text: "Liniendiagramm: Bei 15 °C sprudelt die Tablette 80 Sekunden, bei 25 °C 50 s, bei 35 °C 34 s und bei 45 °C 26 s." },
    o: ["34 s", "50 s", "26 s", "80 s"], a: 0,
    e: "Man geht bei 35 °C nach oben bis zur Linie und liest die Zeit ab: 34 s. Je wärmer, desto kürzer die Zeit." },
  { id: "a4-v1", modul: "reaktionen-auswerten", art: "versuch", typ: "mc", q: "Tom prüft, ob Eisenwolle in Salzwasser schneller rostet als in Leitungswasser. Welcher Plan ist fair?", o: ["Zwei gleiche Gläser mit gleich viel Wasser und gleicher Eisenwolle, nur das Salz ist verschieden.", "Salzwasser im großen Glas, Leitungswasser im kleinen Glas.", "Viel Eisenwolle im Salzwasser, wenig im Leitungswasser.", "Nur das Glas mit Salzwasser beobachten."], a: 0,
    e: "Bei einem fairen Versuch ändert man nur eine Größe (hier: das Salz). Alles andere bleibt gleich." },
  { id: "a4-v2", modul: "reaktionen-auswerten", art: "versuch", typ: "mc", q: "Bei einem Versuch sinkt das Thermometer im Becher von 21 °C auf 15 °C. Welche der Aussagen ist eine Deutung?", o: ["Die Reaktion nimmt Energie aus der Umgebung auf.", "Das Thermometer zeigt 15 °C.", "Die Temperatur ist in zwei Minuten gesunken.", "Im Becher ist es kälter geworden."], a: 0,
    e: "Die Messwerte und das Kälterwerden sind Beobachtungen. Was dahintersteckt (Energie wird aufgenommen), ist die Deutung." },
  { id: "a4-t1", modul: "reaktionen-auswerten", art: "transfer", typ: "offen", q: "Anton legt einen Eisennagel in ein Glas mit Öl und einen zweiten in ein Glas mit Wasser. Nach einer Woche rostet nur der Nagel im Wasser. Erkläre das.",
    m: "Eisen rostet nur, wenn Wasser und Sauerstoff da sind. Das Öl hält Wasser und Sauerstoff vom Nagel fern, im Wasserglas sind beide vorhanden. Darum rostet nur dieser Nagel.",
    k: ["öl", "wasser", "sauerstoff"], min: 3, e: "Rost braucht Wasser und Sauerstoff. Öl schützt wie ein Überzug." },
  { id: "a4-t2", modul: "reaktionen-auswerten", art: "transfer", typ: "mc", q: "Ein Eisennagel liegt einen Monat lang in einer trockenen, fest verschlossenen Dose und rostet nicht. Was fehlt?", o: ["Wasser", "Wärme", "Salz", "Licht"], a: 0,
    e: "Im trockenen Glas rostet nichts: Eisen braucht Wasser und Sauerstoff. Salz beschleunigt das Rosten nur." },
  { id: "a4-n1", modul: "reaktionen-auswerten", art: "rechnen", typ: "zahl", nurM: true, q: "Eisenwolle wiegt vor dem Verbrennen auf der offenen Waage 5,0 g, danach 6,4 g. Wie viel Sauerstoff hat sie aus der Luft gebunden?", loesung: 1.4, toleranz: 0.05, einheit: "g",
    weg: "Die Zunahme ist die Masse des gebundenen Sauerstoffs: 6,4 g − 5,0 g = 1,4 g.", e: "Die Gesamtmasse bleibt gleich. Der Sauerstoff aus der Luft wurde vorher nur nicht mitgewogen." },
  { id: "a4-n2", modul: "reaktionen-auswerten", art: "anwendung", typ: "offen", nurM: true, q: "Jonas vermutet: „Warmes Wasser lässt Eisenwolle schneller rosten.“ Plane einen fairen Versuch.",
    m: "Er stellt zwei gleiche Gläser mit gleicher Eisenwolle und gleich viel Wasser auf, eines mit kaltem, eines mit warmem Wasser. Nur die Temperatur ändert sich. Nach einigen Tagen vergleicht er, wie stark die Eisenwolle gerostet ist.",
    k: ["temperatur", "gleich", "vergleich|beobacht|rost"], min: 3, e: "Ein fairer Versuch ändert nur eine Größe. Am Ende vergleicht man das Ergebnis." }
]);
