/* Deutsch 8 · Schreiben und Aufsätze · Modul 2 (M8): Sachtext zum Zusammenfassen – eigene, dichtere Fassung, acht Abschnitte
   (Einstieg – Messen am Boden – Wetterballons – Satelliten und Radar – Rechenmodelle – Grenzen – Wahrscheinlichkeit –
   Fachleute und Fazit). */
D7Texte.add({
  id: "schr-wetter-m", titel: "Wie eine Wettervorhersage entsteht", textsorte: "Sachtext", zug: "M8",
  modul: "Schreiben und Aufsätze", unterthema: "Kernaussagen herausarbeiten, Zusammenhänge verdichten, zusammenfassen", woerter: 700,
  schwierigkeit: "anspruchsvoll", lehrplan: "D8 3.2, 2.1", thema: "Entstehung einer Wettervorhersage",
  quelle: "Eigenständig für GRUMI erstellt.", lizenz: "eigener Text", erstellung: "eigener Text für GRUMI",
  zeilennummern: true, probe: false,
  absaetze: [
    "Viele Menschen richten ihren Tag nach der Wettervorhersage: Die Landwirtin plant danach ihre Ernte, der Fluglotse den Flugbetrieb, die Schulklasse ihren Ausflug. Dass eine App das Wetter der kommenden Tage auf die Stunde genau anzuzeigen scheint, wirkt selbstverständlich. Tatsächlich steht hinter jeder Vorhersage ein aufwendiges Zusammenspiel von Messtechnik, Mathematik und menschlicher Erfahrung – und ein Rest an Unsicherheit, der sich nicht beseitigen lässt.",
    "Grundlage jeder Vorhersage ist der gegenwärtige Zustand der Atmosphäre, der Lufthülle der Erde. Um ihn zu erfassen, betreiben die Wetterdienste weltweit Tausende von Messstationen, die fortlaufend Temperatur, Luftdruck, Luftfeuchtigkeit, Windrichtung, Windgeschwindigkeit und Niederschlag aufzeichnen. Hinzu kommen Messwerte von Schiffen, treibenden Bojen und Verkehrsflugzeugen. Dieser Aufwand ist nötig, weil Wetter keine Grenzen kennt: Ein Tiefdruckgebiet, das heute über dem Atlantik liegt, kann in zwei Tagen Mitteleuropa erreichen.",
    "Da das Wetter in einer viele Kilometer dicken Luftschicht entsteht, reichen Messungen am Boden nicht aus. An vielen Hundert Orten rund um den Globus steigen deshalb Wetterballons auf, in der Regel zweimal täglich und überall zur selben Zeit, damit die Werte vergleichbar sind. Jeder Ballon trägt eine Radiosonde, ein leichtes Messgerät, das während des Aufstiegs Temperatur, Luftfeuchtigkeit und Luftdruck per Funk übermittelt; aus der Flugbahn lässt sich zudem der Wind berechnen. In etwa 30 Kilometern Höhe platzt der Ballon, weil er sich in der dünnen Luft immer weiter ausgedehnt hat, und die Sonde sinkt an einem Fallschirm zu Boden.",
    "Den Blick von oben liefern Wettersatelliten. Einige stehen in rund 36 000 Kilometern Höhe über dem Äquator und umrunden die Erde genau so schnell, wie diese sich dreht; deshalb haben sie stets denselben Ausschnitt im Blick und zeigen, wie Wolkenfelder ziehen. Andere umkreisen die Erde in viel geringerer Höhe über die Pole und erfassen so nach und nach die gesamte Oberfläche. Satelliten schließen vor allem die Lücken über Ozeanen und Wüsten, wo kaum jemand misst. Wo gerade Regen, Schnee oder Hagel fällt, erkennt das Wetterradar.",
    "Aus Millionen von Einzelwerten muss zunächst ein möglichst vollständiges Bild der Ausgangslage entstehen – eine Aufgabe, die nur Großrechner bewältigen. Sie arbeiten mit Rechenmodellen, die die Atmosphäre in ein dreidimensionales Gitter aus Millionen von Zellen zerlegen. Für jede Zelle berechnet das Modell mithilfe physikalischer Gleichungen, wie sich Druck, Temperatur, Wind und Feuchte in einem kurzen Zeitschritt verändern, und setzt mit dem Ergebnis die Rechnung fort, bis der gewünschte Vorhersagezeitraum erreicht ist. Je enger das Gitter, desto feiner bildet das Modell Berge, Täler und Küsten ab – desto größer ist allerdings auch der Rechenaufwand. Was kleiner ist als eine Gitterzelle, etwa ein einzelnes Gewitter, kann das Modell nur näherungsweise erfassen.",
    "Hier liegt eine erste Grenze der Vorhersage, eine zweite wiegt schwerer: Der Anfangszustand ist nie lückenlos bekannt, und jede Messung ist ein wenig ungenau. In der Atmosphäre können sich solche winzigen Abweichungen aufschaukeln, sodass zwei Rechnungen mit fast gleichen Startwerten nach einigen Tagen ganz verschiedenes Wetter liefern. Bekannt geworden ist dieses Verhalten unter dem Namen Schmetterlingseffekt. Es erklärt, warum die Prognose für den nächsten Tag sehr verlässlich ist, die für den siebten Tag dagegen nur noch eine grobe Richtung angibt – und warum niemand seriös vorhersagen kann, wie das Wetter an einem bestimmten Tag in drei Wochen wird.",
    "Die Wetterdienste machen aus dieser Schwäche eine Stärke. Statt einer einzigen Rechnung starten sie viele Durchläufe mit geringfügig veränderten Anfangswerten. Stimmen die Ergebnisse weitgehend überein, gilt die Vorhersage als sicher; laufen sie auseinander, ist Vorsicht geboten. Aus dem Anteil der Durchläufe, die ein Ereignis zeigen, lässt sich eine Wahrscheinlichkeit ableiten. „Regenwahrscheinlichkeit 70 Prozent“ heißt demnach: In sieben von zehn Fällen mit einer solchen Wetterlage fällt am betreffenden Ort Regen. Die Angabe sagt weder, dass es 70 Prozent des Tages regnet, noch, dass 70 Prozent der Fläche nass werden.",
    "Das letzte Wort hat nicht der Computer. Meteorologinnen und Meteorologen vergleichen die Ergebnisse verschiedener Modelle, gleichen sie mit aktuellen Beobachtungen ab und berücksichtigen örtliche Besonderheiten, die ein Modell leicht übersieht, etwa Nebel in engen Tälern. Sie entscheiden auch, wann eine Unwetterwarnung herausgegeben wird, und müssen dabei abwägen: Wer zu oft warnt, dem glaubt bald niemand mehr; wer zu spät warnt, gefährdet Menschen. Dank dichterer Messnetze und schnellerer Rechner sind Vorhersagen in den vergangenen Jahrzehnten deutlich treffsicherer geworden. Eine Gewissheit über das Wetter von morgen wird es dennoch nicht geben – wohl aber eine immer besser begründete Erwartung."
  ]
});
