/* Deutsch 8 · Schreiben und Aufsätze · Modul 2 (R8): Sachtext zum Zusammenfassen – eigener Text, sieben Abschnitte
   (Einstieg – Messen am Boden – Messen in der Höhe – Rechnen – Grenzen – Wahrscheinlichkeit – Menschen prüfen). */
D7Texte.add({
  id: "schr-wetter-r", titel: "Wie eine Wettervorhersage entsteht", textsorte: "Sachtext", zug: "R8",
  modul: "Schreiben und Aufsätze", unterthema: "Kernaussagen herausarbeiten, zusammenfassen", woerter: 478,
  schwierigkeit: "mittel", lehrplan: "D8 3.2, 2.1", thema: "Entstehung einer Wettervorhersage",
  quelle: "Eigenständig für GRUMI erstellt.", lizenz: "eigener Text", erstellung: "eigener Text für GRUMI",
  zeilennummern: true, probe: false,
  absaetze: [
    "Ein Blick aufs Handy genügt: Morgen Nachmittag soll es regnen, also findet das Fußballtraining wohl in der Halle statt. Was so selbstverständlich aussieht, ist das Ergebnis von viel Arbeit. Bevor eine Wettervorhersage auf dem Bildschirm erscheint, wird gemessen, gerechnet und geprüft.",
    "Am Anfang stehen die Messungen. Auf der ganzen Welt gibt es Tausende von Wetterstationen. Ihre Geräte erfassen rund um die Uhr die Temperatur, den Luftdruck, die Luftfeuchtigkeit, den Wind und den Niederschlag. Auch Schiffe, Bojen im Meer und Flugzeuge liefern solche Werte. Denn das Wetter von morgen hängt davon ab, wie die Luft heute beschaffen ist – nicht nur bei uns, sondern auch weit entfernt.",
    "Wetter entsteht aber nicht nur am Boden. Deshalb steigen an vielen Orten jeden Tag Wetterballons auf. An jedem Ballon hängt ein kleines Messgerät, das seine Werte zur Erde funkt. Der Ballon steigt bis in etwa 30 Kilometer Höhe, also rund dreimal so hoch, wie ein Verkehrsflugzeug fliegt. Dort oben platzt er, und das Messgerät schwebt an einem Fallschirm zurück. Noch viel weiter oben kreisen Wettersatelliten. Sie beobachten die Wolken aus dem All, auch über den Meeren, wo es kaum Messstationen gibt. Wo es gerade regnet oder schneit, zeigt außerdem das Wetterradar.",
    "Alle diese Daten laufen bei den Wetterdiensten zusammen. Dort stehen besonders schnelle Großrechner. Sie arbeiten mit einem Rechenmodell: Der Computer teilt die Lufthülle der Erde in ein Gitter aus Millionen von Kästchen. Für jedes Kästchen berechnet er nach den Gesetzen der Physik, wie sich Temperatur, Luftdruck und Wind in den nächsten Minuten verändern. Mit dem Ergebnis rechnet er weiter – Schritt für Schritt, bis er bei morgen oder übermorgen angekommen ist. Je kleiner die Kästchen sind, desto genauer kann das Modell rechnen. Umso länger braucht der Computer aber auch dafür.",
    "Trotzdem stimmt die Vorhersage nicht immer. Das hat einen einfachen Grund: Niemand kann an jedem Punkt der Erde messen. Der Computer kennt den Anfang also nie ganz genau. Kleine Fehler am Anfang werden mit jedem Rechenschritt größer. Deshalb trifft die Vorhersage für morgen meistens zu, während sie für den siebten Tag schon deutlich unsicherer ist.",
    "Die Wetterdienste gehen mit dieser Unsicherheit offen um. Sie lassen dieselbe Vorhersage viele Male berechnen, jedes Mal mit leicht veränderten Anfangswerten. Zeigen fast alle Rechnungen Regen, ist Regen sehr wahrscheinlich. Kommen ganz verschiedene Ergebnisse heraus, ist die Lage unsicher. So entsteht die Regenwahrscheinlichkeit. Steht dort zum Beispiel „70 Prozent“, bedeutet das: Bei zehn Tagen mit einer solchen Wetterlage regnet es an etwa sieben. Es bedeutet nicht, dass es 70 Prozent des Tages regnet.",
    "Am Schluss prüfen Menschen, was der Computer errechnet hat. Meteorologinnen und Meteorologen, also Fachleute für das Wetter, vergleichen die Ergebnisse und bringen ihre Erfahrung ein. Sie wissen zum Beispiel, in welchen Tälern sich oft Nebel hält. Sie formulieren die Vorhersage und warnen rechtzeitig vor Gewittern, Sturm oder Glatteis. Eine Wettervorhersage ist also Teamarbeit von Messgeräten, Computern und Menschen. Ganz sicher wird sie trotzdem nie sein."
  ]
});
